### ISSUE TITLE
Crash when "thinking about" divide by zero

### ISSUE THREAD

**Issue by smcc** [stp/stp#106]
STP has some long-running issues related to division by zero, which I recently noticed can still bite FuzzBALL in the right (wrong) situation. I think it's not clear exactly what semantics we want for the result, which may be part of the problem. Situations where you write an explicit division by zero in the input file can usually be avoided. But it appears you can also create a formula that involves division of values that are not constrained to be zero, and STP will choose to try values that lead to a division by zero and then crash. For instance in the following example, it appears from a quick look that STP reaches the point of running SAT and getting a satisfying CNF assignment, and then crashes when substituting it back in to check the assignment.

```
y : BV(8);
t4 : BV(8) = BVPLUS(8, y, BVUMINUS(y), 0h01);
QUERY(BVDIV(16, (0h00 @ t4),(0h00 @ y))[0:0] = 0b0);
```
(Also gist: https://gist.github.com/smcc/901e471273743fac922f)

It should certainly be possible to not crash, but I'm not sure what the right behavior should be, since having undefined behavior breaks the assumption that you will always get a consistent output when you plug in a given input. IIRC the SMTLIB2 spec says that division by zero is undefined. If we consider that that gives us license to say, pretend it always returns 1 (I think this was the behavior of early versions and is still present in the code), that would be a nice deterministic choice, but some users might feel it it's weird behavior to show up with no error message.

**Comment by TrevorHansen** [comment]
As per #223, this no longer crashes, but might not do what you expect.
