### ISSUE TITLE
Create tool for reducing failing inputs

### ISSUE THREAD

**Issue by rgov** [stp/stp#11]
In the past I've hit crashes in STP that required some effort to manually reduce down to the smallest failure-inducing input.

Tools like [C-Reduce](http://embed.cs.utah.edu/creduce/) can automatically reduce C files that trigger compiler bugs, using [delta debugging](http://www.st.cs.uni-saarland.de/dd/).

C-Reduce relies on [Delta](http://delta.tigris.org) which could be used to reduce CVC and SMT-LIB2 inputs also. It probably wouldn't be very complicated to write such a script.

**Comment by TrevorHansen** [comment]
ddsmt is good.  It's not perfect, its results will include expressions that can be trivially simplified like (xor true V). It's a minor complaint though. If we supported printing smtlib2 from STP we could post process the results from ddsmt.
