### ISSUE TITLE
BBNodeAIG NOR nodes are really OR nodes

### ISSUE THREAD

**Issue by jamesjer** [stp/stp#117]
There is an unfortunate break statement just before the negation.  I think you want this patch:

```
diff --git a/src/to-sat/AIG/BBNodeManagerAIG.h b/src/to-sat/AIG/BBNodeManagerAIG.h
index 2538621..a97359b 100644
--- a/src/to-sat/AIG/BBNodeManagerAIG.h
+++ b/src/to-sat/AIG/BBNodeManagerAIG.h
@@ -187,7 +187,6 @@ public:
                                 pNode = Aig_Or(aigMgr, children[0].n, children[1].n);
                         else
                                 pNode = makeTower(Aig_Or, children);
-                        break;
                         pNode = Aig_Not(pNode);
                         break;
                 case XOR:
```

**Comment by msoos** [comment]
OK, I now understand the code better and I can check that this is indeed a bugfix and @jamesjer is right. There is still no testcase, but I'm absolutely certain this was a bug in fact.

Thanks for everyone's input and patience. It took a while. I would hope to have a testcase, but this is hard to hit... maybe one day we can build a better fuzzer/tester system.
