### ISSUE TITLE
FatalError() ->control reaches end of non-void function

### ISSUE THREAD

**Issue by msoos** [stp/stp#121]
I have now cleaned up all the warnings so we can actually see the problems. If we now compile, we only get a few warnings, most of which are related to FatalError() being called, but the function it's called from needs a return value. That makes the code behave in an undefined way. We should just come up with a relatively sane return value for each of these. Any ideas what we should return in these cases?

**Comment by msoos** [comment]
Actually, the compiler can cause code to be emitted that crash the system in case of missing return statement (undefined behaviour). I still don't know what to do with this, but I think we should try to return "sane-looking" stuff. The client can then decide what to do since it's their responsibility to handle the error best. Our responsibility is not to crash the app that called us. Obviously the returned data (and possibly our state) will be invalid.

**Comment by msoos** [comment]
Actually, I want to crash the calling process now. If they sent us invalid data, we are not responsible for not crashing them. Also, if we reached an invalid state, we should crash so the error can be reported, rather than "letting" (i.e. forcing) the user to figure out that it's not their fault, it's ours. So I'd like to simply ``release_assert(false);`` where ``release_assert`` is an assert that is always in, like:

```
#define release_assert(a) \
    do { \
        if (!(a)) {\
            fprintf(stderr, "*** ASSERTION FAILURE in %s() [%s:%d]: %s\n", \
            __FUNCTION__, __FILE__, __LINE__, #a); \
            abort(); \
        } \
    } while (0)
```

what do you all think?

**Comment by msoos** [comment]
OK, the calling process will now be assert-failed if if does an incorrect API call -- and later we can replace that with a throw() so it can be caught. I want to really take STP under my wings and do some important changes so we can create a new API that will have a backwards-compatible converter API wrapper for the old interface. We need to make some "though" choices or STP will stagnate :S I hope this is OK.

**Comment by delcypher** [comment]
@msoos 
The original reason for wanting STP to not crash is so that we could do better API testing in the GoogleTest framework. I wasn't aware of ["death tests"](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#death-tests) at the time but I think these could be used to test failing ``release_assert(...)`` failures so I guess this change is okay.
