### ISSUE TITLE
Remove unnecessary includes

### ISSUE THREAD

**Issue by delcypher** [stp/stp#130]
I'm pretty sure some of the `#include`s are superfluous we should use [include-what-you-use](http://code.google.com/p/include-what-you-use/) to strip out useless includes.

**Comment by msoos** [comment]
I'm going to close this. I tried the include-what-you-use and realistically, we can't use it, it's a lot of work to fix the compile afterwards and then I might as well just do it by hand. I think we should concentrate on cleaning up a lot of the code. I'm working on that now, and I think it's best to have focus :)
