### ISSUE TITLE
Flex options for interactive (e.g. pipe) use of SMT-LIB2 mode

### ISSUE THREAD

**Issue by smcc** [stp/stp#132]
Since the SMT-LIB2 standard and STP's implementation thereof support multiple queries interleaved with their output in a single solver session, it seems appealing to use STP in --SMTLIB2 mode connected over a pipe. However this doesn't seem possible with the current version. The most basic problem is that STP's SMT-LIB2 lexer is currently built in "never-interactive" mode, which causes it to always use fread() for input, so it generally won't do any processing until EOF (or maybe when a 8192 byte buffer is full). When running interactively on a Unix terminal this can be seen by needing to type Ctrl-D to get results.

It looks like this change was introduced for Windows compatibility because of a lack of isatty():

2d5522aa4b9c6f98c1ebc905280b13ea01406728

Since we're experimenting with using STP this way for FuzzBALL, I've for now made the opposite decision in our branch:

https://github.com/bitblaze-fuzzball/stp/commit/9c90457a6798a587a03ee06003f9763a1ea8f253

(With my version of Flex this also doesn't seem to bring in a call to isatty(), but I haven't checked on Windows.)

Of course it would be nice to support all the possible use cases at once. In my opinion interactive mode is the better default, and it would be acceptable to always run that way on Windows. On Unix my proposal would be to use non-interactive mode only when the input is a regular file (based on fstat(), or maybe being seekable; I think the latter check is doable in standard C).

The only motivation I'm aware of for a separate non-interactive mode is performance; from my reading of Flex documentation, it's the case that some optimizations are incompatible with interactive mode, so you can't get the optimal best-of-both-worlds with just runtime selection. Potentially we could build a fourth separate Flex lexer, though maybe we'd want to do more benchmarking before resorting to that.

**Comment by msoos** [comment]
Let me close this. The problem has essentially been fixed, and there isn't such a huge benefit to building 2 parsers, really. Also, the `stp < fname` works, though only for CVC as that's default, for SMTv2 you need `stp --SMTLIB2 < fname`. So, all in all, things work as one would expect them to.
