### ISSUE TITLE
CryptoMiniSAT2 checkElimedUnassigned assertion failure

### ISSUE THREAD

**Issue by smcc** [stp/stp#133]
When experimenting with running STP in CryptoMiniSAT 2 mode, I've run into an input that causes STP to crash with an assertion failure inside CMS. Unfortunately I wasn't able to isolate the problem much better than that. ddSMT makes the input smaller but not small in an absolute sense (32k). I also wasn't able to reproduce the problem by outputing a CNF file and running that through a standalone CMS2 binary. 

When running with --cryptominisat, the assertion failure I see is:

stp/lib/Sat/cryptominisat2/Subsumer.cpp:1718: bool MINISAT::Subsumer::checkElimedUnassigned() const: Assertion `solver.assigns[i] == l_Undef' failed.

I read that as "you're only supposed to eliminate a variable that has not been assigned a value, but here's an eliminated variable that was assigned", but this seems like a fairly global invariant so there wasn't any obvious easy next debugging step. Maybe this will ring a bell for @msoos.

The ddSMT-minimized input is at:

https://gist.github.com/smcc/8fd1aa790390b50d5792

The crash also doesn't seem to happen with CMS4 in brief initial testing, so switching to that may also be a future workaround (but I think the dependencies will make integrating that with FuzzBALL a pain).

**Comment by msoos** [comment]
CMS2 is now removed, CMS4 is now the default instead. CMS4 is _much_ more thoroughly tested and is in active development. It should thus be much easier to debug. This bug will no longer be relevant, thankfully :) I hope the new solver is _way_ faster!

Cheers,

Mate
