### ISSUE TITLE
Move to OpenSUSE build service

### ISSUE THREAD

**Issue by msoos** [stp/stp#139]
It would allow us to create packages for more than just Ubuntu which is what we support now. See https://build.opensuse.org/

**Comment by jirislaby** [comment]
FWIW

https://build.opensuse.org/project/monitor/home:jirislaby:statica

**Comment by msoos** [comment]
Wow Wow Wow! Great job, I'm thoroughly impressed! Looks like you can do magic here! I'm terrible at packaging, maybe these packages could become official if you don't mind? I'll dig a bit deeper, but if you could explain me a bit, it'd help too :)

By the way, I heard that the opensuse build system can even build ubuntu packages. Is that still the case?

**Comment by jirislaby** [comment]
Feel free to make them public :). What exactly you would want to help with? It's simply a rpm .spec file describind the build, your sources, and that's it ;). And maybe few patches.

Yes, one can build for ubuntu, fedora, RHEL, SLES, arch, centos, debian and more. The only downside is that I do not know how to write ".spec files" for .deb.

**Comment by msoos** [comment]
Thanks for the info! I've decided this is too much of a hassle to set up for all the distributions. I'm sticking to Ubuntu + Docker for now. I have put the .spec and changes file under /scirpts/.
