### ISSUE TITLE
Assertion encountered using STP as prover of program analysis

### ISSUE THREAD

**Issue by zhaopengli** [stp/stp#155]
Anyone could tell me what is the problem? Is it a bug of STP or something?

Thanks in advance!

Detailed output as the following:

test-sxf: /home/zpli/Workspace/stp-master/lib/Sat/minisat/core_prop/../core_prop/../core/../mtl/Alloc.h:68: const T* Minisat::RegionAllocator<T>::lea(Minisat::RegionAllocator<T>::Ref) const [with T = unsigned int; Minisat::RegionAllocator<T>::Ref = unsigned int]: Assertion `r < sz' failed.
0  test-sxf        0x0000000000eaba2f
1  test-sxf        0x0000000000eabe14
2  libpthread.so.0 0x00002b0de445fc90
3  libc.so.6       0x00002b0de5640d27 gsignal + 55
4  libc.so.6       0x00002b0de5642418 abort + 328
5  libc.so.6       0x00002b0de5639bd6
6  libc.so.6       0x00002b0de5639c82
7  libstp.so       0x00002b0de48f1dea
8  libstp.so       0x00002b0de4974ceb
9  libstp.so       0x00002b0de4974d85 Minisat::Solver_prop::removeSatisfied(Minisat::vec<unsigned int>&) + 149
10 libstp.so       0x00002b0de4976cd1 Minisat::Solver_prop::simplify() + 129
11 libstp.so       0x00002b0de497ddd8 Minisat::Solver_prop::search(int) + 1672
12 libstp.so       0x00002b0de497e13a Minisat::Solver_prop::solve_() + 410
13 libstp.so       0x00002b0de49666ab BEEV::MinisatCore_prop<Minisat::Solver_prop>::solve() + 75
14 libstp.so       0x00002b0de495453b BEEV::ToSATAIG::CallSAT(BEEV::SATSolver&, BEEV::ASTNode const&, bool) + 5179
15 libstp.so       0x00002b0de492f19d BEEV::AbsRefine_CounterExample::CallSAT_ResultCheck(BEEV::SATSolver&, BEEV::ASTNode const&, BEEV::ASTNode const&, BEEV::ToSATBase*, bool) + 61
16 libstp.so       0x00002b0de49129e4 BEEV::STP::TopLevelSTPAux(BEEV::SATSolver&, BEEV::ASTNode const&) + 10244
17 libstp.so       0x00002b0de49140a8 BEEV::STP::TopLevelSTP(BEEV::ASTNode const&, BEEV::ASTNode const&) + 504
18 libstp.so       0x00002b0de4a4316e vc_query_with_timeout + 286
19 test-sxf        0x00000000005e0804 STPSolverImpl::computeInitialValues(klee::Query const&, std::vector<klee::ref<klee::Array>, std::allocator<klee::ref<klee::Array> > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, bool&) + 2612
20 test-sxf        0x00000000005ccd08 CexCachingSolver::getAssignment(klee::Query const&, klee::Assignment*&) + 312
21 test-sxf        0x00000000005cd697 CexCachingSolver::computeValidity(klee::Query const&, klee::Solver::Validity&) + 1303
22 test-sxf        0x00000000005caa65 CachingSolver::computeValidity(klee::Query const&, klee::Solver::Validity&) + 117
23 test-sxf        0x00000000005d9703 IndependentSolver::computeValidity(klee::Query const&, klee::Solver::Validity&) + 163
24 test-sxf        0x000000000059ad77 klee::TimingSolver::evaluate(klee::ExecutionState const&, klee::ref<klee::Expr>, klee::Solver::Validity&) + 311
25 test-sxf        0x00000000005a4b18 klee::ExecutionState::addConstraint(klee::ref<klee::Expr>) + 88
26 test-sxf        0x000000000055f58f klee::Executor::_filterFalsePositiveInLoop(klee::ExecutionState&, std::pair<klee::MemoryObject const*, klee::ObjectState const*>, klee::ref<klee::Expr>) + 927
27 test-sxf        0x00000000005752bc klee::Executor::_findOneObjectPair(klee::ExecutionState&, klee::ref<klee::Expr>, unsigned int, std::pair<klee::MemoryObject const*, klee::ObjectState const*>&) + 1404
28 test-sxf        0x0000000000575a35 klee::Executor::_executeInstructionLoad(klee::ExecutionState&, klee::KInstruction*) + 181
29 test-sxf        0x0000000000578648 klee::Executor::executeInstruction(klee::ExecutionState&, klee::KInstruction*) + 7608
30 test-sxf        0x000000000057a756 klee::Executor::_run() + 326
31 test-sxf        0x000000000057ab69 klee::Executor::runFunctionAsMain(llvm::Function*) + 841
32 test-sxf        0x000000000054878d main + 381
33 libc.so.6       0x00002b0de562bec5 __libc_start_main + 245
34 test-sxf        0x000000000055c6b2
ERROR: STP did not return successfully.  Most likely you forgot to run 'ulimit -s unlimited'

**Comment by zhaopengli** [comment]
Sorry to tell that I have run 'ulimit -s unlimited'!

**Comment by msoos** [comment]
Seem like a bug, yes. Can you please send me the input so I can re-produce?

**Comment by msoos** [comment]
No input was provided by the original reporter. I need to close as I cannot debug this way. If you have the original input file, please attach it here and I'll re-open. Thanks!
