### ISSUE TITLE
Counterexample printing takes significant amount of time

### ISSUE THREAD

**Issue by rsas** [stp/stp#157]
I have the following SMTLIBv2 query:

http://www.cs.utah.edu/~rsas/stp-query.smt2

Running STP w and w/o counterexample shows significant time difference:

```
$ time stp --SMTLIB2 -p stp-query.smt2 > /dev/null

real    0m14.797s
user    0m14.762s
sys     0m0.036s

$ time stp --SMTLIB2 stp-query.smt2 > /dev/null

real    0m4.218s
user    0m4.195s
sys     0m0.024s

```

Any ideas where this difference is coming from?

**Comment by rsas** [comment]
z3 is slower in solving, but faster in printing. Taking

http://www.cs.utah.edu/~rsas/z3-query.smt2

that adds the ``(set-option :produce-models true)`` and a number of ``((get-value ...))`` results in

```
$ time z3 --smt2 z3-query.smt2 > /dev/null

real    0m5.972s
user    0m5.957s
sys     0m0.016s
```

**Comment by msoos** [comment]
Hmmm...the question is, whether it's a static or dynamic difference. With a larger problem, we might have  the same X seconds overhead but not more (=static) or the counterexample printing might take forever (=dynamic difference). It would be good to know. In the first case, we need to get rid of some heavy initialization, in the latter, we need to improve the algorithms. Quite an important difference. Can you please check this using some larger problems?

**Comment by rsas** [comment]
Thanks @msoos for the comment, I'll experiment with larger problems and get back to you.

**Comment by rsas** [comment]
I gave it a try on several bigger problems and the results are confusing.

```
stp (master)
-------------
Problem 1:
-    models: 0m58s
- no models: 0m54s

Problem 2:
-    models: 83s
- no models: 85s 

Problem 3:
-    models: 375s
- no models: 375s
```

Apparently, there is no problem. Unfortunately, I lost the initial query file to see what's going on there...

**Comment by msoos** [comment]
:S That's shame. If you ever find it, please re-open. I lost my copy, too (I used your link to download in the old days, I think) :S Next time, if you could upload it to github gist: https://gist.github.com/ that'd be awesome.

Cheers and thanks again for looking into the problem,

Mate

PS: the file must have been interesting, I think it hit on a nerve where the counter-example generation degraded into some O(n^X) algo where X>1.

**Comment by rsas** [comment]
Thanks @msoos. I think I'll be able to find it again. Stay tuned.

**Comment by TrevorHansen** [comment]
Printing of long bit-vector constants (e.g. 30000 bits) was incredibly slow. Now fixed. I'm guessing that was the problem.
