### ISSUE TITLE
Does the solver have a feature to extract an UNSAT Core?

### ISSUE THREAD

**Issue by srijanshetty** [stp/stp#158]

**Comment by delcypher** [comment]
AFAIK it does not.

**Comment by msoos** [comment]
Actually, CryptoMiniSat4 solver can give you a DRAT trace. From there, you can create an UNSAT core (see http://www.cs.utexas.edu/~marijn/drat-trim/ ). However, it will be an UNSAT core relative to the SAT solver variables, not the SMT variables. There is a mapping somewhere that you can extract (please look a the options and the code) of SAT <-> SMT variables. It won't be easy, though, so buyer beware. You will need to dig _deep_. If you are up to the challenge (I  think about 1 week of work, 8h/day), you can do it. However, we will not be able to help you much other than cursory advice. It'd be fun if you did it, though, but again, it'll be real work.

**Comment by msoos** [comment]
Closing issue since issue owner does not reply.

**Comment by srijanshetty** [comment]
@msoos : Thanks for the pormpt reply and my apologies for being unable to reply sooner. I had to consult with my advisor before I could give a definitive reply. Considering the tight schedule we are in, my advisor thinks that it wouldn't be prudent to undertake the task of implementing an UNSAT core :frowning: . We'll have to think of some way to circumvent this problem though. I'll ping you if I need help.

**Comment by msoos** [comment]
Who is your supervisor? What is your project about? What do you plan to implement into STP? In case you do want to implement something for/into STP, please consider making it such that it can be added to STP without much further work. There is a lot of work already inside that's free, it'd be nice if you contributed.

**Comment by srijanshetty** [comment]
@msoos : The UNSAT core feature is for my undergraduate project and my Professor (the supervisor) thinks that we'll be awfully pressed for time. I'll make sure that any progress I make will make it back into STP.

**Comment by msoos** [comment]
Oh, OK, if undergrad project, than there won't be enough time. UNSAT core would probably take a long while. Good luck with your work and looking forward to the pull request to STP,

Mate
