### ISSUE TITLE
http://people.csail.mit.edu/vganesh/STP_files/stp.html must be redirected

### ISSUE THREAD

**Issue by msoos** [stp/stp#163]
Dear Vijay,

Please redirect the above site to https://sites.google.com/site/stpfastprover/ Thanks!

**Comment by hellovijay** [comment]
Hi Mate,

I am working on this.

-Vijay.

On 3/1/15, Mate Soos <notifications@github.com> wrote:
> Dear Vijay,
>
> Please redirect the above site to
> https://sites.google.com/site/stpfastprover/ Thanks!
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/stp/stp/issues/163


-- 
Cheers,
Vijay Ganesh
http://ece.uwaterloo.ca/~vganesh

**Comment by msoos** [comment]
Best would be to use this inside the <head>:
```
<meta http-equiv="refresh" content="0; url=http://example.com/" />
```

but if you cannot edit the <head>, you can use the javascript version (needs no access to the <head>, you can put it inside the <body>:

```
window.location.replace("http://example.com");
```

It's best not to use both.

Thanks again in advance!

**Comment by msoos** [comment]
Thanks!
