### ISSUE TITLE
stp-master build not going through because of syntax errors

### ISSUE THREAD

**Issue by aruneshpa** [stp/stp#166]
I pulled the source code from the STP repository. While building it, cmake is passing through but the actual build (make) errors out giving some syntax errors. Following is the configuration of my machine-
Linux arunepan-lnx 2.6.18-371.11.1.el5 #1 SMP Mon Jun 30 04:51:39 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.1.2

**Comment by delcypher** [comment]
You need to give more details than this. At a quick glance though your compiler is **far too old**. GCC 4.1.2 was released in 2007!

**Comment by aruneshpa** [comment]
Following is the log -

[arunepan@bgl-ads-780 build]$ make
Scanning dependencies of target constantbv
[  1%] Building CXX object lib/extlib-constbv/CMakeFiles/constantbv.dir/constantbv.cpp.o
[  1%] Built target constantbv
Scanning dependencies of target ASTKind_header
[  2%] Generating ASTKind.cpp, ../../include/stp/AST/ASTKind.h
[  2%] Built target ASTKind_header
Scanning dependencies of target abstractionrefinement
[  3%] Building CXX object lib/AbsRefineCounterExample/CMakeFiles/abstractionrefinement.dir/AbstractionRefinement.cpp.o
/ws/arunepan-bgl/stp-master/lib/Sat/minisat/core/SolverTypes.h:130: error: ISO C++ forbids zero-size array ‘data’
/ws/arunepan-bgl/stp-master/include/stp/STPManager/STPManager.h:304: error: ISO C++ does not support ‘long long’
/ws/arunepan-bgl/stp-master/include/stp/STPManager/STPManager.h:418: error: ‘NodeLetVarVec’ was not declared in this scope
/ws/arunepan-bgl/stp-master/include/stp/STPManager/STPManager.h:418: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/include/stp/AST/ArrayTransformer.h:73: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/include/stp/AbsRefineCounterExample/AbsRefine_CounterExample.h:111: error: a function call cannot appear in a constant-expression
/ws/arunepan-bgl/stp-master/include/stp/AbsRefineCounterExample/AbsRefine_CounterExample.h:110: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp: In member function ‘stp::SOLVER_RETURN_TYPE stp::AbsRefine_CounterExample::SATBased_ArrayReadRefinement(stp::SATSolver&, const stp::ASTNode&, const stp::ASTNode&, stp::ToSATBase*)’:
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:274: error: ‘arrayToIndex’ was not declared in this scope
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:274: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:274: error: redeclaration of ‘std::vector<std::pair<stp::ASTNode, std::map<stp::ASTNode, stp::ArrayTransformer::ArrayRead, std::less<stp::ASTNode>, std::allocator<std::pair<const stp::ASTNode, stp::ArrayTransformer::ArrayRead> > > >, std::allocator<std::pair<stp::ASTNode, std::map<stp::ASTNode, stp::ArrayTransformer::ArrayRead, std::less<stp::ASTNode>, std::allocator<std::pair<const stp::ASTNode, stp::ArrayTransformer::ArrayRead> > > > > > arrayToIndex’
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:274: error: ‘<typeprefixerror>arrayToIndex’ previously declared here
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:286: error: ‘::const_iterator’ has not been declared
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:286: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:311: error: ‘indexToRead’ was not declared in this scope
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:311: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:311: error: redeclaration of ‘std::vector<std::pair<stp::ASTNode, stp::ArrayTransformer::ArrayRead>, std::allocator<std::pair<stp::ASTNode, stp::ArrayTransformer::ArrayRead> > > indexToRead’
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:311: error: ‘<typeprefixerror>indexToRead’ previously declared here
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:315: error: ‘::const_iterator’ has not been declared
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:315: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp: In member function ‘void stp::AbsRefine_CounterExample::applyAllCongruenceConstraints(stp::SATSolver&, stp::ToSATBase*)’:
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:458: error: ‘arrayToIndex’ was not declared in this scope
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:458: error: ‘>>’ should be ‘> >’ within a nested template argument list
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:458: error: redeclaration of ‘std::vector<std::pair<stp::ASTNode, std::map<stp::ASTNode, stp::ArrayTransformer::ArrayRead, std::less<stp::ASTNode>, std::allocator<std::pair<const stp::ASTNode, stp::ArrayTransformer::ArrayRead> > > >, std::allocator<std::pair<stp::ASTNode, std::map<stp::ASTNode, stp::ArrayTransformer::ArrayRead, std::less<stp::ASTNode>, std::allocator<std::pair<const stp::ASTNode, stp::ArrayTransformer::ArrayRead> > > > > > arrayToIndex’
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:458: error: ‘<typeprefixerror>arrayToIndex’ previously declared here
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:466: error: ‘::const_iterator’ has not been declared
/ws/arunepan-bgl/stp-master/lib/AbsRefineCounterExample/AbstractionRefinement.cpp:466: error: ‘>>’ should be ‘> >’ within a nested template argument list
make-3.79.1-p7[2]: *** [lib/AbsRefineCounterExample/CMakeFiles/abstractionrefinement.dir/AbstractionRefinement.cpp.o] Error 1
make-3.79.1-p7[1]: *** [lib/AbsRefineCounterExample/CMakeFiles/abstractionrefinement.dir/all] Error 2
make-3.79.1-p7: *** [all] Error 2

**Comment by msoos** [comment]
Too old compiler. Please update to a newer distribution with a newer compiler. If it still fails to build, please create a new issue.

**Comment by aruneshpa** [comment]
Thank you dan for the suggestion. I just have a small doubt. I have many
versions of gcc installed on my machine. Is there any way to tell the STP's
cmake specifically which version of gcc to use. I do not want to update the
default compiler of my system as it has a lot of dependencies.


Thank you,
Arunesh

On Mon, Mar 16, 2015 at 11:19 PM, Mate Soos <notifications@github.com>
wrote:

> Too old compiler. Please update to a newer distribution with a newer
> compiler. If it still fails to build, please create a new issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stp/stp/issues/166#issuecomment-81839052>.
>



-- 
Thnaks,
Arunesh

**Comment by delcypher** [comment]
When building set the ``CXX`` and ``CC`` environment variables to the paths to the compilers which you wish to use.

e.g.

```
CC=/usr/bin/gcc-4.6 CXX=/usr/bin/g++-4.6 cmake /path/to/stp/source
```

**Comment by delcypher** [comment]
@aruneshpa Oh just another note make sure you delete the contents of the build directory first before running the above ``cmake`` command because when cmake runs it only checks the compiler once. If you run ``cmake`` in an existing build directory it won't try to re-detect the compiler.

**Comment by aruneshpa** [comment]
Thank you Dan for helping me out. I was able to build it successfully. Will
trouble you again if I get stuck.
Thanks,
Arunesh

On Tue, Mar 17, 2015 at 3:14 PM, Dan Liew <notifications@github.com> wrote:

> @aruneshpa <https://github.com/aruneshpa> Oh just another note make sure
> you delete the contents of the build directory first before running the
> above cmake command because when cmake runs it only checks the compiler
> once. If you run cmake in an existing build directory it won't try to
> re-detect the compiler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stp/stp/issues/166#issuecomment-82247968>.
>



-- 
Thnaks,
Arunesh

**Comment by aruneshpa** [comment]
I am getting this error when I trying to build the example/simple directory
Output of camke is---
CC=/router/bin/gcc.c4.7.0-p1 CXX=/router/bin/g++.c4.7.0-p1 cmake ../
-- The C compiler identification is GNU 4.7.0
-- The CXX compiler identification is GNU 4.7.0
-- Check for working C compiler: /router/bin/gcc.c4.7.0-p1
-- Check for working C compiler: /router/bin/gcc.c4.7.0-p1 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /router/bin/g++.c4.7.0-p1
-- Check for working CXX compiler: /router/bin/g++.c4.7.0-p1 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Using STP rooted at /usr/local/src/stp-master/build
STP include paths are: /usr/local/src/stp-master/build/include
STP Static Library target is: libstp_static
STP Shared Library target is: libstp
STP executable: stp
Using STP shared library
Full path to STP binary is STP_FULL_PATH-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to:
/usr/local/src/stp-master/examples/simple/bin


Output of make-
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to
`std::__detail::_List_node_base::_M_unhook()@GLIBCXX_3.4.15'
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to
`std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to
`std::__detail::__prime_list@GLIBCXX_3.4.10'
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to
`std::_Hash_bytes(void const*, unsigned long, unsigned long)@CXXABI_1.3.5'
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to
`std::ctype<char>::_M_widen_init() const@GLIBCXX_3.4.11'


looks like some library issue. But i am not able to figure it out. I tried
it with gcc4.5 and  4.7  , still these linking errors are there.


I have libstdc++.so.6 installed in my /usr/lib

On Tue, Mar 17, 2015 at 4:14 PM, Arunesh Pandey <aruneshpa@gmail.com> wrote:

> Thank you Dan for helping me out. I was able to build it successfully.
> Will trouble you again if I get stuck.
> Thanks,
> Arunesh
>
> On Tue, Mar 17, 2015 at 3:14 PM, Dan Liew <notifications@github.com>
> wrote:
>
>> @aruneshpa <https://github.com/aruneshpa> Oh just another note make sure
>> you delete the contents of the build directory first before running the
>> above cmake command because when cmake runs it only checks the compiler
>> once. If you run cmake in an existing build directory it won't try to
>> re-detect the compiler.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stp/stp/issues/166#issuecomment-82247968>.
>>
>
>
>
> --
> Thnaks,
> Arunesh
>



-- 
Thnaks,
Arunesh

**Comment by msoos** [comment]
You must open a new issue. This is an issue that has been closed an resolved. Please create a new issue. This issue is closed and what you wrote above is not relevant to this issue. That is a new issue.
