### ISSUE TITLE
missing add_dependencies in cmake

### ISSUE THREAD

**Issue by Geof23** [stp/stp#168]
Hi STP -- I ran into a little problem with a concurrent build.

I recommend this patch:
***
diff -urN stp/lib/Sat/cryptominisat2/CMakeLists.txt stp_patch/lib/Sat/cryptominisat2/CMakeLists.txt 
--- stp/lib/Sat/cryptominisat2/CMakeLists.txt	2015-03-26 20:15:37.523595767 -0600
+++ stp_patch/lib/Sat/cryptominisat2/CMakeLists.txt	2015-03-26 20:17:46.987599082 -0600
@@ -21,3 +21,5 @@
     XorSubsumer.cpp
     time_mem.cpp
 )
+
+add_dependencies(cryptominisat2 ASTKind_header)
***
It worked for me!

Thanks for everything -- Geof

**Comment by msoos** [comment]
Thanks :) Cheers!
