### ISSUE TITLE
errors while building stp

### ISSUE THREAD

**Issue by cbe90** [stp/stp#169]
An error occurs while trying to build stp:

> [ 66%] Built target ASTKind_header
[ 66%] Built target stpmgr
[ 66%] Built target stpglobals
[ 66%] Built target abstractionrefinement
[ 66%] Built target AST
[ 66%] Built target simplifier
[ 66%] Built target printer
[ 66%] Built target parser_headersmt
[ 66%] Built target parser_headercvc
[ 66%] Built target parser_headersmt2
[ 66%] Built target parser
[ 66%] Built target cinterface
[ 66%] Built target cppinterface
[ 66%] Built target abc
[ 66%] Building CXX object lib/Sat/CMakeFiles/sat.dir/CryptoMinisat4.cpp.o
In file included from /home/cb/Downloads/stp-master/include/stp/Sat/SATSolver.h:29:0,
                 from /home/cb/Downloads/stp-master/include/stp/Sat/CryptoMinisat4.h:32,
                 from /home/cb/Downloads/stp-master/lib/Sat/CryptoMinisat4.cpp:25:
/home/cb/Downloads/stp-master/lib/Sat/minisat/core/SolverTypes.h:130:65: warning: ISO C++ forbids zero-size array ‘data’ [-Wpedantic]
     union { Lit lit; float act; uint32_t abs; CRef rel; } data[0];
                                                                 ^
/home/cb/Downloads/stp-master/lib/Sat/CryptoMinisat4.cpp: In member function ‘virtual bool stp::CryptoMinisat4::okay() const’:
/home/cb/Downloads/stp-master/lib/Sat/CryptoMinisat4.cpp:76:13: error: ‘class CMSat::SATSolver’ has no member named ‘okay’
   return s->okay();
             ^
/home/cb/Downloads/stp-master/lib/Sat/CryptoMinisat4.cpp:77:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [lib/Sat/CMakeFiles/sat.dir/CryptoMinisat4.cpp.o] Fehler 1
make[1]: *** [lib/Sat/CMakeFiles/sat.dir/all] Fehler 2
make: *** [all] Fehler 2

I just updated to g++ 4.9.2 but it still does not work!

**Comment by msoos** [comment]
Please uninstall CryptoMiniSat4 for the moment. After uninstalling, please re-configure and re-build. There is some turmoil in there. I'll fix it up in the coming weeks. Sorry for the inconvenience!

**Comment by cbe90** [comment]
Thanks, now the installation works. So, using stp with cryptominisat is not possible for the moment, right?

**Comment by msoos** [comment]
Actually, if you install cryptominisat from the GIT it should work out-of-the-box. Also, cryptominisat2 comes included. However, CMS4 is much better. The GIT for it is here: https://github.com/msoos/cryptominisat As long as github says "build passing" for both STP and CMS4, you can build the two together :)

I hope the above helped :)

Mate
