### ISSUE TITLE
Support instrumented builds with Address Sanitizer

### ISSUE THREAD

**Issue by rgov** [stp/stp#17]
[Address Sanitizer](https://code.google.com/p/address-sanitizer/) is a memory error detector, similar to Valgrind, that is available in LLVM 3.1 and GCC 4.8. Unlike Valgrind, it involves adds instrumentation at compile-time and compares very favorably in performance overhead.

I don't see a reason not to support Valgrind in parallel, but it does not work very well on OS X so I cannot test with it.

**Comment by msoos** [comment]
We currently have the fully working "SANITIZE" option in cmake. I think that will do the job. The work by @arsenm is great, but it wasn't integrated in the end, and the SANITIZE option works. I suggest we close this unless @arsenm is happy to integrate that work into STP.
