### ISSUE TITLE
mtl/IntType.h missing

### ISSUE THREAD

**Issue by dr1861** [stp/stp#170]
I cloned a copy of the stp.git repository today, and followed the instructions in INSTALL quickstart to try to build stp. When I run make, I get a nerror saying that mtl/IntType.h  no such file. This of course stops the make process completely.

**Comment by delcypher** [comment]
@dr1861 The INSTALL file was out of date. I've tried to fix this. Basically you need ``minisat`` installed. The configure process shouldn't of completed unless you have an existing install of minisat somewhere.

**Comment by delcypher** [comment]
@dr1861 I'm going to close this issue. If you still have problems after installing ``minisat`` then please re-open the issue.
