### ISSUE TITLE
Export STP version in CMake file for clients

### ISSUE THREAD

**Issue by delcypher** [stp/stp#179]
Clients who import our targets via CMake might want to know STP's version. This should work in the absence of git (i.e. tarballs should build correctly).

**Comment by msoos** [comment]
GIven my explanation of how I intend to package tarballs with cpack ( https://github.com/stp/stp/issues/181 ) the above should be OK. Please check and thanks for the creation of the issue, I would have completely forgotten about it :(

**Comment by delcypher** [comment]
I'll have to test this tomorrow but this looks sensible to me. I'm happy to update the version numbers manually as we only need to this for each release.

**Comment by msoos** [comment]
Oh, OK. I just spent some time extracting the number from GIT, it's not that hard. Currently I have a hard-coded 2.9.99 but as soon as we tag the first release, it will be 3.0.0. From then on the tarballs should have an auto-generated TXT file that describes the version (that cmake gets from the tag) which is read by cmake in case the GIT is not found. This way, we don't need to care, just need to create the tarballs with cmake and tag versions. All else is automated.

**Comment by msoos** [comment]
And for good measure I also added the version into the config.h.in as `STP_VERSION`,  `STP_VERSION_MAJOR` and `STP_VERSION_MINOR`. I guess that makes sense, too.
