### ISSUE TITLE
Support tarball generation

### ISSUE THREAD

**Issue by delcypher** [stp/stp#182]
We need to support the generation of tarballs that work without git and show proper version information.

**Comment by msoos** [comment]
I just added a first version of the CPack system. It will package a file if you do   `make dist` after `cmake ..` in `build/`. It doesn't yet create the file containing the version number but it's not a bad start I think :)

**Comment by delcypher** [comment]
Thanks. We may have to just accept not getting git information into the tarball for now and just manually update the version in the root ``CMakeLists.txt`` that is used when detection of git fails.

I tried doing this hack

```
set(CPACK_SOURCE_IGNORE_FILES "${SourceIgnoreFiles};${CMAKE_SOURCE_DIR}/lib/Util/GitSHA1.cpp.in")

# HACK: Ensure the configured GitSHA1.cpp file ends up in the tarball
# This looks incredibly fragile. There must be a proper way to do this!
set(CPACK_INSTALL_COMMANDS "${CMAKE_COMMAND} -E copy
    ${CMAKE_BINARY_DIR}/lib/Util/GitSHA1.cpp
    ${CMAKE_BINARY_DIR}/_CPack_Packages/Linux-Source/${CPACK_SOURCE_GENERATOR}/${CPACK_SOURCE_PACKAGE_FILE_NAME}/lib/Util/")
```

but

* The copy fails because the ``lib/Util`` directory doesn't exist because the copy happens to early.
* Even the above did succeed it wouldn't work because CMake will just generate a new ``GitSHA1.cpp`` file.

I do have another idea but it is a huge hack

* Don't configure a source file but instead add extra defines containing the git information when compiling the ``Util`` library.
* When creating a tarball add an extra file to the root of the archive (which should work) which the root ``CMakeLists.txt`` file will import if it exists. This extra file will define CMake variables that will provide the git version information.

What do you think?

**Comment by delcypher** [comment]
Given how infrequently we will be generating tarballs (once every release) I would vote for not doing the above hack and just manually modifying the ``CMakeLists.txt`` file prior to every release

**Comment by msoos** [comment]
OK, I agree, good idea. Let's just not do the "tag" thingy I did in the CMakeLists and do the manual update. But let's make sure we only need to configure the version in one place and all the rest takes it from there (as it is now, but instead of taking it from the tag, manually set it)

**Comment by delcypher** [comment]
We are going to be having git tags because we'll be using GitHub's release feature.

I actually quite like the git tag feature because it will show you if you have diverged from a tag. However the git information is kind of broken right now because it isn't regenerated on rebuild so you have to do

```
rm lib/Util/GitSHA1.cpp
make rebuild_cache
```

to get CMake to regenerate the file.

So I suppose we could remove the git tag stuff but I'd like to keep the git SHA1 hash if it's available.

I've started drafting the release (see https://github.com/stp/stp/releases). Note only contributors can see this, also don't click publish! Only click save draft.

**Comment by delcypher** [comment]
@msoos Sorry I was wrong. After a commit the CMake code we use forces a reconfigure so the git tag and git sha1 hash should always be correct.

**Comment by msoos** [comment]
I like your 2nd idea. But we don't need much, only branch off and add one commit to the new branch: remove the SHA hash and add the version number. Then we continue developing on master. This allows the branched-off-version to have a slightly hackish version number (fixed, no SHA tag)

**Comment by delcypher** [comment]
I'm confused, I don't understand which idea you are suggesting. My plan is this.

1. When we are ready to release ``2.2.0`` we add a commit to ``master``  that increments the version number in the cmake lists to ``2.2.0``.
2. We then tag this release with a tag called ``v2.2.0`` and use GitHub's release feature to show this release publically
3. We create a ``2.2.x`` branch of master at the tag we just created. This branch will be used for releases in ``2.2.x`` family (i.e. ``2.2.1``, ``2.2.2`` etc...) which are basically just for back porting bug fixes.
4. Development then continues on ``master``. We increment the version to ``2.3`` in the next commit on ``master`` following the convention of other projects the version number shown is the version we are working towards.

The above approach is nice because all the tags for released versions appear on the ``master`` branch. Also we have branches set up for making bug fix releases if we really need them. I don't want to add new commits to the ``branched-off-version``.

I see you removed the git tag stuff. I'm starting think that we might regret that decision. The fact the SHA1 isn't going to be available in tarballs isn't very nice either. I'm wondering if I should actually try the hack I suggested earlier (when deploying the tarball we add a special file containing the version information that way the user gets the git tag and sha1 in an automatic way).

**Comment by msoos** [comment]
Sorry. I'd go with your suggestion. As for extracting the tag... it's not that hard to add it back, but it's a bit difficult hack to do the tag extraction-creation.

As for using the GitHub release feature -- sure, I'm good with that. But then can we still use the CPack? I thought that the tarball is then auto-generated by GitHub.

**Comment by delcypher** [comment]
@msoos It seems for GitHub releases the source code as it is in the tagged commit is used. This means we cannot do manual tag extraction unless we upload our own tarballs manually, unless we avoid using GitHub releases.

Here's [an example](https://github.com/Z3Prover/z3/releases/tag/z3-4.4.0)

**Comment by msoos** [comment]
I'm a bit confused about this GitHub release system. It generates the tarball from the GIT as far as I can tell so the CPack is completely useless? I know I sound dumb here, but either I can't help or you need to explain this to me, I'm sorry. I don't understand this concept. Can you explain a little bit? Thanks!

**Comment by delcypher** [comment]
@msoos Sorry I don't really have much experience here but AFAICT GitHub generates the tarballs from a particular revision so yes CPack is kind of useless if we rely purely on GitHub but it's always nice to have a fallback

**Comment by msoos** [comment]
OK, so it's as I suspected. In that case, let's drop the CPack, it's one more thing that will code-rot. I'll remove it with a commit and we can revert another time if we need it. Relying on GitHub sounds good to me :)

**Comment by msoos** [comment]
So, this is closed because we'll use github to generate tarball. Done :)

**Comment by msoos** [comment]
Yeah, we used GitHub, so we shall do that in the future. Closed!
