### ISSUE TITLE
Hide non public symbols in the shared library

### ISSUE THREAD

**Issue by delcypher** [stp/stp#183]
We're currently exporting all the symbols in the shared library which isn't a good idea. This prevents a client from using STP as a shared library and using a different version of aig (or anything else that might cause a symbol clash) in their application. We are also implicitly saying that we intend all these symbols to be part of our API which really isn't the case.

We should only export the symbols needed for the `c_interface.h` and `cpp_interface.h` files. [LLVM does this by generating a linker script at run time](https://github.com/llvm-mirror/llvm/blob/master/tools/llvm-shlib/CMakeLists.txt)

**Comment by msoos** [comment]
This seems horrendously complicated. It'd be nice to do but I don't understand half of this. Could you make some headway? I would

**Comment by delcypher** [comment]
I think an easier way for us to achieve this is to use ``-fvisibility=hidden`` and mark our public API functions with the appropriate attributes as [described here](https://gcc.gnu.org/wiki/Visibility)

**Comment by msoos** [comment]
Yup, I am fully on board this one. Messy define stuff but looks more portable and actually quite clean for a define-based solution. Good with me :)

**Comment by msoos** [comment]
This has been done now. Hidden in both Windows and Linux.
