### ISSUE TITLE
Create docker app

### ISSUE THREAD

**Issue by msoos** [stp/stp#184]
Docker seems like a great platform to use: it handles text input&output really well and for stateless systems like STP it's amazing easy and useful. I'll try to make one for our new release, including CMS4 and MiniSat. Probably KLEE should make one too, but that's their pick.

**Comment by delcypher** [comment]
@msoos [KLEE already has one](https://registry.hub.docker.com/u/klee/klee/)

I set it up so on every push to KLEE's GitHub repo a new image is built.

**Comment by msoos** [comment]
Wow. So it builds a new STP every time, too? Can you set one up for STP as well?

**Comment by delcypher** [comment]
@msoos Yes. For KLEE I also reused the TravisCI build scripts to try to deduplicate the effort too

I can set it up for STP but we probably should have stable images too (which we can also set up)

**Comment by msoos** [comment]
It has now been created and runs automatically on every push on Docker Hub. It's at msoos/stp. A short howto has also been added to the README. We can open another issue for more complex Docker image requirements, but for the moment, this should do.
