### ISSUE TITLE
STP seems to give wrong answer

### ISSUE THREAD

**Issue by ericsmithkestrel** [stp/stp#186]
We are trying to upgrade to the latest STP, but we are seeing
discrepancies.  Consider the query below.  The old STP (SVN version
1659) says it is Valid.  But the newest STP says Invalid (and seems to
give a spurious counterexample):

ASSERT( X = 0b0000000000000000000000000000000 );
ASSERT( Y = 0b1111111111111111111111111111111 );
Invalid.

Under the counterexample, I think NODE212 is false, so NODE213 is true,
so the whole thing is true.

This seems to happen even if I ask STP to check the counterexample, which seems especially troubling.

X : BITVECTOR(31);
Y : BITVECTOR(31);
QUERY (
LET NODE134 =
(BVPLUS(32,0bin00000000000000000000000000000001[31:0],(0bin0@Y)[31:0])) IN (
LET NODE136 = (SBVLT(NODE134[31:0],
0bin00000000000000000000000000000000[31:0])) IN (
LET NODE137 = (NOT(NODE136)) IN (
LET NODE212 = (SBVLT((0bin0@Y)[31:0], (0bin0@X)[31:0])) IN (
LET NODE213 = (NOT(NODE212)) IN (
LET NODE214 = (SBVLT((0bin0@X)[31:0], (0bin0@Y)[31:0])) IN (
(NODE214 OR NODE213 OR NODE137))))))));

**Comment by rgov** [comment]
Thanks for your report!

This query returns Valid on e8703fb but Invalid on 04256f9. I'm going to do a git-bisect on this range.

**Comment by rgov** [comment]
```
13b4526815b7e97ca0e7cf7c81b5de40b4a611c6 is the first bad commit
commit 13b4526815b7e97ca0e7cf7c81b5de40b4a611c6
Author: Mate Soos <soos.mate@gmail.com>
Date:   Thu Feb 12 22:19:03 2015 +0100

    An extra rule and some cleanup in simplifying factory

:040000 040000 565537e792819ba83cc7678247edb9607b444299 d5f2c3f6756916a5a6ec20f37641d08dad37da71 M	include
:040000 040000 76c88aa594827448ace16ba7b023f5012ee0ed76 93618e441d3cf3b938a8ba6619d04934ce6f058c M	lib
bisect run success
```

@msoos do you want to look into this one?

**Comment by msoos** [comment]
Damn, I knew it. Yes, sure, I know where this is. Shouldn't have added the extra rule. Fixing...

**Comment by delcypher** [comment]
On 22 Jun 2015 12:20 pm, "Mate Soos" <notifications@github.com> wrote:
>
> Damn, I knew it. Yes, sure, I know where this is. Shouldn't have added
the extra rule. Fixing...

Could you add a query file text case first too?

**Comment by msoos** [comment]
Aaaand this probably guaranteed our failure at the SMT competition. I'm horrible. Sorry :(

**Comment by msoos** [comment]
(also, I added a query test as per @delcypher  suggested)

**Comment by msoos** [comment]
And we would have been 2nd place again if I didn't mess it up: http://smtcomp.sourceforge.net/2015/results-QF_BV.shtml?v=1435013701 I'm sorry. We are 3rd place with MiniSat. The system again managed to mess up the names, it's supposed to have STP- in front (not just "CMsat4"), and it did, of course, throughout.

**Comment by ericsmithkestrel** [comment]
Thanks for the very quick fix!  My head's not really in this, but one thing I was concerned about is that checking the counterexample didn't catch this issue.  Shouldn't counterexample checking be done totally separate from all the simplification rules, etc?  Might help catch things like this in the future.  Thanks again!

**Comment by msoos** [comment]
@ericsmithkestrel I am not as familiar with SMT. However, from experience:
* Parsing is non-trivial. Substituting and checking would only help in case parsing is 100% correct.
* Keeping the parsed, untouched AST in memory for future checking may be prohibitive. In SAT this is certainly the case. Once the SMT/TSAT file has been read in, it may have changed in disk/was read in from stdin, so we must keep it in memory.
* Substitution of the value may not be as simple as it sounds. Many different rules may need to be applied (from modulo addition to handling undefined behaviour such as division by zero)

In light of the above, I'm not surprised there are no trivial validators such as e.g. one written in Python. Writing one for SAT in python can be done in about 10-20 lines of code. Writing one for SMT even in python is at least 1k probably more.

However, given your enthusiasm, I suggest you try wring one and get back to us. We'll gladly add it as MIT licensed code. Good luck and looking forward to hearing back from you!

**Comment by ericsmithkestrel** [comment]
I don't have time to write the evaluator, but I thought STP already had this feature (the -d option is described as "construct counterexample and check it").  So I was surprised that that failed to catch the bug.  (Yes, it would not catch parsing bugs, but I don't think this was a parsing bug.)  Regarding keeping the value in memory, you could do it only if the -d flag was given.

**Comment by msoos** [comment]
I don't have time to write one, either :( As for the `-d` flag, it uses the simplified AST, which means in this case it would not have caught the bug, as the AST simplification was wrong -- which is what is wrong in 99% of the cases. In all complex simplifying solvers, the simplification is what is most often wrong, so checking the solution against the simplified AST helps very little if at all. In SAT, I check every time, and it has caught about 1-2 bugs out of the hundreds I have fixed.

Maybe it's best not to theoretically analyse about the utility, though, best is to simply implement :) I suggest you try doing that and I'll be glad to merge!
