### ISSUE TITLE
getBVUnsigned: Attempting to extract int value from a NON-constant BITVECTOR

### ISSUE THREAD

**Issue by mdempsky** [stp/stp#189]
I'm getting:

    Fatal Error: getBVUnsigned: Attempting to extract int value from a NON-constant BITVECTOR: 
    
    20:(BVPLUS 
      18:0x0000002A
      16:(BVPLUS 
        12:A
        14:B))

from this program:

    VC vc = vc_createValidityChecker();
    Expr falseExpr = vc_falseExpr(vc);

    Expr A = vc_varExpr(vc, "A", vc_bv32Type(vc));
    Expr B = vc_varExpr(vc, "B", vc_bv32Type(vc));

    vc_push(vc);

    Expr AplusB = vc_bv32PlusExpr(vc, A, B);
    Expr AplusBplus42 = vc_bv32PlusExpr(vc, AplusB, vc_bv32ConstExprFromInt(vc, 42));

    assert(0 == vc_query(vc, falseExpr));

    WholeCounterExample wce = vc_getWholeCounterExample(vc);
    uint32_t a = getBVUnsigned(vc_getTermFromCounterExample(vc, A, wce));
    uint32_t b = getBVUnsigned(vc_getTermFromCounterExample(vc, B, wce));
    uint32_t sum = getBVUnsigned(vc_getTermFromCounterExample(vc, AplusBplus42, wce));
    vc_deleteWholeCounterExample(wce);

    assert(sum == a + b + 42);

    vc_Destroy(vc);

when trying to fetch the counter-example value for AplusBplus42 (aka sum).

Am I doing something wrong?  Is there some way to get STP to compute A+B+42 for me?

**Comment by mdempsky** [comment]
Relatedly, if I instead just do

    uint32_t a = getBVUnsigned(vc_getCounterExample(vc, A));
    uint32_t b = getBVUnsigned(vc_getCounterExample(vc, B));
    uint32_t sum = getBVUnsigned(vc_getCounterExample(vc, AplusBplus42));

then the assert fails because it gives me a == 0, b == 0, sum == 0.  But maybe that's a separate issue.

**Comment by msoos** [comment]
Sorry for the late answer. I'll look into this this week. Again, sorry, there were like a 100 deadlines these days, including SMT comp, where there was a bug. Maybe you'd like to re-download STP, there was a fix not long ago.

**Comment by mdempsky** [comment]
I'm using stp/stp@05e2e26 and stp/minisat@3db58943b6ffe855d3b8c9a959300d9a148ab554, which I believe are the latest revisions of each.

**Comment by mdempsky** [comment]
Any suggestions on how to proceed here?  I'd prefer to avoid having to duplicate the expression trees that I believe STP is already maintaining.

**Comment by TrevorHansen** [comment]
As of Austin's commit: ba6a59be21f3f491458c85aa164cddf78b08e17d this can be done as per https://github.com/stp/stp/issues/189#issuecomment-115047061
