### ISSUE TITLE
compilation error on Ubuntu 15.04 64-bit

### ISSUE THREAD

**Issue by zhaopengli** [stp/stp#190]
[ 99%] Building CXX object tools/rewrite_rule_gen/CMakeFiles/rewrite_rule_gen.dir/rewrite_rule_gen.cpp.o
In file included from /home/zpli/Workspace/stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp:53:0:
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h:99:65: warning: unused parameter ‘_id’ [-Wunused-parameter]
                const stp::ASTNode& to_, const int t, int _id = -1)
                                                                 ^
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h: In member function ‘bool Rewrite_rule::timedCheck(int, VariableAssignment&)’:
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h:162:19: error: ‘ITIMER_VIRTUAL’ was not declared in this scope
         setitimer(ITIMER_VIRTUAL, NULL, NULL);
                   ^
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h:162:45: error: ‘setitimer’ was not declared in this scope
         setitimer(ITIMER_VIRTUAL, NULL, NULL);
                                             ^
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h:176:15: error: ‘ITIMER_VIRTUAL’ was not declared in this scope
     setitimer(ITIMER_VIRTUAL, NULL, NULL);
               ^
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/rewrite_rule.h:176:41: error: ‘setitimer’ was not declared in this scope
     setitimer(ITIMER_VIRTUAL, NULL, NULL);
                                         ^
In file included from /home/zpli/Workspace/stp/include/stp/Simplifier/Symbols.h:30:0,
                 from /home/zpli/Workspace/stp/include/stp/Simplifier/VariablesInExpression.h:30,
                 from /home/zpli/Workspace/stp/include/stp/Simplifier/SubstitutionMap.h:31,
                 from /home/zpli/Workspace/stp/include/stp/Simplifier/simplifier.h:32,
                 from /home/zpli/Workspace/stp/include/stp/Simplifier/bvsolver.h:29,
                 from /home/zpli/Workspace/stp/include/stp/STPManager/STP.h:32,
                 from /home/zpli/Workspace/stp/include/stp/Printer/printers.h:34,
                 from /home/zpli/Workspace/stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp:39:
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/Functionlist.h: In member function ‘void Function_list::checkFunctions()’:
/home/zpli/Workspace/stp/include/stp/Util/find_rewrites/Functionlist.h:129:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       assert(functions[i].GetValueWidth() == bits);

Configuration info. as below:

zpli@ubuntu:~/Workspace/stp/build$ sudo cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- You can choose the type of build, options are:Debug;Release;RelWithDebInfo;MinSizeRel
-- Doing a RelWithDebInfo build
-- Building shared library currently broken due to mix of C++/C code
-- Performing Test HAVE_FLAG_-fPIC
-- Performing Test HAVE_FLAG_-fPIC - Success
-- Performing Test HAVE_FLAG_STD_CPP11
-- Performing Test HAVE_FLAG_STD_CPP11 - Success
-- Performing Test HAVE_FLAG_STD_GNUCPP11
-- Performing Test HAVE_FLAG_STD_GNUCPP11 - Success
-- Performing Test HAVE_FLAG_STD_GNUCPP0X
-- Performing Test HAVE_FLAG_STD_GNUCPP0X - Success
-- Performing Test HAVE_FLAG_STD_CPP0X
-- Performing Test HAVE_FLAG_STD_CPP0X - Success
-- Performing Test HAVE_FLAG_STDLIB_LIBCPP
-- Performing Test HAVE_FLAG_STDLIB_LIBCPP - Failed
-- Performing Test HAVE_FLAG_CPP03
-- Performing Test HAVE_FLAG_CPP03 - Success
-- Performing Test HAVE_FLAG_-Wall
-- Performing Test HAVE_FLAG_-Wall - Success
-- Performing Test HAVE_FLAG_-Wextra
-- Performing Test HAVE_FLAG_-Wextra - Success
-- Performing Test HAVE_FLAG_-pedantic
-- Performing Test HAVE_FLAG_-pedantic - Success
-- Performing Test HAVE_FLAG_-Wunused
-- Performing Test HAVE_FLAG_-Wunused - Success
-- Performing Test HAVE_FLAG_-Wsign-compare
-- Performing Test HAVE_FLAG_-Wsign-compare - Success
-- Performing Test HAVE_FLAG_-Wtype-limits
-- Performing Test HAVE_FLAG_-Wtype-limits - Success
-- Performing Test HAVE_FLAG_-Wuninitialized
-- Performing Test HAVE_FLAG_-Wuninitialized - Success
-- Performing Test HAVE_FLAG_-Wno-deprecated
-- Performing Test HAVE_FLAG_-Wno-deprecated - Success
-- Performing Test HAVE_FLAG_-Wstrict-aliasing
-- Performing Test HAVE_FLAG_-Wstrict-aliasing - Success
-- Performing Test HAVE_FLAG_-Wpointer-arith
-- Performing Test HAVE_FLAG_-Wpointer-arith - Success
-- Performing Test HAVE_FLAG_-Wheader-guard
-- Performing Test HAVE_FLAG_-Wheader-guard - Failed
-- Performing Test HAVE_FLAG_-Wformat-nonliteral
-- Performing Test HAVE_FLAG_-Wformat-nonliteral - Success
-- Performing Test HAVE_FLAG_-Winit-self
-- Performing Test HAVE_FLAG_-Winit-self - Success
-- Performing Test HAVE_FLAG_-Wunreachable-code
-- Performing Test HAVE_FLAG_-Wunreachable-code - Success
-- Checking for C++ hash_set implementation...
-- Performing Test HAVE_HASH_SET_STD
-- Performing Test HAVE_HASH_SET_STD - Success
-- C++ hash_set found as std::unordered_set in <unordered_set>
-- Checking for C++ hash_multiset implementation...
-- Performing Test HAVE_HASH_MULTISET_STD
-- Performing Test HAVE_HASH_MULTISET_STD - Success
-- C++ hash_multiset found as std::unordered_multiset in <unordered_set>
-- Checking for C++ hash_map implementation...
-- Performing Test HAVE_HASH_MAP_STD
-- Performing Test HAVE_HASH_MAP_STD - Success
-- C++ hash_map found as std::unordered_map in <unordered_map>
-- GIT hash found: e36745bbef14f808075e4cf1107ffbfcdf422c70
-- PROJECT_VERSION: 2.0.99
-- PROJECT_VERSION_MAJOR: 2
-- PROJECT_VERSION_MINOR: 0
-- PROJECT_VERSION_PATCH: 99
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   program_options
-- Found CryptoMiniSat4 and C++11, allowing --cryptominisat4 option
-- CryptoMiniSat4 dynamic lib: libcryptominisat4
-- CryptoMiniSat4 static lib:  libcryptominisat4.a
-- CryptoMiniSat4 static lib deps: m4ri
-- Finding dynamic minisat libs...
-- Found minisat: /usr/local/lib/libminisat.so  
-- OK, found Minisat library under /usr/local/lib/libminisat.so and Minisat include dirs under /usr/local/include
-- Found BISON: /usr/bin/bison (found version "3.0.2") 
-- Found FLEX: /usr/bin/flex (found version "2.5.39") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.9") 
-- Final CXX flags -std=c++11  -fPIC -Wall -Wextra -pedantic -Wunused -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wformat-nonliteral -Winit-self -Wunreachable-code
-- Found Perl: /usr/bin/perl (found version "5.20.2") 
-- Performing Test HAVE_C_FLAG_-fPIC
-- Performing Test HAVE_C_FLAG_-fPIC - Success
-- Detected python site package directory /usr/lib/python2.7/dist-packages
CMake Warning at CMakeLists.txt:407 (message):
  Testing is disabled

-- Configuring done
-- Generating done
-- Build files have been written to: /home/zpli/Workspace/stp/build

**Comment by zhaopengli** [comment]
fixed by adding "#include <sys/time.h>" in  
"include/stp/Util/find_rewrites/rewrite_rule.h"

**Comment by alexkamp** [comment]
Any plans to make a pull request with this additional include? If you don't want to, I am basically one mouse-click away. I just don't want to steal your fame ;)

PS: Same problem in a docker container which uses the ubuntu:14.04 base image. Same fix works.

**Comment by msoos** [comment]
Fixed in latest push. Thanks to @alexkamp for the fix and to @zhaopengli  for the bugreport!
