### ISSUE TITLE
Copyright information in LICENSE

### ISSUE THREAD

**Issue by mdimjasevic** [stp/stp#199]
In the `LICENSE` file only Vijay Ganesh is listed as the copyright holder. However, this is in contradiction with e.g. the copyright header in `bindings/python/stp/stp.py` where (C) 2014 Jurriaan Bremer is also listed. Also, the `AUTHORS` file lists quite a few authors, but it is not clear from the file if they're copyright holders.

What I would like to ask is to make it clear if an author is also a copyright holder (this doesn't have to be the case in general). Please clarify this in the `LICENSE` file and elsewhere if appropriate.

Making copyright information clear is useful when packaging STP, e.g. for Debian, which I've been working on per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789055.

**Comment by hellovijay** [comment]
Dear Marko,

Currently only Vijay Ganesh is the copyright holder. (In the future, some
of the leader maintainers may become copyright holders as well.)

However, we may have different copyright holders for bindings.

One way you could package STP is to package it without the bindings, and
redirect users to the STP repo for bindings.

Cheers,
Vijay Ganesh.

**Comment by mdimjasevic** [comment]
Hi Vijay,

There are other places where other authors are listed as well, e.g. `lib/AST/ASTmisc.cpp`. What is confusing about a file like that is that it lists a license, but it doesn't say who is the copyright holder. As a matter of fact, this file in particular with the AUTHORS tag suggests that both you and Trevor Hansen are copyright holders (though the copyright is not really stated), but then you said you are the only copyright holder of STP.

**Comment by msoos** [comment]
Well.. I think Trevor Hansen should be contacted for this issue, to be on the safe side of the legal fence as he contributed a measurable chunk of the code. I wouldn't be surprised if he was fine with Vijay being the only copyright holder, but I think an email would do good.

As for others:  my contributions were relatively minor and I'm happy to give up copyright for them. I believe Dan, Ryan and Wi, would all do the same, considering that their contributions too, were relatively minor.

I know this is somewhat politicised issue (as all copyright is), so maybe you can give some guidance on how this works and whether we really need to contact some/all these people.

In good faith and with hopes that all this is easy to clear up,

Mate

PS: Note that STP source-includes three components in its standard build for Linux. I just updated the file (by removing some components, hurray!) LICENSE_COMPONENTS. These three for Linux are: libabc, CVC's SMT-LIB parser, and Bit::Vector. The other components listed there are either linked (e.g. boost) or not built for standard use (e.g. test frameworks).

**Comment by mdimjasevic** [comment]
I am not familiar with how STP was developed, so I don't know if you made any agreements on how copyright is to be handled. Also, keep in mind that I am not a lawyer so what follows is my humble and personal understanding of the situation.

By the law, everyone has their own copyright on their creative works. One has to take action to assign their copyright to someone else. The project being licensed under a permissive license (the MIT/Expat license), the license doesn't even dictate an automatic license of someone's contribution to the project (which would be the case with a copyleft license such as GPLv3).

Therefore, the way I see it, if it hasn't been done so far, each STP contributor should be contacted to confirm their contributions are licensed under such and such terms (in this case, I assume it would be the MIT/Expat license). The next step would be to update each source file and update copyright notices accordingly: if an author retains copyright, designate it as e.g. (C) 2008 John Smith and state the license of the contributions/file; if the author assigned their copyright to Vijay and Vijay is the sole copyright holder in that file, then state e.g. (C) 2009 Vijay Ganesh and again state the license of the file (e.g. MIT/Expat license).

Luckily, you have the list of contributors so it shouldn't be that hard to resolve this issue.

I don't know if there are legal definitions of how big a contribution has to be in order for it to be copyrighted. But having contributed e.g. two 10-line updates would in my opinion account for a copyright.

When it comes to including code from other projects, I don't know much about it. I know that for example you cannot embed GPL-ed code you don't have copyright of and then claim the project to be MIT/Expat-licensed. This has to do with linking and probably something else, but again my knowledge about this topic is very limited.

**Comment by msoos** [comment]
Let's try to send around an email and ask everyone's permission to put the work under Vijay's copyright. I'll update this issue once we resolved these.

It seems that all the other code that is included as-is into the codebase needs to keep its copyright, so the authors of the 3 libraries I mentioned need to be included.

I'll create a separate file, "COPYRIGHT" with all the details of this so it'll be easier to package next time.

@hellovijay  -- would you like to draft this mail and send it to everyone who contributed any significant amount of code? I guess that's Travis, Wi, Ryan, and Dan. As I mentioned, I give up my copyright to you (but would still like to remain an author). I'd appreciate a CC to me, so I can see :) Thanks a lot in advance!

**Comment by msoos** [comment]
(oh, I don't know why I wrote Wi, I meant Khoo)

**Comment by khooyp** [comment]
I'm fine with assigning the copyright to Vijay. Thanks!

**Comment by delcypher** [comment]
> I give up my copyright to you (but would still like to remain an author). 

Isn't giving up your copyright saying that you are not the author? They sound incompatible.

**Comment by mdimjasevic** [comment]
Being an author and a copyright holder are two separate things. For example, if you write software for your employer, it's very likely you're not a copyright holder, but your employer is. You're still an author (though companies usually don't list authors/developers anywhere in the software).

Since it's "all rights reserved" by default by the law, it's up to the copyright holder to say how much of it they want to give to another entity. All rights can be given to another entity without giving up on their own rights; in this case both the author and the entity receiving the copyright have equal rights. Then there is also the case of surrendering all of your rights to another entity. And then there are things in between.

If you want to, sure, you can give Vijay all your copyrights. In that case Vijay can do as he pleases with your original copyright, including making it MIT/Expat licensed, making it proprietary (OK, the MIT/Expat license allows that anyway), or whatever. However, to make this licensing issue clear, it would suffice for everyone to license their contributions under the MIT/Expat license and thereby retain copyright on STP. However, I don't know if you as authors have any prior agreements on copyright.

**Comment by hellovijay** [comment]
I agree with Mate on this.

Mate,

Yes, could you please draft an appropriate email and ask around?

-Vijay Ganesh.

**Comment by hellovijay** [comment]
Once again, I am in total agreement with Mate.

-Vijay.

**Comment by hellovijay** [comment]
Hi Marko,

As Mate suggested, we should ask everyone whether they are will to give up
their copyright.

I am quite happy to share the copyright. STP wouldn't be where it is
without the contributions of Trevor, Mate, Dew, Ryan, Dill, Khoo, and
others.

If I were to highlight the most important contributors, I would say they
would be myself, Trevor Hansen, Mate Soos, and David L. Dill.

Why don't we put these four names (assuming they agree) as the copyright
holders, assuming the other authors are okay with releasing their
copyrights?

Cheers,
Vijay Ganesh.

**Comment by mdimjasevic** [comment]
Hi Vijay,

I'm glad to hear this is going so smoothly! Making sure everyone is fine with whatever you/all of you want to do is the way to go.

Cheers,
Marko

**Comment by delcypher** [comment]
@hellovijay @msoos @mdimjasevic 

I do not wish to give up my copyright.

**Comment by msoos** [comment]
Cool, let me have the copyright, too, actually. I did put quite a bit of work, so maybe that makes sense. Let's ask Ryan as well. Trevor hasn't yet replied, so we may need to assume that he has copyright, too.

**Comment by hellovijay** [comment]
Sounds great Dan and Mate.

Can you please go ahead do the needful, and modify the COPYRIGHT file
appropriately.

Thanks again to all of you for your great work!

Cheers,
Vijay Ganesh.

**Comment by rgov** [comment]
While I acknowledge that the core of STP was developed by others, I have contributed a few changes and source files, and I'd like to retain copyright over them. This seems to be standard in many projects I've contributed to, including [LLVM's Developer Policy](http://llvm.org/docs/DeveloperPolicy.html#copyright).

**Comment by mdimjasevic** [comment]
Again, I'm glad this has been worked out.

I'd suggest you all go through files you've touched/contributed to and update it it such that it reads something along:

```
Copyright 2010-2012 <your name here>
          2008-2015 <another contributor's name>
```

followed by the license.

Finally, all of you that have copyright out to be listed in the main LICENSE file, along the lines suggested above.

**Comment by msoos** [comment]
Note the diff. I have updated all the years given the GIT log that was available to me. Please take a look, but I think according to what I know, it should be fine. @mdimjasevic  is this good for your requirements?

**Comment by hellovijay** [comment]
Dear Mate, Ryan, and Dan,

I made a minor edit, and added David Dill's name as well to the COPYRIGHT
file. Kindly git pull.

Thanks for taking care of this issue.

Cheers,
Vijay Ganesh.

**Comment by mdimjasevic** [comment]
Hi all,

Would you mind combining the COPYRIGHT and LICENSE files? This way it is still a bit confusing because the COPYRIGHT file only lists copyright holders without stating a license, and then the LICENSE file lists only Vijay as the copyright holder.

**Comment by msoos** [comment]
Hi @mdimjasevic , I hope this fixes the issue :) Thanks for the hand-holding, really helped! In case this really does fix the issue, please close :) Thanks again for al,

Mate

**Comment by mdimjasevic** [comment]
Hi @msoos, thanks a lot for this! I am glad to see this being worked on so promptly!

One more related question from a random walk through the repo - are CMakeLists.txt files considered to be software as well? I know next to nothing about CMake, but these look like programs to me. Would you mind adding copyright notices to them as well?

**Comment by msoos** [comment]
How about now? :)

**Comment by msoos** [comment]
I think this can now be closed, since all the issues have been resolved I believe. @mdimjasevic please re-open if there is anything missing. As far as I know, all files now contain proper copyright headers, copyrights have been assigned, licenses have been properly identified. Please re-open if you have any further issued, we'd be glad to help! Thanks!

**Comment by mdimjasevic** [comment]
Hi @msoos,

The source tree still has files that don't have a copyright header as discussed in this issue. Some files don't mention autors nor copyright holders. I suggest putting those that touched the files as copyright holders. Some files simply list authors, but don't state who has copyright. Here I suggest replacing "authors" with "copyright 2015" followed by the same authors listed. Some files have a field "BEGIN DATE" - maybe that can be taken as the copyright year. E.g.:

```
Copyright 2015 Jane Doe
          2015 John Smith
```

I started going through the STP source tree with the goal of identifying files that don't have an appropriate copyright header. However, when I reached a list of about 40 files and realized that so many files miss the header, I stopped pinning down absolutely all the files. However, most of them seem to follow a header template or at least have very similar beginnings, e.g.

```
// -*- c++ -*-
/********************************************************************
 * AUTHORS: Unknown
 *
 * BEGIN DATE: November, 2005
 *
Permission is hereby granted, free of charge, to any person obtaining a copy
...
```

Maybe you could write a script that would walk through the whole source tree, identify such files, and do automatic updates to a proper copyright header. In this very example someone does have copyright - if no one else, then likely @delcypher.


Then I found something you should think about: `cmake/modules/GetGitRevisionDescription.cmake` and `cmake/modules/GetGitRevisionDescription.cmake.in` are copyrighted by the Iowa State University, 2009-2010, under the Boost Software License, Version 1.0. I am not a lawyer, but in my opinion the Boost Software License is compatible with the Expat (MIT) license that you use for STP: the Boost Software License is a permissive free software license and you retained the copyright notice, hence I believe you should be set.

`cmake/modules/MacroPushRequiredVars.cmake` asks the reader to refer to the COPYING-CMAKE-SCRIPTS file to see more about "the BSD license", which the source file is copyrighted under. However, the copyright file is missing.

There could be many more files with an unclear copyright, but it'd be too much for me to walk the whole source tree.

**Comment by msoos** [comment]
I am not so sure that the build system really needs to be that well documented, to be honest. It doesn't get built into the final executable. Even the GPL only requires the build system to be provided but puts no constraint on its license. Please correct me if I'm wrong.

As for the " AUTHORS: Unknown", I'll take a look and fix them all. Again, it think from the perspective of using the system, it's good enough that whoever wrote it it's under MIT license. Trying to pin down the authors of each kernel file for example might make the files hundreds of lines longer by listing each individual author. It's unnecessary -- whoever wrote it clearly released it under the license it's under and that seals the deal. Again, please correct me if I'm wrong.

**Comment by msoos** [comment]
Okay, "Unknown" authors fixed. Next up is the build system.

**Comment by msoos** [comment]
OK, I think I managed to fix up the issues with the build system too. Please take a look!

**Comment by msoos** [comment]
@mdimjasevic Hey, I think I managed to fix all the issues. Can you please take a look?

Thanks!

Mate

**Comment by mdimjasevic** [comment]
Hi @msoos,

Thanks for working on this! I do appreciate it a lot!

I am not a lawyer nor a copyright expert, so whatever I say here is my own opinion and understanding of copyright and licensing only, which could be wrong. That said, I still think every source file ought to have a copyright header saying who holds copyright and which license it is available under, and not simply listing authors. STP is not even close to the the Linux kernel's size so there are not as many authors nor source files.

One reason why every source file should have a copyright header is because someone might want to cherry-pick source code files out of STP and use them in another project. This is what I believe you STP authors have done with external libraries/projects residing in the `lib` directory. Not having a copyright header in such cherry-picked files makes things very messy.

Nevertheless, I suppose that the situation wrt to this issue is good enough. It is definitely much better than before! Therefore, if you don't feel like updating all file headers, go ahead and close this issue.

**Comment by msoos** [comment]
I think all has been indicated now, as per previous 2 commits. All good, thanks again!

Closing.

**Comment by mdimjasevic** [comment]
Btw, for a future reference, I just learned about a tool that is very useful for checking file licenses: [licensecheck](https://packages.debian.org/jessie/devscripts). So by simply running:

```bash
licensecheck -r *
```

in the root directory of STP you get to learn a lot about licenses used and about files that are missing copyright.

**Comment by mdimjasevic** [comment]
@msoos, @rgov,

I'm still looking at copyright of STP and `scripts/stp-bisect.sh` has no copyright header nor indication of who is an author. However, `git log -- scripts/stp-bisect.sh` says that there is only one commit to the file and that the author is Ryan Govostes. Would any of you mind updating the file with an appropriate copyright header?

It's similar with `tests/generated-tests/generators2/ArrayGenerator.java`.

**Comment by msoos** [comment]
stp-bisect -- I fixed that yesterday, forgot to push. I pushed now. As for ArrayGenerator, that needs to go to the trashbin probably. I'll do that tonight (after checking). Thanks!

**Comment by mdimjasevic** [comment]
@delcypher , @msoos ,

I see you have commits in `lib/extlib-abc`. I'm curious if you were simply removing files (and possibly adding copyright headers) or if you made changes there as well. Because I want to reflect it in a copyright file that will be in the Debian package. If you did make changes, are you aware that the MIT-variant license of ABC is different from the variant you use for STP? In such case, I think it'd be best if you licensed your changes in ABC under the same license ABC uses.

**Comment by msoos** [comment]
No changes. It was simply moved around without any changes. In the long run we wish to remove that internal dependency and create an external dependency and not create copyright nightmare with multiple licenses and such. I will now create a new release so you can package! :)
