### ISSUE TITLE
Move to CryptoMiniSat 2 as a submodule

### ISSUE THREAD

**Issue by rgov** [stp/stp#2]
We should use a Git submodule for [CryptoMiniSat 2](https://github.com/msoos/cryptominisat/tree/cryptominisat-2.9.8), and ensure that all references to its license are updated to reflect the fact that it is MIT licensed.

**Comment by msoos** [comment]
I cannot make CMS2 a submodule: It's a different version that's here and it's tuned for STP. If I make it a submodule, I would have to get back to this really old piece of code.

On the other hand, CMS4 is faster (we got 2nd place at the competition), and its integration is clean. 

I suggest we keep the status quo, and instead try to nudge people to use CMS4 which is actively developed and works well with cmake.
