### ISSUE TITLE
Running tests in a build with the lit tool

### ISSUE THREAD

**Issue by mdimjasevic** [stp/stp#200]
I've been trying to build the 2.1.0 release of STP and run tests that come with it. This is what I use in a debian/rules file:

```make
override_dh_auto_configure:
        mkdir -p build
        cd build && cmake -DENABLE_TESTING=ON \
        -DENABLE_PYTHON_INTERFACE=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DALSO_BUILD_STATIC_LIB=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_ASSERTIONS=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ../

override_dh_auto_build:
        cd build && $(MAKE)
```

I get the following error:

```
-- Finding dynamic minisat libs...
-- Found minisat: /usr/lib/libminisat.so  
-- OK, found Minisat library under /usr/lib/libminisat.so and Minisat include dirs under /usr/include
-- Found BISON: /usr/bin/bison (found version "3.0.2") 
-- Found FLEX: /usr/bin/flex (found version "2.5.39") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.9") 
-- Final CXX flags -std=c++11 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -fPIC -Wall -Wextra -pedantic -Wunused -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wformat-nonliteral -Winit-self -Wunreachable-code
-- Found Perl: /usr/bin/perl (found version "5.20.2") 
-- Performing Test HAVE_C_FLAG_-fPIC
-- Performing Test HAVE_C_FLAG_-fPIC - Success
-- Detected python site package directory /usr/lib/python2.7/dist-packages
-- Testing is enabled
CMake Error at tests/CMakeLists.txt:10 (message):
  Could not find lit tool.  Try setting LIT_TOOL to the full path for lit
```

This happens in Debian 8.2, with the llvm-3.5-tools package installed, where I believe the lit tool in question should be.

Is there something I could do to make the build process aware of the system-wide installation of lit?

As a side note, I see the same bug was reported a year ago in Cryptominisat: https://github.com/msoos/cryptominisat/issues/195 (I don't have it installed).

@msoos, I assume you would know what to do.

**Comment by delcypher** [comment]
@mdimjasevic I'm actually the person who set up the testing infrastructure so I'm the more appropriate person to ask. As the error message suggests you need to tell it where to find ``lit``.

``lit`` is available from PyPi (``pip install lit``). Alternatively you can try using ``llvm-lit`` (which is basically the same) but you'll need to tell CMake where to find it when configuring. E.g.

```
$ cmake -DLIT_TOOL=/usr/bin/lit /path/stp/source/root
```

I've never recommended using ``llvm-lit`` because it **does not ship with LLVM**. Debian and Ubuntu do ship it with ``llvm-dev`` but other distros do not which is why I suggest just getting ``lit`` from PyPi.

**Comment by mdimjasevic** [comment]
thanks, @delcypher for the hint. Since this is for creating a package for STP in Debian, I decided to go the Debian way, i.e. installing it with `apt-get`, i.e. adding it to `Build-Depends` in `debian/rules`.

The next problem I stumbled upon is that now I get this error:

```
-- Testing is enabled
CMake Error at tests/CMakeLists.txt:39 (add_subdirectory):
  The source directory

    /home/vagrant/stp-2.1.0/utils/gtest

  does not contain a CMakeLists.txt file.
```

This is caused by `tests/CMakeLists.txt:39`:

```cmake
add_subdirectory(${GTEST_PREFIX} gtest)
```

If I comment out that line (which points to an otherwise empty directory), it's all fine and the build process goes through. However, I am not sure any tests are actually executed. How do I check in the output if any tests were run?

**Comment by msoos** [comment]
You need to initialized the git submodules :) Here:

```
git submodule init
git submodule update
```

That will do the trick :) Then the build will succeed. I hope this helps!

**Comment by mdimjasevic** [comment]
Yup, silly me, I figured that out in the meantime with submodules. Still, what should I be expecting in the output to see tests executing?

**Comment by msoos** [comment]
`make check` will do the trick :)

**Comment by msoos** [comment]
Actually, all of this is supposed to be in https://github.com/stp/stp/blob/master/INSTALL.md Please tell me how it could be improved!

**Comment by delcypher** [comment]
@msoos

Could you add an issue to produce a better error message when the submodules are missing and assign it to me?

I'm on my mobile so I can't look it now but I should be able to in the next few days.

**Comment by mdimjasevic** [comment]
@msoos , thx for a pointer to these very detailed instructions! I can execute tests now.

I'm 99% sure I'm missing something again, but are some tests expected to fail? In particular, I see failures in C-api-tests:

```
********************
Testing Time: 41.55s
********************
Failing Tests (25):
    STP C-api-tests Unit tests :: array-cvcl-02Tests/array_cvcl02.one
    STP C-api-tests Unit tests :: b4-c2Tests/b4_c2.one
    STP C-api-tests Unit tests :: b4-cTests/b4_c.one
    STP C-api-tests Unit tests :: if-checkTests/if_check.one
    STP C-api-tests Unit tests :: interface-checkTests/interface_check.ONE
    STP C-api-tests Unit tests :: mdempskyTests/mdempsky.one
    STP C-api-tests Unit tests :: multi-query-bugTests/multi_query_bug.many
    STP C-api-tests Unit tests :: multi-query-bugTests/multi_query_bug.one
    STP C-api-tests Unit tests :: multiple-queriesTests/multiple_queries.one
    STP C-api-tests Unit tests :: parsefile-using-cinterfaceTests/parsefile.CVC
    STP C-api-tests Unit tests :: printTests/print.one
    STP C-api-tests Unit tests :: push-popTests/push_pop.two
    STP C-api-tests Unit tests :: reported_errorTests/reported_issue_120.one
    STP C-api-tests Unit tests :: sbvdivTests/sbdiv.one
    STP C-api-tests Unit tests :: simplifyTests/simplify.one
    STP C-api-tests Unit tests :: simplifyTests/simplify.two
    STP C-api-tests Unit tests :: stp-array-modelTests/stp_array_model.one
    STP C-api-tests Unit tests :: stp-counterexTests/stp_counterex.one
    STP C-api-tests Unit tests :: stp-div-001Tests/stp_div.one
    STP C-api-tests Unit tests :: stp-test3Tests/stp_test.MS
    STP C-api-tests Unit tests :: stp-test3Tests/stp_test.MSP
    STP C-api-tests Unit tests :: stp-test3Tests/stp_test.SMS
    STP C-api-tests Unit tests :: stpcheckTests/extend_adder_notexpr.one
    STP C-api-tests Unit tests :: timeoutTests/timeout.one
    STP C-api-tests Unit tests :: yTests/y.one

  Expected Passes    : 40
  Unexpected Failures: 25
tests/api/C/CMakeFiles/C-api-tests.dir/build.make:52: recipe for target 'C-api-tests' failed
make[3]: *** [C-api-tests] Error 1
CMakeFiles/Makefile2:1680: recipe for target 'tests/api/C/CMakeFiles/C-api-tests.dir/all' failed
make[2]: *** [tests/api/C/CMakeFiles/C-api-tests.dir/all] Error 2
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:151: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by msoos** [comment]
@delcypher  I tried to add 2 new messages to the repo that warn about the lit tool needing to be installed and the submodules. I think it's OK but maybe you could check? The diffs are:

c291d5f47890c38466ab30522b0acd79fcb15192
5ab33e3f717d7dec24230b9ae03affbc1e48f3a0

Thanks!

**Comment by msoos** [comment]
@mdimjasevic Something is odd there. Both on my machine and on TravisCI all the tests pass.Maybe you have an old STP version installed as well into a default path? Or some other weirdness? Try `rm -rf build` and then `mkdir build && cd build` and `cmake ..` and `make`. Maybe that will do the trick...

**Comment by mdimjasevic** [comment]
@msoos, this is with the 2.1.0 release. As I use Vagrant for this, there is no previous installation of STP or anything like that. Just to make sure this is what really happens, I re-executed all the steps from cloning STP to configuring the build process which goes like this:

```bash
...
mkdir build
cd build
cmake \
  -DENABLE_TESTING=ON \
  -DTEST_APIS=ON \
  -DTEST_C_API=ON \
  -DTEST_QUERY_FILES=ON \
  -DUSE_VALGRIND=ON \
  -DLIT_TOOL=/usr/lib/llvm-3.5/build/utils/lit/lit.py \
  -DENABLE_PYTHON_INTERFACE=ON \
  -DBUILD_SHARED_LIBS=ON \
  -DALSO_BUILD_STATIC_LIB=ON \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DENABLE_ASSERTIONS=ON \
  -DCMAKE_INSTALL_PREFIX=/usr \
  ../
make -j8 check
```

The result is the same as reported above.

That's the `amd64` architecture if that is of any help.

**Comment by delcypher** [comment]
Try running the built test executables manually to see why they are failing.

e.g.
```
 $ build_dir/tests/api/C/array-cvcl-02Tests
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from array_cvcl02
[ RUN      ] array_cvcl02.one
ASSERT( a[0x00000000] = 0x0000000B );
ASSERT( i = 0x00 );
[       OK ] array_cvcl02.one (1 ms)
[----------] 1 test from array_cvcl02 (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 1 test.
```

**Comment by mdimjasevic** [comment]
@delcypher, that's interesting. When I run the failing tests individually as you've suggested, they all pass. I don't have a clue what's going on.

**Comment by delcypher** [comment]
``lit`` simply runs the tests it finds in a directory. You should check what doing

```
$ lit -vs tests/api/C/
```

does when run from the root of the build directory.

Note that we use ``lit`` from PyPi and not from the LLVM source tree so that "might" be the source of your problems.

**Comment by mdimjasevic** [comment]
@delcypher:

```
vagrant@debian-jessie:~/stp-2.1.0/build$ /usr/lib/llvm-3.5/build/utils/lit/lit.py -vs tests/api/C
Testing Time: 0.57s
  Expected Passes    : 65
vagrant@debian-jessie:~/stp-2.1.0/build$ /usr/lib/llvm-3.5/build/utils/lit/lit.py --version
lit 0.4.0dev
```

**Comment by delcypher** [comment]
This suggests something is going wrong with the ``make check`` invocation. Try running

```
$ make C-api-tests
```

this will run the C API tests only

**Comment by mdimjasevic** [comment]
@delcypher, the result is the same, i.e. those 25 failures out of 65 tests.

**Comment by delcypher** [comment]
Try

```
$ make C-api-tests VERBOSE=1
```

this should show you the exact command line used to invoke ``lit`` which will hopefully let you debug what is going on.

**Comment by delcypher** [comment]
> @delcypher I tried to add 2 new messages to the repo that warn about the lit tool needing to be installed and the submodules. I think it's OK but maybe you could check? The diffs are:
>
> c291d5f
> 5ab33e3

@msoos Thanks. I've made a minor improvement in b7f0781b67a33c63c408a0d127949cf01ea0e03d

**Comment by mdimjasevic** [comment]
@delcypher, I managed to figure out where's the problem (or at least what it has to do with). It has to do with passing the `-DUSE_VALGRIND=ON` option to CMake. When built with it, the tests fail; when built without it, the `check` target builds successfully.

I don't know why that happens. Grepping GTest for "valgrind" I see they mention it in the code, but I didn't dig to see what exactly is happening.

With the `VERBOSE=1` option to `make` I haven't learned much so far. 

Have you ever tried to build the `check` target with Valgrind enabled?

**Comment by delcypher** [comment]
Oh I see. Running the tests with Valgrind has never worked (which is why that option is currently disabled). When I wrote the test infrastructure I added support for it but I never looked into why they were failing in much detail. I think part of it has to do with STP's abysmal C interface.

**Comment by mdimjasevic** [comment]
@delcypher, thanks for that! Maybe you could update this page accordingly: https://stp.github.io/testing/.

**Comment by mdimjasevic** [comment]
I have no further questions regarding this so I'm closing the issue.

**Comment by delcypher** [comment]
> @delcypher, thanks for that! Maybe you could update this page accordingly: https://stp.github.io/testing/.

[I've updated the documentation to note that using valgrind for the tests doesn't really work right now](https://github.com/stp/stp.github.io/commit/32ad90e7935eb60426b2f23c25aa8c704761f883)
