### ISSUE TITLE
Missing Wiki

### ISSUE THREAD

**Issue by domainexpert** [stp/stp#202]
The link to the wiki from the main project page links to the main project page itself. Actually, I desperately need the API documentation (where could I find it if not from the wiki?).

**Comment by msoos** [comment]
http://stp.github.io/ is all we have unfortunately. Please check the pyhton bindings' code or just use the python bindings -- it's quite clean and understandable. You are also very welcome to write an API guide. Would be great!

**Comment by delcypher** [comment]
@domainexpert 

There are some comments in 

https://github.com/stp/stp/blob/master/include/stp/c_interface.h

but the C API is awful. We have an open issue to write a new one from scratch ( #90 )

**Comment by msoos** [comment]
@domainexpert  actually, if you can take a look at the existing API and feel like you could do better, it'd be great if you could work on a new one. I'm closing this issue, please follow up on the thread at https://github.com/stp/stp/issues/90 or create a pull request with a new description against the docs here:  https://github.com/stp/stp.github.io Thanks in advance -- every little helps!

**Comment by domainexpert** [comment]
Thanks to everyone for helping.
