### ISSUE TITLE
Modulo inconsistent behavior

### ISSUE THREAD

**Issue by enzet** [stp/stp#208]
We use STP for path constraint solving in our dynamic analysis tool and faced a different behavior in modulo operation handling. Following CVC constraints

    x : BITVECTOR(32);
    y : BITVECTOR(32);
    z : BITVECTOR(32);
    ASSERT(z = BVMOD(32, x, y));
    ASSERT(z = 0hex00000005);
    QUERY(FALSE);

imply following error:

    Fatal Error: BVConstEvaluator:division by zero error
    stp: Error: BVConstEvaluator:division by zero error

But corresponding SMT-LIB 2 formulae with `bvsmod`:

    (declare-fun x () (_ BitVec 8))
    (declare-fun y () (_ BitVec 8))
    (assert (= #x05 (bvsmod x y)))
    (check-sat)

returns 

    ASSERT( x = 0x05 );
    ASSERT( y = 0x00 );
    sat

Also I know that the semantic interpretation is underspecified for `bvsmod` in case `y` is 0, but there `y` is symbolic variable. Is this answer expectable result of undefined behavior or is it a bug?

**Comment by msoos** [comment]
This is most probably a bug. Thanks for the report! Division by zero is a pain, but this case is almost certainly an issue with STP. As you said, `y` is symbolic, so it shouldn't try to shoot itself in the foot by assigning it to zero :)

**Comment by enzet** [comment]
Thank you for answer.

If it is interesting for you I've checked Z3 and CVC4 and found the same problem. On the same SMT-LIB 2 formulae Z3 returns expectable result

```lisp
sat
(model 
  (define-fun y () (_ BitVec 8)
    #x0c)
  (define-fun x () (_ BitVec 8)
    #x59)
)
```

but for `bvsmod` replaced with `bvsrem` I get

```lisp
sat
(model 
  (define-fun y () (_ BitVec 8)
    #x00)
  (define-fun x () (_ BitVec 8)
    #x05)
)
```

CVC4 also returns zero for `y`:

```lisp
sat
(model
(define-fun x () (_ BitVec 8) (_ bv16 8))
(define-fun y () (_ BitVec 8) (_ bv0 8))
)
```

I suppose the problem is more fundamental.

**Comment by TrevorHansen** [comment]
We've changed unsigned division by zero to equal 1 now, so both the CVC and SMTLIB2 formats will produce the same answer of x =5, y=0, now.

**Comment by msoos** [comment]
Thanks Trevor! This division by zero was a huge pain for a lot of users, I'm so glad you fixed it!
