### ISSUE TITLE
Multiple validity checkers

### ISSUE THREAD

**Issue by linade** [stp/stp#212]
Hi all,
I was trying to use stp c interface and really hope I can do something like this:

#include "stp/c_interface.h"
int main() {
  VC vc1 = vc_createValidityChecker();
  VC vc2 = vc_createValidityChecker();
  ... // do something with vc1
  ... // do something with vc2
  vc_Destory(vc1);
  vc_Destroy(vc2);
  return 0;
}

However, this gives me segmentation fault (even without anything in between). But if I change this to:

  VC vc1 = vc_createValidityChecker();
  ... // do something with vc1
  vc_Destory(vc1);
  VC vc2 = vc_createValidityChecker();
  ... // do something with vc2
  vc_Destroy(vc2);

This seems to work fine. In other words, I can't use multiple instances of stp at the same time. In my case, I want to do this because sometimes I can't finish a vc's job before initializing another vc. More specifically, each vc would be initialized, create different assertions and checkpoints, or issue queries at random stages of the project. They shouldn't interfere with each other.

Is it too much to ask? Is there a reason I shouldn't use stp this way? Of course I can store the jobs from different stages of the project and give them all at once to the solver. But it's less convenient and wouldn't be efficient. Thanks in advance.

**Comment by msoos** [comment]
This one is really embarrassing and I cannot fix it right now. STP keeps global state and cannot be instantiated multiple times in an executable. Yeah, this needs to be fixed. If you have time, you can take a look at the stpglobals.h and see if you can fix it. I didn't write this so I'm unfamiliar with the code. If you have time and can fix it, I'd be so grateful. Maybe a weeekend project? :) I'll merge your fixes I promise :)

**Comment by linade** [comment]
Thanks for the quick reply. It seems originally the globals were for parsers only, but later they are used every where. Most significantly the ASTNode class uses it, and ASTNode is everywhere. I couldn't find a quick fix this afternoon. Probably won't try it this weekend either. It would be faster to get a workaround from my side so.

**Comment by TrevorHansen** [comment]
All good as of 54d40c621cbadda291fd50edaccb4a5058534f72
