### ISSUE TITLE
Moving to LLVM 3.6

### ISSUE THREAD

**Issue by mdimjasevic** [stp/stp#213]
Dear STP authors,

As you might remember, I've been working on getting a Debian package for STP. [The package has been under review](https://ftp-master.debian.org/new/stp_2.1.1+dfsg-1.html) for 4 months now and I don't know when I'll hear back about the package.

In the meantime, a few changes happened, including STP 2.1.2 - LLVM versions 3.4 and 3.5 will not be available in the next Debian stable release, hence the current STP package version, which depends on LLVM 3.5, will not work.

Because of that, I would like to ask you to consider rebasing STP on LLVM 3.6. If you would do that, I would resubmit a new STP package to Debian right away. Your rebasing would hopefully trigger KLEE authors to upgrade as well.

An email thread in a Debian mailing list clarifying this change in Debian [is available](https://lists.debian.org/debian-mentors/2016/01/msg00546.html).

**Comment by msoos** [comment]
I'm sorry but have you tried compiling it with clang 3.6? What makes you think it doesn't compile? Please state the reasons. I am closing it in the meanwhile.

**Comment by delcypher** [comment]
> the current STP package version, which depends on LLVM 3.5, will not work.
@mdimjasevic  What? STP does not depend on LLVM. We have a dependency on ``lit`` (from the LLVM project) for testing but that is not a runtime dependency. Even as a build time dependency you should be getting this from PyPi and not from LLVM

**Comment by mdimjasevic** [comment]
Mea culpa.

I thought there would be problems as the LLVM API changes from one version to another.

@delcypher, you are right, LLVM is needed only for `lit`. As the STP package will eventually be built on the Debian project's server, in preparing build scripts I have to use the same kind of infrastructure, which means relying on LLVM packages available in the Debian archive only, and not in PyPi, the LLVM project's .deb repositories, or in any other sources. As running tests is an integral part of building a package, I needed LLVM here.

I just tried it myself and I can successfully build the package with LLVM 3.6, so all is good.
