### ISSUE TITLE
compiler warnings - potential bugs

### ISSUE THREAD

**Issue by mchalupa** [stp/stp#214]
Hi,

when compiling STP i get a lot of compiler warnings. Most of them are probably harmless, but I picked a few which could cause some troubles:

```
stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp:1231:44: warning: format '%d' expects argument of type 'int', but argument 4 has type 'size_t {aka long unsigned int}' [-Wformat=]
     sprintf(t, "%s[%d]", current.c_str(), i);
 
stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp:1480:44: warning: format '%d' expects argument of type 'int', but argument 4 has type 'size_t {aka long unsigned int}' [-Wformat=]
     sprintf(t, "%s[%d]", current.c_str(), i);
                                            ^
/home/marek/statica/symbiotic/stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp: In function 'bool checkProp(const stp::ASTNode&)':
/home/marek/statica/symbiotic/stp/tools/rewrite_rule_gen/rewrite_rule_gen.cpp:329:18: warning: 'value' may be used uninitialized in this function [-Wmaybe-uninitialized]
        << "[" << value << "]" << n;
```

Cheers,
Marek

**Comment by msoos** [comment]
Thanks! Rewrite rule gen is not being used at the moment and it should not be used by any regular user as it's only used for development. However, I encourage you to solve the above issues. Please clone the repository, fix the issues in your clone, then ask for the fixes to be merged through a pull request. Here is a short howto:

https://help.github.com/articles/using-pull-requests/

Thanks in advance and looking forward to your fixes!

Mate
