### ISSUE TITLE
 SMT-LIB 2.0: declare-const

### ISSUE THREAD

**Issue by amgrubb** [stp/stp#215]
I am getting an error whenever I declare a constant. For example:

=== File b.smt2 ===
(declare-const x (_ BitVec 64))
(declare-const y (_ BitVec 64))
(assert (= x y))
(check-sat)

=== Error ===
amgrubb@ubuntu:~/Documents/$ stp --SMTLIB2 b.smt2
syntax error: line 5
syntax error, unexpected STRING_TOK
  token: declare-const
Fatal Error: 
stp: Error: 

Is there a work around for constants?

Also, does STP implement the full SMT-LIB 2.0 standard? Are there any commands I shouldn't be using?

**Comment by msoos** [comment]
All of 2.0 relevant to bitvectors with arrays is supported AFAIK. The `declare-const` is *not* part of the 2.0 standard. Please see http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r12.09.09.pdf  It's only part of the 2.5 standard. However, if you could implement it, we'd be grateful. Please clone the repo, add it to the yacc language definition (`smt2.y`) and to the C++ code, and create a pull request!

Thanks a lot in advance,

Mate
