### ISSUE TITLE
Finding Multi-sulutions

### ISSUE THREAD

**Issue by songling** [stp/stp#216]
@msoos 
I am using STP to solve some problems and I'd like to figure out the number of solutions. To this end, I let STP output the CNF file, and then use Cryptominisat to find up to M solutions. If M is large enough, I can get all of the solutions. For some problems, I found that the number of solutions Cryptominisat returns is larger than the number of solutions the problem actually has.

For example, the problem in the website
 https://github.com/songling/cp2block/blob/master/cp2block.stp
has only one solution, but Cryptominisat returns two solutions.

Specifically, 25 words A00~A44 should satisfy the constraint that the total Hamming weight is 6. Since I've already assigned 6 bits to be 1,  the problem has only one solution.

I find the solution as follows.

$ stp --output-CNF --exit-after-CNF cp2block.stp
$ cryptominisat4 --maxsol=10000 output_0.cnf

Then cryptominisat returns 2 solutions.

(CryptoMiniSat version 4.5.3, STP version number 2.1.2)

I don't know why this happens. I used to use an older version of STP and never encounter this kind of issues.

**Comment by msoos** [comment]
Unfortunately, it's not correct to output the CNF and then try to solve that more than once. The outputted CNF may not encode the whole SMT formua. STP optimizes by not encoding everything until it's needed. Eventually, the CNF will contain all the SMT formula if needed, but that usually requires multiple iterations. As I described to you earlier, you must use either the SMT Lib interface or you must use the python bindings provided. I wish you luck! Please post back here in case you have any issues or if you had success :) Thanks!

Mate
