### ISSUE TITLE
Build fails with linking Cryptominisat library located in non-default directory

### ISSUE THREAD

**Issue by MartinNowack** [stp/stp#221]
The library gets found, still compilation fails:
```
... snip ...
-- Found CryptoMiniSat4 and C++11, allowing --cryptominisat4 option
-- CryptoMiniSat4 dynamic lib: libcryptominisat4
-- CryptoMiniSat4 static lib:  libcryptominisat4.a
-- CryptoMiniSat4 static lib deps: m4ri
-- Finding static minisat libs...
-- OK, found Minisat library under /tmp/ubuntu/local/lib/libminisat.a and Minisat include dirs under /tmp/ubuntu/local/include
-- Final CXX flags -std=c++11 -fno-omit-frame-pointer -Wall -Wextra -pedantic -Wunused -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wformat-nonliteral -Winit-self -Wunreachable-code
CMake Warning at CMakeLists.txt:432 (message):
  Testing is disabled
... snip ...
```
And here it fails:
```
make[2]: Entering directory `/tmp/ubuntu/stp/build'
Linking CXX executable ../../stp
cd /tmp/ubuntu/stp/build/tools/stp && /usr/bin/cmake -E cmake_link_script CMakeFiles/stp.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++11 -fno-omit-frame-pointer -Wall -Wextra -pedantic -Wunused -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wformat-nonliteral -Winit-self -Wunreachable-code -O2 -g   -pthread   CMakeFiles/stp.dir/main.cpp.o CMakeFiles/stp.dir/main_common.cpp.o CMakeFiles/stp.dir/STPProgramGlobals.cpp.o  -o ../../stp-2.1.2 -rdynamic ../../lib/libstp.a -Wl,-Bstatic -lboost_program_options -lcryptominisat4 -Wl,-Bdynamic -lm4ri /tmp/ubuntu/local/lib/libminisat.a
/usr/bin/ld: cannot find -lcryptominisat4
/usr/bin/ld: cannot find -lm4ri
collect2: error: ld returned 1 exit status
```

Interestingly, `minisat` is found correctly.
I guess the path to cryptominisat needs to be added as well.

**Comment by msoos** [comment]
Actually, lately I have changed things around for the SMT competition. I will update README this week so things work well. All in all, for STP to be compiled statically and for STP to create a static library, you need to compile cryptominisat statically. It will then work. I'll work a bit on this so it's all clear. But as I mentioned before, KLEE can always be built (just needs static CMS+STP), it's part of our continuous integration system. I get an email for every STP push I do that doesn't compile with KLEE. No kidding. It's built on a vanilly Ubuntu 14.04, freshly spinned up, with absolutely nothing pre-installed or any past compilation data or anything else on it, for that matter. So things do actually work. I'll post here and in the README a short summary of how.

**Comment by MartinNowack** [comment]
@msoos Thanks, a lot for the info. I'll try to compile it statically.
