### ISSUE TITLE
Changing default solver to Cryptominisat

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#222]
Replacing Minisat with CMS as our default SAT solver seems sensible to me. 

In the past I've been wary because the startup time of CMS was slower, so that on easy problems (i.e. when sat solving would finish in less than a couple of milliseconds), Minisat would outperform. CMS has fast startup now, so I think the issue has gone away.

Does anyone else have a preference?

**Comment by msoos** [comment]
Could be nice :) I'd happy for that of course, I need to release the new CryptoMiniSat though. Let me do that this week and then I'm fine with switching. What do the others think? @delcypher @rgov ? I'd be happy to hear what you have to say!

**Comment by rgov** [comment]
Both STP and MiniSat are MIT-licensed, while CryptoMiniSat is an optional LGPL3-licensed dependency. Would that remain the same? Would users be able to run a completely MIT-licensed solver?

**Comment by msoos** [comment]
As a side-note, the constant bit propagation code is not MIT. It needs to be removed.

Since CryptoMiniSat is LGPLv2, and STP only uses CMS through its header (which is MIT), STP would stay MIT. It would use a library that is LGPLv2 though :S Note that glibc is LGPL too, so most deployments would not be affected, I think. There is a lot of LGPLv2 code on most OS x systems, too, I believe, and they get auto-linked pretty generally to a lot of stuff -- but probably @rgov  has a much better understanding of the Mac OS sphere.

But I fully understand your concerns. I'm just not sure that given it's LGPLv2 if it would affect too many things. Does anyone else have industry some experience where LGPLv2 was an issue? I'm genuinely curious.

**Comment by rgov** [comment]
>  This version of the GNU Lesser General Public License incorporates the terms and conditions of **version 3** of the GNU General Public License, supplemented by the additional permissions listed below.

Emphasis mine. I've had trouble getting approval to use LGPLv3 in commercial applications in the past. If it were LGPLv2 it would at least be easier.

**Comment by msoos** [comment]
Wow, where is that? :D That is a mistake. I definitely want only LGPLv2. I know LGPLv3 is a mess. Thanks for finding that one! I need to fix it :)

**Comment by TrevorHansen** [comment]
Thank everyone.

Changing to CMS being the default SAT solver requires a single line of code to be changed. Otherwise, the code is the same. Minisat can still be set as the SAT solver, by using the --minisat command-line flag (or similar) to STP. It sounds like people don't have a technical preference for keeping Minisat the default solver?

I'm the author of the constant bit propagation code, I consider it MIT licensed. So I will put new headers on it, sometime.

The bit-vector library we use is LGPL, and tightly integrated with STP (i.e. you can't statically link it into the binary). I don't know about licences. Can someone give me a sense of what trouble this might cause?

Thanks.

**Comment by TrevorHansen** [comment]
Ooops. I meant to say that you can't dynamically link the bit-vector library in..

**Comment by msoos** [comment]
@TrevorHansen  I was talking about constantbv.cpp:

```
/*****************************************************************************/
/*  AUTHOR:                                                                  */
/*****************************************************************************/
/*                                                                           */
/*    Steffen Beyer                                                          */
/*    mailto:sb@engelschall.com                                              */
/*    http://www.engelschall.com/u/sb/download/                              */
/*                                                                           */
/*****************************************************************************/
/*  COPYRIGHT:                                                               */
/*****************************************************************************/
/*                                                                           */
/*    Copyright (c) 1995 - 2004 by Steffen Beyer.                            */
/*    All rights reserved.                                                   */
/*                                                                           */
/*****************************************************************************/
/*  LICENSE:                                                                 */
/*****************************************************************************/
/*                                                                           */
/*    This library is free software; you can redistribute it and/or          */
/*    modify it under the terms of the GNU Library General Public            */
/*    License as published by the Free Software Foundation; either           */
/*    version 2 of the License, or (at your option) any later version.       */
```

**Comment by msoos** [comment]
Should we leave things as it is for the moment? There seems to be no consensus. MIT vs LGPLv2 may be an issue. Let me leave this as it is. Maybe next version we move to the CryptoMiniSat!

**Comment by TrevorHansen** [comment]
I'm good to make the change. Based on the discussion, it seems best to make Cryptominisat the default if Cryptominisat has been enabled, otherwise use Minisat as the default. Unless anyone objects, I'll make the change in the next week.

**Comment by msoos** [comment]
Okay, that sounds really reasonable actually! I'll release after you make
the change :) Is that OK everyone? @rgov @delcypher?  ?

**Comment by TrevorHansen** [comment]
ok, done in 41b9d44b6a4550fcc1dd7462b138c01d8db03d31
