### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by ccadar** [stp/stp#225]
Hi, the latest STP release is quite old, from 28 October 2015, and I would like to use a recent STP release for KLEE (in particular one that incorporates the fix for the division by zero issues I reported in #206) .  Would that be possible?  Thanks!

**Comment by msoos** [comment]
Good point! Since we got 2nd place this year at SMT Comp, we should do a new release. I'll be doing that for both CMS and STP this week. I have a presentation to give about CMS next Monday so I need to get a release out of the door anyway :)

PS: Link to results page http://smtcomp.sourceforge.net/2016/results-QF_BV.shtml?v=1467112059 Only Boolector got more "Correctly Solved Score"

**Comment by ccadar** [comment]
Congrats for the SMT-COMP results!!  And thanks for preparing the upcoming release.

**Comment by msoos** [comment]
Hi! I released CryptoMiniSat 5.0. I am now preparing to release STP. Please let me know if the current system is OK for your needs. It should work, I believe, TravisCI is just about to pass. Please take a peek. I will release this week if all is fine.

Thanks!

Mate

**Comment by msoos** [comment]
Hi All,

I drafted a new release for the point where Trevor started hacking adding SMT-LIB 2.5 and removing libabc from the source -- these are big changes (and are **very** welcome) but I want to release a stable release. I have drafted a new release here:

https://github.com/stp/stp/releases/tag/stp-2.2.0

Please take a look, edit as appropriate, etc. @delcypher  @TrevorHansen @rgov 

Looking forward to your feedback and making the pre-release into a final release :)

Mate

**Comment by ccadar** [comment]
Hi @msoos, many thanks for your work on this!  I am traveling and don't have time to test this right now, but I'll try to take a look later next week.

**Comment by TrevorHansen** [comment]
yes @msoos, ok with me.

**Comment by msoos** [comment]
OK, I've released it. Only change I had to make was to fix the version to 2.2.0 in the CMakeLists.txt.

The release contains a 64b linux static executable, which is nice to have. The only itch I have is that I haven't fixed the Windows compile on AppVeyor and so I cannot attach a Windows executable. I want to do that soon, though.

Please write a feedback here once you can test it. It will need to be a new release if there is anything wrong with it, but it should be fine I hope. Looking forward to your feedback! Closing, but you can always comment and I get it as an email :)

**Comment by ccadar** [comment]
Thanks, @msoos!  I'll let you know if we run into any issues with KLEE.
