### ISSUE TITLE
Using C++11

### ISSUE THREAD

**Issue by msoos** [stp/stp#226]
Hi All,

Would it be OK to use C++11 in STP? It would make compilation a lot easier (types and datastructures that we now hack around/test for availability at build config time). All meaningful C++ compilers now have C++11 support. I only plan to utilise a small subset, such as the new for loop construct, cstdint and value-initialised class members (e.g. `int a = 2;` in a struct). Would this be OK?

**Comment by rgov** [comment]
No objection from me.

**Comment by delcypher** [comment]
SGTM

**Comment by hellovijay** [comment]
Fine by me.

-Vijay Ganesh.

**Comment by TrevorHansen** [comment]
Seems unobjectionable to me to!
