### ISSUE TITLE
clang testing in travisCI

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#227]
Does anyone know what's stopping us running clang on travisCI?

**Comment by msoos** [comment]
Nothing at all, except TravisCI has an older clang in the current config (12.04). Moving to the newer TraviCI (14.04) could solve it, or, I could copy-paste what I have in CryptoMiniSat which install clang to 12.04. I'll look into this in the weekend. Note that the KLEE test for TravisCI already installs clang so we could use that to :)

**Comment by TrevorHansen** [comment]
hi @msoos, I'd like to do a static clang build on travis ci. I've got it going partway, but cmake seems to be putting in dynamic linker flags (even though I've asked for static). See:

https://travis-ci.org/stp/stp/jobs/159495750

Do you see what's wrong?

**Comment by msoos** [comment]
Sorry, I am currently very busy in many ways, and will not be able to participate in STP or CryptoMiniSat for a few months. I should be back afterwards :) Good luck and sorry again!

**Comment by TrevorHansen** [comment]
On travis CI, it'd be good to get a static build, with cryptominsat that we can test with the query files.

I've started working on it, but the travisCI website seems broken, I can see the log files on it. I'll fix the current build and continue on when it's working again.

**Comment by TrevorHansen** [comment]
The TravisCI log files are showing up again.  The static build is succeeding, but making a dynamically linked executable.
Here's the log:
https://travis-ci.org/stp/stp/jobs/226275551

 Can you see why this is @msoos?

**Comment by msoos** [comment]
So, I'm worked a LOT on this. It turns out the cryptominisat also cannot build statically with clang. This is really bad and I'm working through that. Note that that does not affect STP, as STP fails to build with clang even without CMS (only MiniSat).

**Comment by msoos** [comment]
OK, I got it nailed down. Final linker command:

$ /usr/bin/clang++   -std=c++11  -pthread -Wall -Wextra -Wunused -pedantic -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wheader-guard -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -fPIC -O2 -g     -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -static  CMakeFiles/stp.dir/main.cpp.o CMakeFiles/stp.dir/main_common.cpp.o CMakeFiles/stp.dir/STPProgramGlobals.cpp.o  -o ../../stp-2.1.2 -rdynamic ../../lib/libstp.a -lboost_program_options /usr/local/lib/libminisat.a /usr/local/lib/libcryptominisat5.a /usr/local/lib/libm4ri.a 

If I remove the "-rdynamic" from there, it links and produces a static executable. I'll fix this soon :)

**Comment by msoos** [comment]
Done. There are some other minor issues around, but this is fully fixed. Also, I nailed the tests in static compilation, so that works too now.
