### ISSUE TITLE
cppinterface missing dependency on ASTKind.h

### ISSUE THREAD

**Issue by dtzWill** [stp/stp#235]
This occasionally causes the following build error for me (when building in parallel):

``` console
In file included from /tmp/nix-build-stp-2016.09.25.drv-0/stp-ea62844/lib/Interface/cpp_interface.cpp:25:
In file included from /tmp/nix-build-stp-2016.09.25.drv-0/stp-ea62844/include/stp/cpp_interface.h:28:
In file included from /tmp/nix-build-stp-2016.09.25.drv-0/stp-ea62844/include/stp/AST/AST.h:28:
/tmp/nix-build-stp-2016.09.25.drv-0/stp-ea62844/include/stp/AST/UsefulDefs.h:40:10: fatal error: 'stp/AST/ASTKind.h' file not found
#include "stp/AST/ASTKind.h"
```

Looking at [this CMakeLists.txt file](https://github.com/stp/stp/blob/master/lib/Interface/CMakeLists.txt#L31), it seems there's a missing dependency on `ASTKind.h` that would be resolved by adding the following:

``` cmake
add_dependencies(cppinterface ASTKind_header)
```

(similar to the existing dependency on the header from `cinterface`).

If you agree with this change please apply this fix upstream :).

Thanks!

**Comment by TrevorHansen** [comment]
Thanks @dtzWill I've seen this too, but thought I was the only one who was getting it! I don't have much experience with the build system, but what you propose fixes it for me, too. thanks again, trev.
