### ISSUE TITLE
Documentation dead links

### ISSUE THREAD

**Issue by colinmorris** [stp/stp#236]
The link to the longer description of the SMT language [on this page](http://stp.github.io/smt-input-language/) is a 404: [http://www.grammatech.com/resource/smt/SMTLIBTutorial.pdf](http://www.grammatech.com/resource/smt/SMTLIBTutorial.pdf)

Also, the [documentation link](https://github.com/stp/stp/wiki) in the README just takes me to the main github project page again. Seems like the wiki doesn't exist?

**Comment by msoos** [comment]
Sorry, currently, I have no time to fix this :S Maybe in a couple of months. I know it's slow, but I am very busy right now :(

**Comment by msoos** [comment]
Thanks! Both have been fixed.
