### ISSUE TITLE
Fix AppVeyor

### ISSUE THREAD

**Issue by msoos** [stp/stp#247]
Apparently it's not that difficult.

Pull request discussion here: https://github.com/stp/stp/pull/246

Copy from thread:

---------------
@fkutzner wrote: 

Building it isn't entirely untethered from POSIX yet:

cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=<InstallPath> -DCMAKE_PREFIX_PATH=<PathToMinisatAndZlibInstallation>;<PathOfCygwinRootDir> -DMINISAT_LIBRARY=<pathOfMinisat.libFile> <PathOfSTPSource>
cmake --build . --config Debug
cmake --build . --config Debug --target install
I'm using Cygwin's flex and bison, but run the build process from the Git bash (a gcc-less MinGW environment which also doesn't contain MinGW C/C++ header files). CMake generates a Visual Studio project and uses MSBuild to build STP, so it is possible to use the Visual Studio IDE - it's no fun, though, since MSVC emits a tremendous amount of warnings, slowing down the UI. Boost is missing from my compilation mainly because I haven't gotten around to add it yet. If you'd like, I could write the readme entry (including build instructions for zlib and boost), probably by next week.

I'm currently working on a few things:

reducing the amount of warnings. Most of them don't seem to be very helpful, e.g. the thousands of lines about struct paddings and removing unused C++ library inline functions. These make building STP with MSVC take ages
getting the automated tests to run. I'm halfway there, but there are a lot of small issues like getting the tests to use the non-Cygwin Python installation and needing to conjure up a "not" program (I did some manual testing for the PR, though, and ran the automated tests on macOS to make sure STP still works with other toolchains.)
finding minisat in the CMAKE_PREFIX_PATH
enabling shared library builds
The last bit is tricky with MSVC, as we would need to explicitly mark the symbols we whish to be exported. Adding them for the C++ interface without sprinkling export tags all over the code seems pretty cumbersome. I'm looking into ways to make a Unix-style shared library with all symbols exported. What do you think? It would be minimally intrusive for the STP code, but complicate the build process a bit since the symbols would need to be read from the object files and gathered in a definition file. Should I create an issue for this as soon as I know this is viable?

Building the static version of CryptoMiniSat like above was a breeze! I haven't installed m4ri yet, though, which prevented me from building STP with CryptoMiniSat. I'll look into what went wrong next weekend. The dynamic (default) build didn't work, since a static one is forced for MSVC and no DLL is generated against which the executable can be linked. MSVC only generated a warning about clean_to_int in solverconf.h:53. not always returning a value. However, I couldn't build it in the IDE, since xxd.exe could not be found. It worked fine from the Git bash, though.

---------

 @msoos
     Member
msoos commented 4 minutes from now
Wow, that's some really good work, thanks! I'll get it to compile under AppVeyor and then I'll see the warnings too and I can fix some/most as well. I did that for CryptoMiniSat and it seems like I did OK. The symbol export thing is a valid concern. We should actively try to fix it for STP. I fixed it for CryptoMiniSat and it wasn't that bad at all. Essentially the same thing (with some #define's) can be used to do both POSIX and WIN-style symbol export fixing.

As for CryptoMiniSat:

I need to fix the dynamic building. Sorry, I was concentrating on releasing an executable.
xxde.exe works when vim is installed and cmake is used to build. I guess/hope that worked as you could build it (only statically, though, but still)
So, thanks again! I'll get to this a bit later this week!

**Comment by fkutzner** [comment]
(Moved this comment from the discussion in #246)

I've looked through the AppVeyor file - does AppVeyor bring perl, flex and bison? I use these tools from my Cygwin installation. Also, a Python installation outside of Cygwin is needed. I've got the automated tests up and running (see https://github.com/fkutzner/stp/tree/win64dll), and needed to adjust the CMake parameters by passing -DPYTHON_EXECUTABLE, -DPYTHON_LIB_INSTALL_DIR (on Windows, the Python installation directory) and -DLIT_TOOL (path to lit-script.py, not the lit binary). Furthermore, to run the tests I needed to install an implementation of _not_ in a %PATH% directory.

Having a Windows box at hand, I could try to have a stab at setting up AppVeyor for STP, however it would take some time since I don't have experience with AppVeyor yet.

Thanks for putting time into this! :)

**Comment by msoos** [comment]
Hi! I'm glad you managed to get all of those running :) It'd be nice if you could write down what were the steps, though! I don't have a Windows box, so I need AppVeyor and it's slower this way. The thing is, I am not being paid to do this, and I don't have windows, so I'd need to buy it and that's not cheap :S So just a set of steps would be really nice. Like, cygwin, what you need installed inside cygwin, etc. How you configured it, how you compiled it, including MiniSat. You say you managed to compile MiniSat, but how? Also, where do you install it? How do you give the installation path to STP? Thanks a ton in advance!

**Comment by msoos** [comment]
Well, I guess MiniSat is fixed now:

https://ci.appveyor.com/project/msoos/minisat

But I actually had to change the code. Weird, I thought minisat would just run out of the box. Anyway, now on to STP :)

**Comment by fkutzner** [comment]
Sorry, I did not mean to be so terse - I'll write a batch script with all the details to make up for it!

**Comment by fkutzner** [comment]
Here's the Windows batch script: https://gist.github.com/fkutzner/d990ca73ac3e813717529059518db9f3

The script installs Cygwin locally (including flex, bison and perl), fetches the zlib,minisat,stp sources and builds them. Unfortunately, it isn't completely automatic yet: the Cygwin installer (https://cygwin.com/setup-x86.exe) and embeddable Python (https://www.python.org/ftp/python/3.6.1/python-3.6.1-embed-amd64.zip) need to be downloaded (see the script's header where to place rsp. extract them).

I hope I haven't overlooked any dependencies.

**Comment by msoos** [comment]
Wow, it's starting to compile! Weird, unexpected and great! The log is MASSSSSIVE though :) I have a feeling I'll be working through that most of today ;) Thanks for your gist, it *really* helped. I owe you a beer!

**Comment by msoos** [comment]
A few warnings to fix :)

```
[00:03:02]     68701 Warning(s)
[00:03:02]     2 Error(s)
```

The only error is zlib, which should easy to fix:

```
[00:03:02]          C:\projects\stp\minisat\myinstall\include\minisat/utils/ParseUtils.h(27): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory [C:\projects\stp\build\lib\Sat\sat.vcxproj]
[00:03:02]          C:\projects\stp\minisat\myinstall\include\minisat/utils/ParseUtils.h(27): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory [C:\projects\stp\build\lib\Sat\sat.vcxproj]
```

So, good progress, but those 60k warnings need to go :O Thanks again!

**Comment by fkutzner** [comment]
Being one of the few MSVC users, I think I owe you a whole case of beer :D Thanks for setting this up! I've been playing around with the CI system, and added a native Python installation via CMake parameters (see last commits on https://github.com/fkutzner/stp/tree/win64dll_appveyor) - there's trouble finding zlib.h, but compilation is well underway. I've put the zlib install directory in STP's CMAKE_PREFIX_PATH, so I'm a bit puzzled why zlib.h can't be found...

I've added the "/W3" (production quality warnings) flag in my branch, it helped tone down MSVC a bit :)

**Comment by msoos** [comment]
Build succeeded :)

https://ci.appveyor.com/project/msoos/stp/history

Thanks! I'll look through your commits, see what I can use :)

**Comment by msoos** [comment]
Hey! So I've made a lot of progress on the visibility/hidden issue. I just pushed, if you pull, normal visibility (as enforced by VC normally) should _almost_ work. Can you take a peek if you can fix the remaining issues? Some are caused by flex/bison-generated files and some from some vtable-based issue. I'm a bit confused about the Windows flags you put in, but I hope you can remove the one that makes everything visible, so the work I did with DLL_PUBLIC ( __declspec(dllexport) ) will work? Can you take a peek?

The other thing that bothers me endlessly is the
```
function not inlined
```
warnings in the build for Windows. Do you have any idea how to fix them? Could you take a shot at it? Thanks a lot in advance!

**Comment by fkutzner** [comment]
I'm currently out of town and didn't bring my Windows laptop, but I'll be back later this week and will try to solve these issues. Thanks for putting in the DLL_PUBLIC markers, with these I think I can remove the "export everything" flag.

**Comment by msoos** [comment]
No worries, thanks a lot in advance for taking a peek! Nice travels!

**Comment by msoos** [comment]
Note: currently it's broken due to the fixing of the linkage stuff. It's trivial to fix it, by commenting out what DLL_PUBLIC does when in MSVC mode, but it works for Linux (which is a good sign) and it's pretty easy to fix, so I'll just leave it as broken and come back to it in a few days. Just don't worry in case you see it broken, it's not _that_ broken :) Also, I fixed the million-warnings issue, they are a lot more manageable now!

**Comment by fkutzner** [comment]
Thanks, compiling is much, much nicer now :) I've fixed the linkage issue in https://github.com/fkutzner/stp/tree/dllfixes and will resume work there, making a pull request as soon as DLL building works nicely.

**Comment by msoos** [comment]
Thanks, I had a look, I really liked it so I imported it, along with clearly stating it's your work :)

**Comment by fkutzner** [comment]
Ok :) I'm still working on that branch, though. I'm making some progress, currently dealing with the symbols in auto-generated parser files.

**Comment by fkutzner** [comment]
I've just pushed another commit, but please wait until I make a pull request before importing this. There are still errors and I will rewrite things.

**Comment by msoos** [comment]
Cool, I won't be merging rematurely :)

**Comment by msoos** [comment]
Todo:
* DLL (no idea :D )
* tests (should work, but apparently needs "not" installed)
* boost (works, needs uncommenting but something breaks in the end)

**Comment by msoos** [comment]
Currently, the build is passing: https://ci.appveyor.com/project/msoos/stp

What is the status with the DLL, tests and python? Currently, it's built with STATICCOMPILE which is the reason why python is not turned on.

Testing can work with both static and dynamic compile now. We have a "make check". I kinda don't like it, because it doesn't work with "ctest", maybe I could fix that and ctest would work under Windows?

Once all above is working, we'll need to enable boost, it's really useful and makes a much better executable.

**Comment by fkutzner** [comment]
I've just checked it out - running the python tests doesn't work right now with a dynamic library MSVC build because the path in library_path.py is generated as ` .../lib/$(Configuration)/stp.dll` (with `$(Configuration)` not being substituted). I'll try to come up with a solution that works both on Unix and Windows.

I've been using `make check`, but would gladly use CTest instead. The less MSBuild verbosity ends up on the screen, the better :) CTest runs fine on Windows and is configuration-aware (e.g. `ctest -C Debug`).

**Comment by msoos** [comment]
Wow, thanks! If you can fix it on AppVeyor, I can fix the Linux part, I promise :) Make a pull request to make it work on Windows, and I'll do the rest :)

**Comment by fkutzner** [comment]
Ok :) Currently, I'm working https://github.com/fkutzner/stp/commits/win64tests. Yesterday, I've reverted the python binding build scripts to the generator-expression-based approach to see what went wrong on Linux, but right now it seems to work fine, at least on Travis. Did it break testing on Linux on your local machine?

I hoped that enabling the tests on AppVeyor would only involve throwing in a _not_ program and switching the tests on. To see if _not_ is already present, I just did the latter, and... the C-api-tests fail :( The output is https://ci.appveyor.com/project/fkutzner/stp/build/1.0.31, could you have a look? Curiously, the tests pass on my machine. I've attempted to reproduce the problem by converting the AppVeyor file into a batch script* and running it locally, but observed no test failures. In fact, there's some good news: the whole `check` target passes on my machine when executed in release mode. I probably mistook a very slow rebug-mode execution of STP for a freeze.

*https://gist.github.com/fkutzner/4d574bbf3433965e1cb6bcbdac2e3c14

**Comment by msoos** [comment]
Wow, great work, can you please add a merge request?  I have been working hard to understand CryptoMiniSat under Windows and it's really making progress so if ALL that isn't working is the c-api-tests, then you are making HUGE progress, so I'd love to see it and have a shot at fixing the remaining bit :) Please add a merge request, awesome work!!!

**Comment by fkutzner** [comment]
Unfortunately, the other test suites have failures, too. The aforementioned AppVeyor log was for a build after which only the C API tests ran. The current one, https://ci.appveyor.com/project/fkutzner/stp/build/1.0.35 (testing 84ca6ee), executes the whole `check` target. Currently, the AppVeyor build uses the _not_ utility of LLVM. Would this be okay for a merge? If so, I could open a pull request for my current branch.

**Comment by msoos** [comment]
Sure go ahead please! :) Thanks a ton!

**Comment by msoos** [comment]
Sorry, but I had to fix the Linux build. I hope it doesn't break the Windows one. This $<CONFIG> is a massive pain, I'm really-really tired of it. I have cmake 3.0.2, part of Debian Jessie, and it's broken there -- the directory doesn't get created so configuration fails because "[blah]/RelWithDebinfo/file" cannot be written, because of  "[blah]/RelWithDebinfo/" was never created, hence "file()" things with "[blah]/$<CONFIG>/file" all fail. I have wasted about 2 days on this, and it's a shame cmake is so crappy. I don't think we are using it wrongly, it's just wrong. I don't want to force users to use a system that's newer than Jessie... Jessie is pretty new, no?

**Comment by fkutzner** [comment]
Ouch, that's unfortunate - but I agree, STP should be buildable on Jessie, it's not so old. There's a newer version of CMake in the backports, but it would be nicer if everything just worked out on the default system. STP still builds on Windows. The python interface tests are broken, however:

```
Project "C:\projects\stp.build\check.vcxproj" (1) is building "C:\projects\stp.build\tests\api\python\python-interface-tests.vcxproj" (63) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\python-interface-tests\".
  Creating directory "x64\Release\python-interface-tests\python-i.1EC45E1C.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\python-interface-tests\python-i.1EC45E1C.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/projects/stp/tests/api/python/CMakeLists.txt
  CMake does not need to re-run because C:/projects/stp.build/tests/api/python/CMakeFiles/generate.stamp is up-to-date.
  Running python-interface-tests
  Traceback (most recent call last):
    File "C:/projects/stp.build/tests/api/python/tests.py", line 32, in <module>
      from stp import stp, Solver
    File "C:/projects/stp.build/bindings/python/stp\stp.py", line 52, in <module>
      raise Exception('Unable to locate the libstp shared object')
  Exception: Unable to locate the libstp shared object
```

I think the easiest workaround would be to have MSBuild place the binaries in a fixed place within the build directory, just as `make` does. That would go against VC++ conventions and might make using STP with other VC++ projects somewhat less comfortable, but IMO it's a viable solution until more recent CMake versions have made their way into mainstream Linux distributions. I'll try to see how this approach works out, probably within the week.

**Comment by msoos** [comment]
I just fixed to use CTest. This should allow us to run the test suite on Windows. I'll check it tomorrow, fingers crossed! :)

**Comment by msoos** [comment]
Note that tests now run in AppVeyor, but there is a Structure Exception Handler exit. I'm opening a new issue for that. I consider this one fixed, as the binary is installed and run.
