### ISSUE TITLE
Newest build broken because of missing import Util/constants.h

### ISSUE THREAD

**Issue by Robbepop** [stp/stp#248]
Building STP is currently broken for me compiling with GCC 6.3 with the following error:

```
In file included from stp/lib/Util/GitSHA1.cpp:26:0:
stp/include/stp/Util/GitSHA1.h:25:28: fatal error: Util/constants.h: No such file or directory
 #include "Util/constants.h"
                            ^
compilation terminated.
```

I tried to fix this by removing the missing include from the many files that include it but I think this file is required since recent changes but not yet added to the repo or in the wrong place.

**Comment by msoos** [comment]
Thanks for spotting this! I hope this commit fixes it :)
