### ISSUE TITLE
QF_UFBV or QF_AUFBV cause parsing errors

### ISSUE THREAD

**Issue by the-kiel** [stp/stp#263]
Hi, 

I just realised that when I tried to parse a smt2-file using QF_UFBV (see attached), this causes two errors: 

` ~/SMT/stp/build/stp --SMTLIB2 btfnt/btfnt_atlas_out.smt2 
(error "syntax error: line 1 Wrong input logic  token: QF_UFBV")
(error "syntax error: line 41 syntax error, unexpected LPAREN_TOK, expecting RPAREN_TOK  token: (")`

Now if I change QF_UFBV to QF_AUFBV, the first error disappears, but the second one remains. 
It seems to occur when functions are used where the parameter is a bitvector. 

Other solves (I tried boolector and yices) can read the file. 
Is this a known issue? 

Best, 
Thorsten

[btfnt_atlas_out.smt2.zip](https://github.com/stp/stp/files/1124694/btfnt_atlas_out.smt2.zip)

**Comment by TrevorHansen** [comment]
Hi Thorsten,

STP currently recognises QF_BV, QF_ABV, and QF_AUFBV as valid logics. Anything else will give a parse error.

However, STP is a solver for Bitvectors and arrays (without extensionality). STP doesn't handle uninterpreted functions (UF).

So QF_UFBV isn't recognised by STP as a valid logic.

If you change the logic to QF_AUFB, which is recognised. Then STP fails when it reaches the first definition of a UF. I plan on implementing UF in the future, until then, you'll need to use solvers like Boolector, Yices, and Z3 which handle UF.

Trev.
