### ISSUE TITLE
Unsigned char miscompilation of ABC on ARM

### ISSUE THREAD

**Issue by smcc** [stp/stp#264]
Earlier this week I experimented with a version of STP compiled for ARM/Linux, as part of testing and improving the ARM-architecture support in our FuzzBALL binary symbolic execution system. It seems this platform hasn't been tested much, since I found a problem that seems like it would affect many queries.

If you are familiar with the C language spec, you might recall that unlike the situation with larger integers, "char", "signed char", and "unsigned char" are considered to be three separate types. "char" has the same range and representation as either "signed char" or "unsigned char", but which is implementation-dependent. If you had asked me up until recently, I would have guessed that all modern platforms had "char" equivalent to "signed char", but surprisingly to me it turns out that most ARM compilers, including GCC, make "char" a synonym for "unsigned char". Apparently this arose because early versions of ARM did not have a convenient instruction for loading a byte and sign-extending it into a word register.

This turns out to be a problem for some of the old ABC code that's included with STP. The function `Cnf_ReadMsops` in `lib/extlib-abc/aig/cnf/cnfData.c` decompresses a table stored as a long string into linked data structures, and it uses char arrays in which "-1" is used as a sentinel value. However on platforms where char is unsigned, the condition `pMemory[k] == -1` can never be true, because the -1 stored into the array earlier is converted into 255 which is as an int is different from -1. Amusingly, the recent GCC version I was testing with (the latest from Arch Linux, 7.1.1 IIRC) realizes under -O2 that because this condition can never hold, the loop it's in will run forever; since there is no way to avoid executing the loop, it "optimizes" the whole function into a one-instruction infinite loop. (This made it easy to see there was a problem with the function but harder to find where in the function it was. There's a helpful warning that is only printed under -Wextra.)

Based on a comparison with the upstream ABC code I did later, we can consider this an instance of the known problem of using an old version of ABC (issue #159), since the problem was fixed in the upstream ABC version sometime before the 2012 start of their current Mercurial repo.

There are a few choices about how to change this in the code. The one that seems most elegant to me is to make the relevant data structure have type "signed char"; IMO that's obviously the type you need if you want to store -1. This change can be seen here:

https://github.com/bitblaze-fuzzball/stp/commit/3192a2e34bc7f53d6b64bb6647ea80353cd22caa

The problem can also be fixed by changing -1 to (char)(-1), which is the approach that the upstream ABC took. The following change merges this and some other minor changes from the upstream version of the file:

https://github.com/bitblaze-fuzzball/stp/commit/308c97bf5bc068c6aa30aa92595879910e08bd18

Making the file closer to the upstream version rather that farther away is desirable in its own way, though if the plan is to get rid of our separate copy of ABC soon anyway, perhaps it doesn't matter. Let me know if you'd like me to turn one of these changes into a pull request.

The first version of the change is the only one I've tested on my ARM laptop so far, but I can confirm it fixes the problem there. I haven't done any more systematic testing of ARM STP yet, though it works for the FuzzBALL example where I originally noticed the problem. (I'm guessing this bug would have been hit by an query that used the AIG-based CNF conversion; I was surprised by how far STP got on my symbolic execution path conditions before reaching it.)

**Comment by TrevorHansen** [comment]
Thanks Stephen,

If it's easily done, patching our ABC seems the nicest for now. As per #159, there seem to be build system differences that are making it difficult for us to use the upstream.

Trev.

**Comment by msoos** [comment]
Yeah, Trevor, can you please patch it? In the meanwhile I'll make progress towards using libabc as a separate library

**Comment by msoos** [comment]
Thanks I have fixed this by applying your patch. We should be on the new libabc.

You have an ARM laptop? That's kinda cool... what is it? :)

**Comment by smcc** [comment]
The ARM laptop I've used for this testing is an ASUS C201, sold as a Chromebook. You can use it for general-purpose Linux hacking either with a "Crouton" chroot environment inside Chrome OS, or by installing a regular Linux distribution on its own partition (I would have preferred Debian, but Arch is the distribution whose instructions I was able to get running first.) In addition to a cheap platform to play with real ARM hardware, I was also hoping I could use it as a general-use lightweight laptop, though I haven't yet gotten my real-Linux installation working well enough for this yet.

**Comment by msoos** [comment]
Thanks! That's a pretty nice piece. ThinkPad has the 110S that's is quite
amazing, it's worth checking out. Same price range, but IPS panel. Great
for hacking, I think.

Thanks again, and thanks for the detailed bug description&fix! I wish all
were this clean and well-reasoned :)

Cheers!
