### ISSUE TITLE
stp/lib/Parser/smt2.y: conflicts: 1 reduce/reduce

### ISSUE THREAD

**Issue by c0d4r** [stp/stp#272]
stp/lib/Parser/smt2.y: conflicts: 1 reduce/reduce
stp/lib/Parser/smt2.y:4.9-19: error: %define variable 'parse.error' is not used
make[2]: *** [lib/Parser/parsesmt2.tab.cpp] Error 1
make[1]: *** [lib/Parser/CMakeFiles/parser_headersmt2.dir/all] Error 2
make: *** [all] Error 2

**Comment by msoos** [comment]
Oops thanks for the bugreport!! I'll fix this on Saturday :)

Cheers!

**Comment by msoos** [comment]
Thanks, it should be fixed now :)
