### ISSUE TITLE
Broken installation for user-defined prefix

### ISSUE THREAD

**Issue by hoangmle** [stp/stp#276]
Before 4b2762635930b2140df14b5b933996cfd2f70686, `STP_INCLUDE_DIR` from `STPConfig.cmake` stores the full include path, but now just the string `include`. Maybe we should use `${CMAKE_INSTALL_FULL_INCLUDEDIR}` instead of `${CMAKE_INSTALL_INCLUDEDIR}` here https://github.com/stp/stp/blob/4b2762635930b2140df14b5b933996cfd2f70686/CMakeLists.txt#L555?

**Comment by msoos** [comment]
Thanks, fixed! :) More of these please, great bug report, good stuff! Thx again!
