### ISSUE TITLE
Failing SMT2 instances.

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#277]
After fuzzing STP for about a month, it's found two instances that produce the wrong answer.

I've simplified them and checked them in here: 09db593130d042593b14387e320f18146aa9bbea

Looking quickly, it seems like there's a defect in the array transformer, the code that converts array problems into bit-vector problems.

I'll work on it in the next week, but if anyone else is interested, I'd appreciate some help.

**Comment by TrevorHansen** [comment]
Fixed in ba5c1d590c63166bc90de458732538dfdf83b79c

**Comment by msoos** [comment]
Wow, thanks a lot Trevor! I think we ought to have a fuzzer in the cloud. It'd be about 10 USD to do that fuzzing you did. It'd cost about 0.3 USD/h for a 16core machine (AWS spot c4.8xlarge instance), so that's about 530 core-hours, about 22 days worth of single-core fuzzing. I have some scripts... I really need to make them more flexible.

**Comment by msoos** [comment]
By the way, did you use the script for fuzzing to do it? I'm curious if it was useful at all. If you had to adjust, it'd be nice if you could commit that back!

**Comment by TrevorHansen** [comment]
Hi Mate,

I used fuzzsmt  (https://github.com/msoos/fuzzsmt), in batch mode, producing 5000 instances per iteration. Then I merged them into a single file on a ramdisk. Then I compared the results of running the combined file with STP & MinkeyRink. Across 8 cores on my Ryzen 1700, it runs through about 40M instances per day.  The defect in the array transformer showed up 3 in about 1.2B instances, so about 1 in 400M instances was failing.

As a next step I'd like to try running the fuzzer at larger bit-widths (i.e. >64 bits) and with a timeout on the solvers.

When I've looked at the fuzzing script in our repository it was a bit slow. With the bulk fuzzer at low bit-widths I can test about 50 instances per second per core.

**Comment by msoos** [comment]
That's interesting, the combination trick. Can't do that with CNF instances, hence I never thought about it. We are using individually generated fuzz instances in the fuzzer (also uses fuzzsmt). To be honest, I need to include fuzzsmt in the STP distribution through git modules. I included the fuzzers with CMS though git modules and it's so much easier that way. Deployment on a cloud cluster&fuzzing is a breeze like that.

3/1.2B is crazy... also, congrats on the Ryzen. I wanted to get a ThreadRipper, for similar reasons (i.e. HPC computing).

Thanks for the detailed answer!
