### ISSUE TITLE
can GPU be used to accelerate STP solver? 

### ISSUE THREAD

**Issue by moliam** [stp/stp#278]
as the title.

**Comment by rgov** [comment]
It is not a currently supported feature and there is no effort to add it. First, we would need to have an underlying SAT solver which is GPU-accelerated, or at least SIMD-accelerated.

**Comment by msoos** [comment]
All of that is almost completely impossible. I used to program GPGPUs. Someone I truly trust has tried it too, to no avail. However, @moliam you are more than welcome to do it. However, you will have to do this fully on your own, I cannot help you at all, as I fully believe this is wasted time.
