### ISSUE TITLE
STP with -g doesn't timeout

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#279]
When I run STP with a timeout, it sometimes seems to exceed the number of conflicts without exiting. 

I've attached a sample SMT2 file and an output of the run. I try to limit to 100K conflicts, but it keeps going. The last line:

c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
c   glue     1   357  140K  605236 4184K  199K    3.93    3.85   77K  3161   20K  646K   35.39    6.54

seems to show that it has reached 140K conflicts. 

When I output the CNF and run it in cryptominisat with the --max-confl option it exits properly. I guess because we are calling cryptominisat differently. In STP, we call cryptominsat for this problem with set_no_simplify_at_startup enabled. I don't know the command line option that causes the same effect? Do you have any ideas @msoos ? 

[run.txt](https://github.com/stp/stp/files/1709195/run.txt)
[slow.smt2.txt](https://github.com/stp/stp/files/1709198/slow.smt2.txt)

**Comment by msoos** [comment]
I fixed this, but assigned it the wrong bug code :) Here is the fix: 6073b502e9b4e54b25337041660705c72f94f7ca

What happened was that CMS's interface requires the limit to be set every time before `solve()` is called. This is so that each `solve()` call can have its own limit.  As you might imagine, this can be advantageous.

I now set the limit on _each_ `solve()` call, individually to be X (e.g. 10k). This of course leads to longer overall solving time. However, I don't think this is bad in the long term. What do you think? I can of course still create an overall limit, e.g. `max_confl_overall` for CMS? Would that be better?

**Comment by TrevorHansen** [comment]
Thanks Mate,

I think it's best to have an overall limit. If we're doing abstraction refinement, `solve()` might be called lots of times. So it might take much longer than you expect to timeout.

I don't think we need to make a change in CMS though, could I just decrease `max_confl` by `get_sum_conflicts()` after each call to `solve()`? Is `get_sum_conflicts` just the number of conflicts during the last call to `solve()`, not the sum of conflicts on all calls?

Trev.

**Comment by msoos** [comment]
Actually, the sum_conflicts doesn't do that... I am making new functions:

```
//Get info about only the last solve() call -- summed for all threads
        uint64_t get_last_solve_sum_thread_conflicts(); //get total number of conflicts of last solve() call of all threads
        uint64_t get_last_solve_sum_thread_propagations();  //get total number of propagations of last solve() call made by all threads
        uint64_t get_last_solve_sum_thread_decisions(); //get total number of decisions of last solve() call made by all threads
```

I am also making the descriptions of the other ones cleaner. I'll get back to you in a day or two with the above implemented. Sorry!

**Comment by msoos** [comment]
The `get_sum_conflicts` actually gets the sum. So that won't work. I pushed this new header functions to CMS master:

```
        //Get info about only the last solve() OR simplify() call -- summed for all threads
        uint64_t get_last_conflicts(); //get total number of conflicts of last solve() or simplify() call of all threads
        uint64_t get_last_propagations();  //get total number of propagations of last solve() or simplify() call made by all threads
        uint64_t get_last_decisions(); //get total number of decisions of last solve() or simplify() call made by all threads
```

That should do the trick :)

**Comment by msoos** [comment]
Thanks! Hope it wasn't too much trouble!
