### ISSUE TITLE
Remove CVC input support

### ISSUE THREAD

**Issue by rgov** [stp/stp#282]
STP will go SMT-LIB2-only in version 3.0. As @msoos points out, only CVC and STP support the CVC input language, and even CVC4 supports SMT-LIB2.

**Comment by TrevorHansen** [comment]
Leaving CVC in doesn't bother me. Happy to discuss.

**Comment by TrevorHansen** [comment]
This has come up again. Does anyone know if the CVC input is used by anyone, or it'd be OK to remove it?
