### ISSUE TITLE
Automatically create manpage with help2man

### ISSUE THREAD

**Issue by msoos** [stp/stp#284]

**Comment by rgov** [comment]
I'd suggest making this an optional step for CMake, if the `help2man` tool is included. We can also include a pre-built version.

To keep the pre-built version in sync, we can have Travis run `help2man` itself and diff the output with the pre-built version, and fail the build if they are different.

More difficult, we could have Travis rebuilt the manpage and commit the new version and push it back. (Or maybe open a pull request?) But I think just failing the build is OK for now.

**Comment by msoos** [comment]
It's an optional step in CMAKE in CMS :) Travis re-builds it and can export the asset :) But we can deal with that later. Let's do it one step at at time :)
