### ISSUE TITLE
problems with solving linear equations

### ISSUE THREAD

**Issue by moliam** [stp/stp#285]
I have 50 linear equations with 50 variables to be solved, and it is quick for STP to give the answer. However, if I give 49 linear euqations with 50 variables( just remove one from the 50 equations ), the solving time increases significantly. Why ?
I know that mathematically there are actually infinite number of solutions to the latter situation, is this the reason ? When solving a set of constraints, would STP find as many as possible the satisfiable solutions or just find one of them ?

**Comment by TrevorHansen** [comment]
STP will re-arrange a linear equation to isolate a variable and then substitute through all the linear equations for the isolated variable. There's no intelligence applied to the order of substitutions. If you're seeing big differences in runtime for small differences in inputs, my guess is that (in the slow case) the substitutions are being performed in an order that doesn't let all the equations be removed.

STP will stop after finding one satisfiable solution.

**Comment by msoos** [comment]
We could probably use M4RI here, and do Gaussian elimination at top-level?
Sounds like some work though...

By the way, I'm curious, maybe CMS with Gauss would recover the matrix and
solve it instantly? We could give it a try. Can you please provide an SMT2
example file both the fast and slow one? It could be interesting and we
could really help you. Thanks!

**Comment by msoos** [comment]
I am closing since you haven't given us the 2 examples so we could compare and fix. In case you can give these two examples, please post them here and we can re-open. Until then, the bug cannot be managed as we have no inputs to trigger it.
