### ISSUE TITLE
Getting coverity scan working

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#286]
I expected that if I merged master into the coverity_scan branch, then it would automatically begin a coverity analysis.  The build has completed, but online the last analysis showing is from Jul-15:

https://scan.coverity.com/projects/861

Are there some other steps required to launch the analysis?

**Comment by msoos** [comment]
Coverity had a security breach. Our keys and passwords and everything has to be re-generated. Will do...

**Comment by msoos** [comment]
OK, reset password, generated new token, updated and re-merged. Should be OK now :)

**Comment by TrevorHansen** [comment]
Thanks Mate, I've looked through the reports and submitted some small fixes.  I don't think there's any reported issues worth worrying about.

**Comment by msoos** [comment]
Cool! It should just run from now on. They had to reset all secrets, they had a breach. I fixed them all (CMS + STP).
