### ISSUE TITLE
option to bit-blast in CNF and call the SAT solver

### ISSUE THREAD

**Issue by steseb** [stp/stp#293]
Hello,
I noticed a severe performance degradation by using STP with the cryptominisat backend in place of directly call cryptominisat. Is it possible to have an option on the binary (and on the python API) that just bit-blasts the SMT2 expressions in CNF form and then calls the SAT solver used in the backend?

Thanks

**Comment by kuldeepmeel** [comment]
In particular, we did an extensive analysis via the following steps:

**Comment by steseb** [comment]
Just to clarify the experiments that we have performed.
Source files are in smt2-lib format:

1. call `STP` to solve the expression: stp --SMTLIB2 "$smtfile" -r -a -w --disable-equality

2. solve by directly calling `CryptoMiniSat`:
2.1) call `STP` to get the `CNF` conversion: stp --SMTLIB2 "$smtfile" --disable-simplifications --output-CNF --exit-after-CNF
2.2) call `CryptoMiniSat` on the CNF/ DIMACS file format: cryptominisat5 --zero-exit-status --verb 0 cnfoutfile.cnf

These are the results of the execution time (in seconds) over some expressions:

CryptoMiniSat | STP
-- | --
8,79 | 14,99
22,19 | 29,49
188,14 | 298,53
1368,74 | 4173,29
59780,3 | 78059,06
15,45 | 10,63
13,33 | 22,21
10,27 | 18,43
280,18 | 383,45
408,02 | 1218,31
5230,07 | 37528,87
166,7 | 220
448,02 | 475,87
5725,9 | 16899,16
23,49 | 32,47
20,8 | 12,42
278,76 | 391,93
484,53 | 1239,42
6887,69 | 32025,75
26,63 | 18,36
298,19 | 288,45
439,34 | 1094,9
6986,66 | 32026,92
8,77 | 18,29
127,27 | 179,14
441,13 | 1091,9
8435,17 | 33181,47

as you can see in several cases the performance degradation is severe. A direct call to the SAT backend after the bit blast should solve my issue.

**Comment by kuldeepmeel** [comment]
We found that 
stp --SMTLIB2 "$smtfile" --disable-simplifications
behaved worse than
stp --SMTLIB2 "$smtfile" -r -a -w --disable-equality

Absolutely, Stefano can share the SMT2 files.

**Comment by steseb** [comment]
Please find attached the SMT2 files we used in our experiments
[stpVsCryptominisat.zip](https://github.com/stp/stp/files/2192451/stpVsCryptominisat.zip)

Thank you

**Comment by TrevorHansen** [comment]
Hi @msoos, 

I'm trying to understand why there is a slowdown when running CMS within STP versus running it externally.  On the attached smt2 example it's about 13 times faster to output the CNF and run CMS, versus run CMS inside STP.

[ext_con_044_002_0128.smt2.txt](https://github.com/stp/stp/files/2270225/ext_con_044_002_0128.smt2.txt)

For example, when I run the attached smt2 file, it spends 33 seconds in SAT solving
> c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
> c [distill] long cls tried: 0/0 cl-short:0 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 0/0/0 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c [distill] long cls tried: 17/10 cl-short:34 lit-r:23 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 34/17/17 lits-rem: 23 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1    22  4097   10605   29K  5077    4.01    3.72    61  1946  2079     7   11.78   11.76
> c [distill] long cls tried: 51/61 cl-short:102 lit-r:2 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 102/51/61 lits-rem: 2 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1    78  8194   10605   29K  5077    4.01    3.72    67  2736  5380     7   15.01   15.00
> c [distill] long cls tried: 175/232 cl-short:346 lit-r:132 T: 0.00 T-out: N T-r: 99.99%
> c [distill] long useful: 346/175/236 lits-rem: 132 0-depth-assigns: 0 T: 0.00 T-out: N
> c   geom     1   152 12291   10605   29K  5077    4.01    3.72   232  2669  9374    10   19.79   19.77
> c   geom     1   197 16388   10605   29K  5077    4.01    3.72   239  3677  8612    10   21.59   21.57
> c [distill] long cls tried: 7/237 cl-short:10 lit-r:15 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 10/7/239 lits-rem: 15 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1   249   20K   10605   29K  5077    4.01    3.72   256  3937 12430    10   22.77   22.76
> c [distill] long cls tried: 19/256 cl-short:38 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 38/19/256 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1   314   24K   10605   29K  5077    4.01    3.72   256  3952 16512    10   24.12   24.11
> c   glue     1   365   28K   10605   29K  5077    4.01    3.72   256  3959   20K    10   24.95   24.94
> c [distill] long cls tried: 2/258 cl-short:4 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 4/2/258 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1   389   32K   10605   29K  5077    4.01    3.72   258  4031   20K    10   24.71   24.70
> c   glue     1   394   36K   10605   29K  5077    4.01    3.72   258  4036   25K    10   25.34   25.33
> c   glue     1   397   40K   10605   29K  5077    4.01    3.72   258  1627   31K    10   25.75   25.74
> c [distill] long cls tried: 0/258 cl-short:0 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 0/0/258 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1   399   45K   10605   29K  5077    4.01    3.72   258  1657   30K    10   26.06   26.06
> c   glue     1   401   49K   10605   29K  5077    4.01    3.72   258  1806   34K    10   25.89   25.88
> c   glue     1   403   53K   10605   29K  5077    4.01    3.72   262   944   39K    10   26.16   26.16
> c [distill] long cls tried: 4/262 cl-short:8 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 8/4/262 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c   geom     1   404   57K   10605   29K  5077    4.01    3.72   262   955   43K    10   26.40   26.40
> c   glue     1   405   61K   10605   29K  5077    4.01    3.72   264   917   34K    10   25.51   25.51
> c   glue     1   407   65K   10605   29K  5077    4.01    3.72   264   926   38K    10   25.80   25.80
> c   glue     1   407   69K   10605   29K  5077    4.01    3.72   264   927   42K    10   26.07   26.06
> c recursive minimization cost OK: 240Kcost/(% lits removed)
> c --> Executing strategy token: handle-comps
> c --> Executing strategy token: scc-vrepl
> c [scc] new: 1 BP 0M T: 0.00
> c --> Executing strategy token: cache-clean
> c --> Executing strategy token: cache-tryboth
> c --> Executing strategy token: sub-impl
> c [impl sub] bin: 3 T: 0.00 T-out: N w-visit: 21418
> c --> Executing strategy token: intree-probe
> c [scc] new: 70 BP 0M T: 0.00
> c [vrep] vars 65 lits 607773 rem-bin-cls 276 rem-long-cls 9 BP 0M T: 0.03
> c [scc] new: 0 BP 0M T: 0.00
> c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-long-cls 0 BP 0M T: 0.01
> c [intree] Set 0 vars hyper-added: 32 trans-irred::0 trans-red::0 T: 0.02 T-out: N T-r: 99.93%
> c --> Executing strategy token: probe
> c --> Executing strategy token: sub-str-cls-with-bin
> c [distill] cache-based irred--  cl tried    58636 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.04 T-out: N
> c [distill] cache-based   red--  cl tried      528 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
> c --> Executing strategy token: distill-cls
> c [distill] long cls tried: 29318/29318 cl-short:1 lit-r:0 T: 0.42 T-out: N T-r: 41.33%
> c [distill] long useful: 2/58636/58636 lits-rem: 0 0-depth-assigns: 0 T: 0.84 T-out: N
> c --> Executing strategy token: scc-vrepl
> c [scc] new: 0 BP 0M T: 0.00
> c --> Executing strategy token: sub-impl
> c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 21418
> c --> Executing strategy token: str-impl
> c [impl str] lit bin: 0 (by stamp: 0) set-var: 0 T: 0.00 T-out: N T-r: 99.94% w-visit: 21418
> c --> Executing strategy token: sub-impl
> c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 21418
> c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-xor,'
> c [occ] mem usage for occur      2 MB
> c [occ] mem usage for occur      0 MB
> c Mem for watch alloc      : 8           MB (35.16     %)
> c Mem for watch array      : 0           MB (1.94      %)
> c --> Executing OCC strategy token: occ-backw-sub-str
> c [occ-backw-sub-str-long-w-bins] subs: 0 str: 0 tried: 9324 0-depth ass: 0 T: 0.00 T-out: N T-r: 99.90%
> c [occ-sub-long-w-long] rem cl: 117 tried: 147540/73770 (200.0%) T: 0.04 T-out: N T-r: 96.57%
> c [occ-sub-str-long-w-long] sub: 0 str: 0 tried: 221310/73770 (300.0)  T: 0.08 T-out: N T-r: 92.19%
> c --> Executing OCC strategy token: occ-clean-implicit
> c --> Executing OCC strategy token: occ-bve
> c [occ-empty-res] Empty resolvent elimed: 4289 T: 0.00 T-out: N
> c  #try to eliminate:   7334
> c  #var-elim        :   6195
> c  #T-o: N
> c  #T-r: 99.99%
> c  #T  : 0.07
> c [occur] 0.02 is overhead
> c [occur] link-in T: 0.02 cleanup T: 0.00
> c [consolidate] T: 0.00
> c global_timeout_multiplier: 4.40

But if output the CNF and run it in CMS, it takes about 2.6 seconds. That is, it's about 13 times faster:

> cryptominisat5 output_0.cnf 
> c Outputting solution to console
> c CryptoMiniSat version 5.6.3
> c CryptoMiniSat SHA revision f65efe012a9d365d576ee82dfd326f8275b16d72
> c CryptoMiniSat compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fno-stack-protector -Wlogical-op -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DNDEBUG -D_FORTIFY_SOURCE=0 -DUSE_M4RI | STATICCOMPILE = ON | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND =  | VALGRIND_FOUND = TRUE | ENABLE_TESTING = OFF | M4RI_FOUND = TRUE | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = OFF | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = /usr/lib/x86_64-linux-gnu/libpython2.7.a | PYTHON_INCLUDE_DIRS = /usr/include/python2.7 | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Aug  5 2018 22:22:31
> c CryptoMiniSat compiled with gcc version 5.4.0 20160609
> c Executed with command line: cryptominisat5 output_0.cnf
> c Reading file 'output_0.cnf'
> c -- header says num vars:          10709
> c -- header says num clauses:       34684
> c WARNING: Empty line at line number 34687 -- this is not part of the DIMACS specifications (http://www.satcompetition.org/2009/format-benchmarks2009.html). Ignoring.
> c -- clauses added: 34684
> c -- xor clauses added: 0
> c -- vars added 10709
> c Parsing time: 0.01 s
> c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
> c [distill] long cls tried: 0/0 cl-short:0 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
> c [distill] long useful: 0/0/0 lits-rem: 0 0-depth-assigns: 0 T: 0.00 T-out: N
> c [distill] long cls tried: 392/387 cl-short:780 lit-r:256 T: 0.00 T-out: N T-r: 99.99%
> c [distill] long useful: 780/392/392 lits-rem: 256 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1    45  4097   10604   29K  5077    4.01    3.72   619   798  2661    13   20.95   20.89
> c [distill] long cls tried: 475/858 cl-short:950 lit-r:109 T: 0.00 T-out: N T-r: 99.99%
> c [distill] long useful: 950/475/862 lits-rem: 109 0-depth-assigns: 0 T: 0.00 T-out: N
> c   glue     1    78  8194   10604   29K  5077    4.01    3.72  1029  1456  5681    22   20.63   20.58
> c [distill] long cls tried: 1786/2618 cl-short:3572 lit-r:860 T: 0.01 T-out: N T-r: 99.90%
> c [distill] long useful: 3572/1786/2644 lits-rem: 860 0-depth-assigns: 0 T: 0.01 T-out: N
> c   geom     1   100 12291   10604   29K  5077    4.01    3.72  2731   784  8710    60   19.80   19.71
> c   geom     1   110 16388   10604   29K  5077    4.01    3.72  3273  2385  9452    70   17.80   17.73
> c [distill] long cls tried: 682/3289 cl-short:1361 lit-r:224 T: 0.01 T-out: N T-r: 99.94%
> c [distill] long useful: 1361/682/3300 lits-rem: 224 0-depth-assigns: 1 T: 0.01 T-out: N
> c   glue     1   116   20K   10600   29K  5077    4.01    3.72  4831  1896 12445   100   17.23   17.15
> c [distill] long cls tried: 1703/4611 cl-short:2949 lit-r:903 T: 0.02 T-out: N T-r: 99.77%
> c [distill] long useful: 2949/1703/4992 lits-rem: 903 0-depth-assigns: 23 T: 0.02 T-out: N
> c ------- FINAL TOTAL SEARCH STATS ---------
> c UIP search time          : 2.66        (99.55     % time)
> c restarts                 : 119         (200.50    confls per restart)
> c blocked restarts         : 43          (0.36      per normal restart)
> c time                     : 2.66        
> c decisions                : 2851450     (0.00      % random)
> c propagations             : 20053672    
> c decisions/conflicts      : 119.51      
> c conflicts                : 23860       (8983.43   / sec)
> c conf lits non-minim      : 654182      (27.42     lit/confl)
> c conf lits final          : 17.43       
> c cache hit re-learnt cl   : 0           (0.00      % of confl)
> c red which0               : 2396        (10.04     % of confl)
> c props/decision           : 0.00        
> c props/conflict           : 0.00        
> c 0-depth assigns          : 162         (1.51      % vars)
> c 0-depth assigns by CNF   : 60          (0.56      % vars)
> c reduceDB time            : 0.00        (0.00      % time)
> c OccSimplifier time       : 0.00        (0.00      % time)
> c [occur] 0.00 is overhead
> c [occur] link-in T: 0.00 cleanup T: 0.00
> c SCC time                 : 0.00        (0.00      % time)
> c [scc] new: 0 BP 0M  T: 0.00
> c vrep replace time        : 0.00        (0.00      % time)
> c vrep tree roots          : 0           
> c vrep trees' crown        : 0           (0.00      leafs/tree)
> c distill time             : 0.04        (1.35      % time)
> c strength cache-irred time: 0.00        (0.00      % time)
> c strength cache-red time  : 0.00        (0.00      % time)
> c Conflicts in UIP         : 23860       (8943.03   confl/TOTAL_TIME_SEC)
> c Mem used                 : 11.59       MB
> c Total time               : 2.67        
> s UNSATISFIABLE
> 

My first guess is that there is some simplification that we need to enable via the CMS API?

Thanks!

**Comment by msoos** [comment]
I am sorry, I am *extremely* overwhelmed. I will get back to this in a week or so. It is on my agenda. Please let me know if 1-2 week delay is absolutely unacceptable. Thanks!

**Comment by msoos** [comment]
OK, as promised, once I got everything sorted, I am now back and I fixed this :) The issue was a change I added many years ago that set the forced polarity to be `false` which meant that polarity caching was disabled. Polarity caching is super important but back in the days, it seemed that polarity caching was doing things that was not that useful to STP's behaviour as it seemed to have expected that subsequent solutions should be close to one another (and hopefully most variables would be `false`). I don't know how this change affects problems where abstraction refinement is used -- I suspect it affects them badly? @TrevorHansen can you please check? This would be important to check I think....

**Comment by msoos** [comment]
Note that behaviour is now *exactly the same* whether you dump the CNF and then you solve or not. I mean, it's not just similar. Every single branch and every single decision, every conflict clause, **everything** is the same.

**Comment by TrevorHansen** [comment]
Thanks for looking into it @msoos, it's something I should have spotted.

I've a few things to do:
* Some of our "simplifications" made these problems harder, I need to recheck the cut-offs. starexec is currently down, so I'll do another time.
* I'll check how the change impacts on problems with arrays, from memory we disable some CMS simplifications for problems with arrays, so if disabling polarity is better just for problems with arrays, it seems easy to do.

**Comment by TrevorHansen** [comment]
It's all working fine.
