### ISSUE TITLE
Arbitrary-length bitvector constants?

### ISSUE THREAD

**Issue by maxzinkus** [stp/stp#303]
I see that bitvector constants over `sizeof(unsigned long long int)` are an error per: https://github.com/stp/stp/blob/c68788eb05731ae08e4f730a6b1c93803620e2b9/lib/STPManager/STPManager.cpp#L187
Is there no way to create a larger bitvector constant value?

**Comment by rgov** [comment]
If you remove that (or change it to just `width <= 0`, what breaks? I don't know if that assertion is really true.

We would *love* to replace the bit vector implementation, but I haven't found anything that would fit in easily.

**Comment by maxzinkus** [comment]
After changing the above, I'm running into:
```
python: /home/mz/stp/lib/Simplifier/constantBitP/ConstantBitP_TransferFunctions.cpp:49: simplifier::constantBitP::Result simplifier::constantBitP::bvEqualsBothWays(simplifier::constantBitP::FixedBits&, simplifier::constantBitP::FixedBits&, simplifier::constantBitP::FixedBits&): Assertion `a.getWidth() == b.getWidth()' failed.
```
but that may not be because of the width of a constant. This will be easier to figure out with #302

**Comment by TrevorHansen** [comment]
Hi Max, It sounds like you need bit-vector constants with more than 2^64
bits, or have I misunderstood?

**Comment by maxzinkus** [comment]
@TrevorHansen With more than 64 bits, representing values greater than `2^64`, thankfully not with `2^64` bits.

**Comment by TrevorHansen** [comment]
If you want to make a constant with 256-bits (say), you should be able to
do it by passing a string to one of the creation functions? They should
work for less than 2^(32) bits.

**Comment by maxzinkus** [comment]
@TrevorHansen Thank you, I'll look into that. Could you give me a documentation reference or an example?

**Comment by TrevorHansen** [comment]
Hi @maxzinkus, It didn't seem to be exposed in the python API.  I had a go at fixing it, but have never used python or the API before.

**Comment by maxzinkus** [comment]
Awesome, thank you!
As suggested I also tried removing the width check and it actually seems to be working just fine, using
`solver.bitvecval(size, value)` from python

**Comment by maxzinkus** [comment]
Ah, writing the PR I bumped into an issue. I wanted to change `bvconst` to a pointer to a buffer which can be walked to get all `width` bits of the constant. The trouble is, this requires a decision on or detection of endianness. When all the bits are in a buffer, they can be extracted via masking, but as soon as we introduce a buffer, a byte order has to be defined. Making code detect endianness feels gross - anyone have thoughts on a better way?

**Comment by maxzinkus** [comment]
Perhaps @TrevorHansen 's solution is the better way. I'll wait for #304 and see where we can go from there.

Thanks all!
