### ISSUE TITLE
Bitvecval value in python

### ISSUE THREAD

**Issue by steseb** [stp/stp#306]
It seems that the Python interface doesn't provide the right name/value for the a constant bit vector.

Please see the small example below:
```
import stp
a = stp.Solver()
x = a.bitvec('x')
x.name
>>> 'x'
x.value
>>> 0
y = a.bitvecval(32, 18)
y.name
>>>
y.value
>>> {'x': 0}
```

if `x.value == 0` could just stand for a placeholder for the symbolic bit vector, I don't understand why `y.value` returns `x`

**Comment by msoos** [comment]
Ah that sounds crappy... could you please take a look in the python interface code and check what could be causing this? Maybe you could find it? I'd be really grateful :) We are a bit busy doing a lot of other stuff so a helping hand would be great! Thanks :)

**Comment by steseb** [comment]
I tried to have a look.

Assuming that it is ok to get 0 for the `value` of a new `bitvec`, the problem with the `bitvecval` seems that `Expr.value()` searches in the `Solver.model()` by name, but BV constants don't have one.

If no name/key is provided, `model` returns all the expressions having a key i.e., only the `bitvec`s. 

I can't solve this.

**Comment by andrewvaughanj** [comment]
@steseb I forgot about this; there's a chance this is done -- see: #328 

If you're happy, can you close the issue?
