### ISSUE TITLE
Exported STP version number is incorrect

### ISSUE THREAD

**Issue by MartinNowack** [stp/stp#307]
The version number exposed by STP is incorrect since a couple of versions (after 2.1.2):

https://github.com/stp/stp/blob/20593fcdc258e056a583aabf9390422c72ecb246/CMakeLists.txt#L298

This leads to wrongly exported version strings of the dynamic libraries of STP and of course wrongly linked files.

I guess it would be useful to add a new `.x` release for versions released after 2.1.2.

**Comment by msoos** [comment]
I'm so sorry. I have now both updated that to 2.3.2 and I have pushed a new tag 2.3.2, creating a release. I am now compiling the binaries so the release is nice and shiny. I will now fix the AppVeyor build as well and have Windows binaries too -- probably by tomorrow evening :)

Thanks so much for letting us know. Please let me know if this fixes the bug!

**Comment by MartinNowack** [comment]
@msoos Fantastic!! Thanks a lot.

**Comment by msoos** [comment]
Thanks for the feedback :) Closing.
