### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [stp/stp#310]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [CryptoMiniSat5](https://github.com/stp/stp/blob/65d84fa64e1a6f4bf3a5407305cf769fe7d4788b/lib/Sat/CryptoMinisat5.cpp#L43)
- [Simplifier](https://github.com/stp/stp/blob/c68788eb05731ae08e4f730a6b1c93803620e2b9/include/stp/Simplifier/Simplifier.h#L88)

**Comment by msoos** [comment]
The idea is good, but currently, we are using valgrind to make sure no memory leaks, and in what we could find, there was none. Hence, I don't see the clear benefit here. However, in case you would like to pursue this, please create a pull request, we'd be happy to review and merge! Looking forward to the pull request,

Mate
