### ISSUE TITLE
How to create stpwin.lib?

### ISSUE THREAD

**Issue by shell33** [stp/stp#319]
When I want to install on Win7 64bit, I cannot creat stpwin.lib, so stp cannot install in my PC correctly. So I try to use 'dumpbin -exports' to create stpwin.lib from stpwin.dll, but the output do not contain any function, so the stpwin.lib that I create do not contain any function which means the stpwin.lib is not correct.
I have Visual Studio 2015, Python3.6 64bit, cygwin64, git64, zlib and minisat, these are all install correctly.
Please tell me how to create stpwin.lib? THANKS!

**Comment by msoos** [comment]
Hi,

You can use Visual Studio to build STP. Please see these steps:

https://github.com/stp/stp/blob/master/appveyor.yml

It should allow you to build STP in Visual Studio. Let us know how it went!

Good luck,

Mate

**Comment by shell33** [comment]
THX, I will try.

shell33

**Comment by msoos** [comment]
Cool, good luck! Let us know how it went! Note that by default that builds
a static library. If you need a dynamic one, try adjusting the parameters
to the build options. If it doesn't work, let us know and we can try to
walk you through it and then document it in the README so others don't have
to suffer :)

**Comment by shell33** [comment]
I success building it in Win7 64bit. THX!
But there is one more question.
When I try to install it in Win7 32bit, in 'cmake' commands, I use "Visual Studio 14 2015" instead of "Visual Studio 14 2015 Win64". And when build boost, I ignore 'address-model=64'. The building process has no error. But finally I only get 'stp_simple.exe', do not get 'stp.exe'.
Where am I doing something wrong?

shell33

**Comment by msoos** [comment]
Hey,

Glad to hear you built the library -- don't worry about the stp EXE. The
library is not affected by boost at all! And you can always download the
full STP executable from Appveyor, just click on the appveyor icon at the
top of the GitHub README page of STP (small mini icons, should be green)
and navigate to a build that is green and click "artifacts" on the top
right and you can download the full executable. Good luck!

Please document exactly how you built the library so others can do it as
well! Please send us how you did it, step by step :)

**Comment by shell33** [comment]
THX again!
Using the steps that contain in 'appveyor.yml', stp can be build on Win7 64/32bit easily. However, using the steps that contain in README page of STP always get some errors.
1. git config --global core.autocrlf input
2. Get 'lit.exe' of python(do not forget '-m').
3. Build boost.
4. Build zlib.
5. Build minisat.
6. Build cryptominisat.
7. Using 'cygwin' get flex, bison, perl.
8. Build stp.
There are some points should be noted that I think.
1. environment: after installing cmake, git, cygwin in PC, add these EXE path to PATH(environment)
2. If you want to build STP in Windows 32bit, I think you should not contain 'address-model=64' when you build boost. Because I have one error(X64 do not match X86).
3. Use administer cmd.
4. Release.
Good luck,

shell33

**Comment by msoos** [comment]
Thanks so much! Okay, I have updated the README to point to the AppVeyor build files and also to this issue :) Thank you again!

Mate
