### ISSUE TITLE
Consider using MiniSAT fork

### ISSUE THREAD

**Issue by rgov** [stp/stp#321]
https://github.com/master-keying/minisat

They are cleaning up MiniSAT to fix compiler warnings and so forth. [Comparison](https://github.com/niklasso/minisat/compare/master...master-keying:master).

**Comment by msoos** [comment]
I would really not bother. It would take a lot of time to check they did the right thing and frankly, MiniSat is *great*. Needs no changes to compile and work perfectly well. Some algorithms and data structures in MiniSat are extremely sensitive to change, so it would take me 5-8k CPU hours on a cluster to verify this change is not for the worse. I strongly suggest we forget about this. We should be using Riss and CryptoMiniSat anyway, they are waaaaay better solvers than MiniSat. Please close in case you feel like I haven't overlooked something, which may well have happened. However, I would be very reluctant to check all their changes. It's extremely time-consuming and very-very minor changes can have huge effects, as I have had to learn in the past many years.

**Comment by rgov** [comment]
Hm, ok. They do have some [larger changes](https://github.com/niklasso/minisat/commit/0894d6ea13571e78631c45a33baaba4af94fd4a4) that I think are of marginal benefit compared to risk of introducing regressions (in performance or correctness). Other changes seem nice, like removing the warning over confusing conditions like `if (a || b && c)`, and adding CI, although we use our own CI for MiniSat.

Since MiniSat is so stable, though, and we have alternatives, I agree we don't need to use the fork.

**Comment by msoos** [comment]
Thanks! Sorry, I just had a look at that change... I will not have time to check that. It's not that fun to live with the warnings, I agree, but they are harmless (there are no bugs in MiniSat) and we are not using MiniSat anyway most of the time. I'm glad you agree :) Thanks again!
