### ISSUE TITLE
Timeout code has broken STP

### ISSUE THREAD

**Issue by andrewvaughanj** [stp/stp#324]
- [x] fix the broken tests

- [x] understand how the build got broken

**Comment by andrewvaughanj** [comment]
@msoos what cmake target do I need to exercise https://github.com/stp/stp/commit/06f6eb86d9d87d50926a95c0df3c53854c826ee9? 

Here's my `cmake` command:

```
    cmake .. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DBoost_USE_STATIC_LIBS=1 \
    -DENABLE_TESTING=1 \
    -DENABLE_PYTHON_INTERFACE=0 \
    -DPYTHON_EXECUTABLE="$(echo $(which python))" \
    -DLIT_TOOL="$(echo $(which lit))" \
    -DZLIB_INCLUDE_DIR="../../${INSTALL_DIR}/include" \
    -DCMAKE_INSTALL_PREFIX="../../${INSTALL_DIR}" \
    -DZLIB_LIBRARY=$(readlink -f "../../${INSTALL_DIR}/lib/libz.a") \
    -DMINISAT_LIBDIR="../../${INSTALL_DIR}/lib" \
    -DMINISAT_INCLUDE_DIR="../../${INSTALL_DIR}/include" \
    -DMINISAT_LIBRARY="../../${INSTALL_DIR}/lib/libminisat.a" \
    -DPYTHON_LIB_INSTALL_DIR="../../${INSTALL_DIR}/python"
```

which doesn't fail to build on the merge git hash (so before your changes).

I'm trying to understand what I missed so I can rectify it in the future!

**Comment by msoos** [comment]
The one that builds the binary that uses Boost :) Please see TravisCI -- it shows all the ways the system breaks :) Please unbreak our build pipeline, which should work: https://travis-ci.org/stp/stp

Thanks!

**Comment by andrewvaughanj** [comment]
@msoos are you happy that this is resolved now?

**Comment by msoos** [comment]
Sure, thanks!
