### ISSUE TITLE
error building stp - attempted static link to libcryptominisat5.so

### ISSUE THREAD

**Issue by refactormyself** [stp/stp#332]
please I get this error while building stp
```
/usr/bin/x86_64-linux-gnu-ld: attempted static link of dynamic object /usr/local/lib/libcryptominisat5.so.5.6'
collect2: error: ld returned 1 exit status
tools/stp/CMakeFiles/stp-bin.dir/build.make:124: recipe for target 'stp' failed
make[2]: *** [stp] Error 1
CMakeFiles/Makefile2:1196: recipe for target 'tools/stp/CMakeFiles/stp-bin.dir/all' failed
```

**Comment by rgov** [comment]
Hi. When you post a problem like this to any open source project, please include more details. What system is this on? What version of STP are you building? What build command are you running? How did you build and install CryptoMiniSAT?

**Comment by refactormyself** [comment]
Sorry about that.

**STP version :** current version - I just cloned the repo https://github.com/stp/stp.git
**OS:** Ubuntu
**Steps I took to build:**
1. Install dependencies
```
#  boost, flex, bison and minisat
sudo apt-get install cmake bison flex libboost-all-dev python perl minisat

# CryptoMiniSat 
git clone https://github.com/msoos/cryptominisat
cd cryptominisat
mkdir build && cd build
cmake ..
make
sudo make install
sudo ldconfig
```
2. clone and build

```
git clone https://github.com/stp/stp.git

cd stp

mkdir ./build;cd ./build
echo
echo "Now building STP ... "

# cmake .. -DCMAKE_BUILD_TYPE=Debug

# cmake -DSHAREDCOMPILE=ON ..

cmake -DSTATICCOMPILE=ON ..
make
sudo make install
sudo ldconfig

```

**Comment by rgov** [comment]
Thanks. The version of Ubuntu matters also, but I think there's enough information here.

You are building the static version of STP against the dynamic version of CryptoMiniSAT. Are you intentionally trying to build a static version of STP? If not, then do not follow those instructions, just run `cmake` with no options.

Otherwise you ALSO need to build CryptoMiniSAT with `cmake -DSTATICCOMPILE=ON ...`.

**Comment by refactormyself** [comment]
Thank you. My intention is not to build a static version of STP, I am just following the instruction. Eventually my goal will be to build a SHARED version of STP and link to it. How can I achieve this?

**Comment by rgov** [comment]
Just follow the basic instructions: https://github.com/stp/stp#build-and-install

Do not follow the part called "Building a static library and binary" because you don't want a static library.
