### ISSUE TITLE
Signals.SIGSEGV: 11     Segmentation fault

### ISSUE THREAD

**Issue by shell33** [stp/stp#334]
Hi,
When I use Python3 subprocess to process an STP file in terminal, it returns 'subprocess.CalledProcessError: Command '['stp', '--CVC', 'XX.stp']' died with <Signals.SIGSEGV: 11>'.
And when I process the STP file use 'stp --CVC XX.stp' directly in terminal, in returns 'Segmentation fault(core dump)'.
They are all in Linux.
Please tell me how to fix it. THX!

**Comment by msoos** [comment]
Hey! Thanks for the report. Please tell us what version of STP you are using and what is the `XX.stp` file that you are using so we can debug. Thanks in advance,

Mate

**Comment by shell33** [comment]
[1st.zip](https://github.com/stp/stp/files/3650222/1st.zip)
Hi,
When I process the stp file in Linux, the error will be occurred. I have 2 Linux environment, one is Ubuntu18(X64) with the STP version is 2.3.3 and the other one is Ubuntu16(X86, VMware) with the STP version is 2.1.2. Besides, there is an interesting thing that when I process the stp file in Win7(X64) with the STP version is 2.3.3, the file can be processed successfully. I can guarantee that the memory is enough. The stp file is almost 30M, so I make a ZIP file and have no password.
THX!

**Comment by rgov** [comment]
My guess is that your `flagsum` assertion is just too big, and the process of recursively evaluating the expression tree ends up exhausting the maximum stack depth.

You should split this into different assertions.

**Comment by msoos** [comment]
Ryan is most likely right :) You can also manipulate the maximum stack size
using 'ulimit' -- check it  out, it should help. Then you don't have to
split it. Run 'ulimit -h' to see the options and 'ulimit -a' to see the
current maximum stack size, which hopefully will explain the difference!
Good luck and let us know :)

**Comment by shell33** [comment]
OK! I set stack size to unlimited and process the file successfully, THX! @msoos and @rgov

**Comment by msoos** [comment]
Glad it worked! :) Closing.
