### ISSUE TITLE
CryptoMiniSat dependency unconditionally added

### ISSUE THREAD

**Issue by ccadar** [stp/stp#346]
In `STPConfig.cmake.in`, the  CryptoMiniSat dependency is unconditionally added:
```
include(CMakeFindDependencyMacro)
find_dependency(cryptominisat5)
```

This happened recently, in 2a0839f3d2a9fc577e4891dae56b90f416117312

This causes a problem when STP is built without CryptoMiniSat support, and a project includes `STPConfig.cmake` as a dependency.

In particular, KLEE does this and gets this error from CMake:
```
CMake Warning at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findcryptominisat5.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "cryptominisat5", but CMake did not find one.

  Could not find a package configuration file provided by "cryptominisat5"
  with any of the following names:

    cryptominisat5Config.cmake
    cryptominisat5-config.cmake

  Add the installation prefix of "cryptominisat5" to CMAKE_PREFIX_PATH or set
  "cryptominisat5_DIR" to a directory containing one of the above files.  If
  "cryptominisat5" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  stp/stp.git/build/STPConfig.cmake:15 (find_dependency)
  cmake/find_stp.cmake:15 (find_package)
  CMakeLists.txt:321 (include)


CMake Warning at cmake/find_stp.cmake:15 (find_package):
  Found package configuration file:

    stp/stp.git/build/STPConfig.cmake
```

Reverting that patch solves the issue, but I'm not sure how you want to handle CryptoMiniSat support.

@arrowd (as author of that patch), @msoos (as author of CryptoMiniSat), any thoughts on how to resolve this?  Thank you!

**Comment by arrowd** [comment]
Ouch, so STP itself can be built without cmsat. Then my change is wrong indeed. I'll try to come up with a patch soon.

**Comment by ccadar** [comment]
Thanks for the very quick response, @arrowd.  Indeed, it can be built w/o CryptoMiniSat, and KLEE uses it w/o by default. 
Also, note that STP has a CMake option `NOCRYPTOMINISAT` which can be used to completely disable the search for CryptoMiniSat.

While you think of the right patch, can you just revert that patch for now?  KLEE's CI fails right now because of it, and I would prefer not to disable support for mainline STP.

**Comment by msoos** [comment]
Sorry, this should now be fixed. Please let us know if it still creates some issues! Thanks,

Mate

**Comment by arrowd** [comment]
@msoos Thanks for fixing this. My internet provider had an unfortunate outage yesterday.
