### ISSUE TITLE
SMTCOMP 2020

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#349]
The draft SMTCOMP 2020 rules have been released:

https://smt-comp.github.io/2020/rules20.pdf

The big change for us is that they're asking us to limit the number of configurations we submit to 2. I read this as making it difficult for us to submit STP with a range of different SAT solvers - like we did last year?

Do others read it the same way?

Trev.

**Comment by andrewvaughanj** [comment]
Here’s the part:

> Limit the Number of Solvers. This year solver development teams may only submit more than one entry if they are substantially different. A justification must be provided for the difference. We strongly encourage the teams to keep the number of solvers per team per category at at most two.
>
> Rationale: The organizers wish to keep the total run-time of the competition small, in case of unforeseen problems that require to rerun the whole competition. The idea in allowing up to two submissions is to encourage the development of new, experimental techniques by allowing an “alternative solver” to be submitted while keeping the competition manageable.

I’m not sure it would be viable to even submit STP with two backends, as this does not even “substantially different”.

Also, if you (Trevor) are on the teams for both STP and Minkeyrink, you need to decide if they are “substantially different” enough to meet the intent of what the organisers wrote.

**Comment by andrewvaughanj** [comment]
I feel I should clarify what I wrote, as I fear it could be interpreted in a "negative way".

I'm a 100% not saying that submitting Minkeyrink and STP is "not possible", only that there is a question about the "spirit of the law" (vs. the "letter of the law") and which people are members of the "STP team" and the "Minkeyrink team".

As Minkeyrink is closed-source, I have no idea how it differs from STP. It may already differ "substantially", in which case, submission of both STP and Minkeyrink is a no-brainer.

W.r.t. the original question: my interpretation of the "spirit of the law" is that submitting the same SMT solver with differing SAT backends would not be substantially different, and also that the "alternative solver" part doesn't cover this. My interpretation of the "alternative solver" is that you might have two _widely different_ ways of handling the SMT instance (e.g., MBQI vs. e-matching) inside of one tool. Submitting that tool in MBQI-mode vs. e-matching-mode would be fine.

**Comment by msoos** [comment]
I think what we have to take into account is that many times these kinds of
rules are not really against Minkeyrink or STP. They are instead to deter
people who have been making minor changes and are not considered serious
contributors to the field. In other words, it's against abuse by parties
who are not contributing back in a significant way and only wish to profit
from the potential fame. This, I believe, cannot be said of those working
in these two projects. We have put lots of effort into these systems over
the years, and it shows: e.g. Minkeyrink is substantially different as can
be observed in performance and STP has evolved quite a bit over the years
(see e.g. Norbert Manthley's STP submission last year, using a completely
different, self-written, SAT solver). Note that this is only my personal
interpretation, given my experience with rules for the SAT Competition. We
should ask the organizers to get clarity, though.

Just my 2 cents,

Mate

**Comment by andrewvaughanj** [comment]
(I have no "skin in this game"; just an interesting topic, so you're really very welcome to ignore me here ...)

Actually, I believe that what they're trying to do is limit things like (from [2019 SMT-COMP participants](https://smt-comp.github.io/2019/participants.html)):

* 6 CVC4 versions (2 non-competing)

* 9 STP versions (2 non-competing)

* 10 Yices2 versions (0 non-competing)

**Comment by TrevorHansen** [comment]
By my reading of the rules, it's reasonable to submit 2 versions/configurations of STP to this year's competition - as long as each configuration is a bit different.

I see our options being:
1) We agree which STP configurations to submit.
2) We have our own pre-competition to decide which STP configurations to submit. 

Does anyone have a preference? I'd be happy to let Norbert choose one configuration and Mate another?

Trev.

**Comment by conp-solutions** [comment]
I agree that we should reduce the number of submissions. Using STP + Riss (or mergesat) showed in past competitions, that changing the SAT backend can result in different solver behavior, which is interesting for the portfolio approach. However, I did not change the solvers much. Hence, we do not need to repeat this public experiment.

So, going with a cryptominisat based version, as it's been the best one previously, and with a MiniSat version, would be fine with me. In case we can have parallel, cryptominisat again seem well benchmarked. The portfolio did not work very well, iirc.

Most of the submission should be scripted. I will not have time to submit this year, and am also fine with not being mentioned as author.

**Comment by msoos** [comment]
Thanks Norbert! Yes, for the portfolio I believe running with riss/mergesat as one of the solvers would be interesting. For the mainline, it seems that CMS did better.

I have worked a lot on CryptoMiniSat lately, it should be quite a bit faster... but tuning for something like SMT can sometimes be a challenge. Trevor, can you please take a look at the current "master" branch on the public CryptoMiniSat how it performs? I think it should be a lot faster.

**Comment by TrevorHansen** [comment]
Thanks @msoos , @conp-solutions 

From what you've said it seems OK to submit a single STP entry using the current master version of cryptominisat configured to use multi-threading?

Mate, you suggested submitting a riss/mergesat entry, Norbert doesn't seem keen. Norbert suggested a minisat entry. Minisat is so old now, to me it doesn't seem like a great comparison?

I'll submit just a single entry, as discussed, unless anyone's got a better plan? Final submissions are due in a couple of weeks. So there's time to tune things a little.

I've run the current master CMS with STP, 16GB memout, 1200 seconds timeout, on the updated SMTLIB. All the problems parse. We get 1675 failures, including 6 memouts. I'm running the 2019 CMS submission now. In about 3 days I'll write with the results.

**Comment by msoos** [comment]
Hi Trevor,

Let's just submit a single entry with CryptoMiniSat. I am confident it'll be fine. The "master" is okay -- please re-pull, though, I have just fixed an important bug. However, I would suggest to use the newest and greatest CryptoMiniSat, here https://github.com/meelgroup/cryptominisat/ It's private and accessible to you (@TrevorHansen ) but here is a tarball for everyone else: https://www.msoos.org/largefiles/cmsat_main_ccnr.tar.gz I will make the repo public in the coming 1-2 weeks. It's pretty damn fast, it beats CaDiCaL on SAT Race'19 by about 16 instances.

I suggest we make sure we have M4RI installed when the binary is built, but let's delete every remnant of BreakID, I am not sure the symmetry breaking is working well in a library setting -- I think I asked you to try it out last time, and it wasn't a success -- you can give it another try, though, if you like.

Would the above be OK with everyone? I am still working a bit on CryptoMiniSat, perhaps I'll be able to pull off a few other tricks, make it slightly faster. But in general I think it should be OK. In case you are interested, the main performance benefit is coming from a few things, mostly Gauss-Jordan elimination being turned on all the time, stable polarities (check CaDiCaL's SAT Race'19 description for this), a tuned branching heuristic, improved vivification/distillation, and a tight integration with CCAnr, really cool SLS solver.

Cheers,
Mate

**Comment by conp-solutions** [comment]
Single STP with CryptoMiniSat is fine with me too. Compared to last year, MergeSat improved as well, but I did not test on incremental workloads.

If you are willing to submit a single CryptoMiniSat STP, and the portfolio STP with Riss and MergeSat, that would work for me, too.

Best,
Norbert

**Comment by msoos** [comment]
Oh, sure, if we can do portfolio as well as a single-system one, then we should most certainly submit with MergeSat as one of the portfolios, and probably MiniSat as another one, too!

**Comment by TrevorHansen** [comment]
I should have been clearer, initial submissions are due tomorrow (my time). Final submission on the 18th May (two weeks later). I'll submit two configurations:

1) STP + CMS, with CMS taken from Mate's currently private branch.
2) STP + Riss & Mergesat portfolio.

So if we keep it at two configurations, there's no room for Minisat. Or is Minisat one of the portfolio solvers? We don't need to resolve it until final submissions though..

I'll submit initial versions tomorrow. I'll write with updates.

**Comment by msoos** [comment]
Yeah, these 2 are perfect! And yes, we still have some time to do some performance tuning :) And yes, no need for MiniSat on its own. It can be part of the portfolio, though, as a 3rd solver, but perhaps that's not very useful. Thanks for taking care of tomorrow's deadline!

**Comment by TrevorHansen** [comment]
Ok. I've submitted two STP entries to SMTCOMP 2020. One is STP + MergeSAT, the other STP + CMS. Just placeholders that I'll replace before the final deadline. I hope that's what everyone expected.

In two days' time I'll send through some plans for performance tuning. It seems to me that there's lots we could do in the next 2 weeks to squeeze out some extra performance.

**Comment by msoos** [comment]
Thanks, sounds great!

Mate

**Comment by TrevorHansen** [comment]
Hi @msoos,

The version output from the dynamically compiled private-CMS is below.
* Have I used the flags you're expecting?
* Do you have a preference for which version of gcc/clang I use?

Thanks

```
c BreakID not compiled in, disabling
c CryptoMiniSat version 5.7.0
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision c0e218c38df58a4ef3a82a81587612ac13a1bf92
c CMS is GPL licensed due to M4RI being linked. Build without M4RI to get MIT version
c Using VMTF code by Armin Biere from CaDiCaL
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fno-stack-protector -fvisibility=hidden -Wlogical-op -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DUSE_GAUSS -DNDEBUG -D_FORTIFY_SOURCE=0 -DBOOST_TEST_DYN_LINK -DUSE_SQLITE3 -DYALSAT_FPU -DUSE_M4RI -DUSE_MPI | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND = TRUE | ZLIB_FOUND =  | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND = TRUE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = OFF | PYTHON_EXECUTABLE = /usr/bin/python3 | PYTHON_LIBRARY = /usr/lib/x86_64-linux-gnu/libpython3.6m.so | PYTHON_INCLUDE_DIRS = /usr/include/python3.6m | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = May  6 2020 17:32:39
c CMS compiled with gcc version 5.5.0 20171010
```

**Comment by TrevorHansen** [comment]
There's been an extension the SMTCOMP 20, now final submissions are due 25-May. So there's about a day to get everything sorted.

It's looking good so far, the new CMS is faster than last years, and I've had the chance to make some tweaks. Using a 1200 second timeout and 16GiB memory out,  we solve about 1000 more of the 41,713 problems than last year's entry does. It leaves us with about 550 problems we can't solve in the available time/memory

Just a few things:
* @msoos, is the best version of https://github.com/meelgroup/cryptominisat/ to use the head? Also, currently I'm compiling with gcc 5.5.0. My machine has gcc 5 through 10, and clang 6 through 9. Do you have a preference for which we compile with?

* @conp-solutions , I entered STP + MergeSAT into "model validation" and "incremental" before I realised that MergeSAT is scripted. So it seems like I should withdraw from those divisions? 

* I've started work on the description. I plan on including everyone's name who submitted patches in the last year. I'm not finished going through them yet! Given how late I've left it, if anyone has feedback for me now, it'd be great to hear it soon. The description is here:
https://github.com/stp/docs/blob/master/smt2020-descr/descr.pdf

**Comment by msoos** [comment]
Hi,

First of all, thank you so much for your work!

Please don't use the HEAD. Please just use the one that you tested on -- I lately have been adding things and they are _not_ tested so they may crash, bug out, etc. Please just use the one that you already tested and is faster! Taking the HEAD now would be dangerous -- when I asked you to do it it was pretty stable :)

I have no preference for compilers in general, but usually the newer the better :) I always use gcc so I don't know how it performs on clang.

My description for SAT Comp 2020 is here: https://github.com/meelgroup/cryptominisat/tree/devel/docs/satcomp20-pdf/ccanr Apart from BreakID, it's correct (BreakID is not compiled in to your version and that's OK). Note that Gauss-Jordan elimination is now enabled by default, though it does turn off automatically if it's not useful.

Thank you so much for your work and let me know if I can help,

Mate

PS: Maybe for next year we can experiment with BreakID but it's almost certainly a bad idea right now. Next year :)

**Comment by conp-solutions** [comment]
MergeSat is scripted, that is correct, mainly because it was not capable of incremental solving last year. That changed by now. I will see whether I can manage a PR that integrates it properly. If I do not, or that PR is not merged in time, this combination has to be removed from those tracks.

Wrt CryptoMiniSat versions to use, should STP use git submodules to work around that problem? While that brings maintenance effort, as the submodule needs to be bumped once in a while, it would be always clear which version of CryptoMiniSat belongs to a given STP version, based on git commit IDs.

**Comment by msoos** [comment]
Sure, using submodules sound good. But let's not do it right now, as the revision that is being submitted is not yet public. I'll let you know when I release, should be soon :)
Thanks again everyone for all,

Mate

**Comment by andrewvaughanj** [comment]
(such a minor nit, but if you're thanking me---and it is very much appreciated !!!---can you please use "Andrew V. Jones"?)

**Comment by conp-solutions** [comment]
It looks like I can make STP use MergeSat instead of MiniSat (with all the ugly consequences, essentially replacing the Minisat namespace everywhere) to form a statically compiled binary.

When is the latest point in time (in UTC ;) ) at which you'd consider using such a version instead of what we currently have?

Best,
Norbert

**Comment by conp-solutions** [comment]
I created a PR with the changes to build with MergeSat, but did not test yet: https://github.com/stp/stp/pull/354

**Comment by TrevorHansen** [comment]
Hi @conp-solutions, nice work. I'd like to submit our final version in 14 hours' time.  That's not the final deadline though, just when I run out of time! Trev.

**Comment by TrevorHansen** [comment]
I've updated the system description:

https://github.com/stp/docs/blob/master/smt2020-descr/descr.pdf

I looked through the commit messages for the last year, and tried to include everyone. I'm sure I've done a bad job of it, though. If anyone wants to take over and add missing contributors, or order peoples' names by contribution, it's good with me.

@msoos  - our submissions will be compiled by GCC 5.5.0.  I've run out of time to test with other compilers. Next year! I've submitted with c0e218c38df58a4ef3a82a81587612ac13a1bf92

@conp-solutions. I'm about to start working on the MergeSAT submission. I'll let you know how it goes.

**Comment by TrevorHansen** [comment]
Hi @conp-solutions 

I've tried buillding STP with mergesat. But when I try to build in your branch, I get a missing file error. 

```
Scanning dependencies of target ASTKind_header
[  1%] Generating ASTKind.cpp, ../../include/stp/AST/ASTKind.h
[  1%] Built target ASTKind_header
Scanning dependencies of target util
[  2%] Building CXX object lib/Util/CMakeFiles/util.dir/GitSHA1.cpp.o
[  3%] Building CXX object lib/Util/CMakeFiles/util.dir/RunTimes.cpp.o
In file included from /home/thansen/solvers/stp/lib/Util/RunTimes.cpp:35:0:
/usr/local/include/minisat/utils/System.h:28:26: fatal error: mtl/IntTypes.h: No such file or directory
compilation terminated.
lib/Util/CMakeFiles/util.dir/build.make:86: recipe for target 'lib/Util/CMakeFiles/util.dir/RunTimes.cpp.o' failed
make[2]: *** [lib/Util/CMakeFiles/util.dir/RunTimes.cpp.o] Error 1
CMakeFiles/Makefile2:1120: recipe for target 'lib/Util/CMakeFiles/util.dir/all' failed
make[1]: *** [lib/Util/CMakeFiles/util.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Instead I've built STP and Mergesat separately and have a submission ready for those. In that case we'd need to withdraw from model-verification & incremental.

We've got maybe 12 hours until the deadline. Does it seem easy to fix? Or can you provide me with a binary?

Trev.

**Comment by conp-solutions** [comment]
[stp_simple.gz](https://github.com/stp/stp/files/4678168/stp_simple.gz)

**Comment by conp-solutions** [comment]
This is what I compiled on my system right now.

Otherwise, feel free to not submit to the 2 extra tracks and just use the scripted variant.

**Comment by TrevorHansen** [comment]
Hi @conp-solutions, thanks for the build! I've submitted just now.

I haven't used the simple build before. I didn't see how to configure the thread count? So I submitted a single threaded version. I don't know if it's what you intended, but either way it'll give us a better chance to place highly in the separate parallel/single threaded competitions.

In case you want to change it for later, when I tested quickly I got some message like "c Switcing to VSIDS"

**Comment by TrevorHansen** [comment]
Hi Norbert, There's been an extension to the SMTCOMP deadline for 22 more hours. That is, until Tuesday, May 26, 23.59 anywhere on earth. 

I've run some more tests on the mergesat binary and it doesn't seem like it's using a recent STP version.  cd4a4898697a7ff873290ce2cecf0e023403d24e introduced some changes that solve about 60 extra problems (that is using CMS it fails on 490 rather than 550 problems.) 

So if you want to, we've got time submit STP + MergeSAT using a newer version?

**Comment by conp-solutions** [comment]
Sure, i can (modulo rebase conflicts) generate a new binary in the next 3 hours. Not sure why i did not use origin head.To make sure i do the right thing, can you post a commit id i should use?Best,Norbert

**Comment by TrevorHansen** [comment]
Hi Norbert,

Ideally the MergeSAT submission will be based on
cd4a4898697a7ff873290ce2cecf0e023403d24e Apologies if I've messed up and
the binary does include that commit.

Trev.

**Comment by conp-solutions** [comment]
[stp_simple-3eeedda6.gz](https://github.com/stp/stp/files/4683074/stp_simple-3eeedda6.gz)

**Comment by conp-solutions** [comment]
The binary I just uploaded has been created using the mentioned commit. The current history is:

```
git log --decorate --pretty=oneline --graph mergesat
* 3eeedda62322a8a2dc57458f7e9d86524a098f52 (HEAD -> mergesat, conp-solutions/mergesat) travis: do use a recent mergesat commit
* adc14b68a387b0e45620da5abd05e7349bc04dc2 travis: add building with mergesat
* 8e4ff44e5bb3dac529b916918590b797721c9680 namespace: make Minisat definable
* 97d019ad4c2c1dc687b67645e8509102da1533e1 build: teach cmake how to build with mergesat
* 04b9b0b82b85c878774213bbb9e0fecae340a4e8 mergesat: teach STP about new solver
* 13df8e3e2196ce2288973acccb9ae8c4cadc34b1 mergesat: add glue code
* 37b0c72440a65bfbc559492a8aafa2d482d79a5b (origin/master) Remove binaries. Have put them in a release instead.
* ac1b92b181c293a00360a028857cb76a6cc8b191 (tag: smtcomp2020) initial smtcomp 2020 mergesat.
```

**Comment by TrevorHansen** [comment]
Thanks Norbert, I've submitted just now. We'll find out on July 5th/6th how we went. 

I submitted three solvers:
STP + CMS, to QF_BV single query track, model validation, and incremental.
STP + MergeSAT to QF_BV single query track, model validation, and incremental.
MinkeyRink Solver (my own solver) to QF_BV single query track.

I think they're good solvers and with only a little bit of luck we should place well. 

I found writing the system description the hardest. So much happens, especially to the build system, that I don't understand the details of, so apologies again to those that I've shortchanged! You know who you are.

**Comment by TrevorHansen** [comment]
An update. I just heard from the organisers that STP + MergeSAT doesn't work properly in the incremental track. It's not flushing output like it needs to. 

The problem is that when I hid the comments, I did it like this:
"$SOLVERDIR"/stp "$1" | grep  -v ^c
when it should be:
"$SOLVERDIR"/stp "$1" | grep --line-buffered -v ^c

I didn't realise that grep buffers output when it's not writing to a console. Lesson learned. 

Sorry Norbert!

Trev.

**Comment by conp-solutions** [comment]
No worries. I have to say thanks for all the effort -- thanks. I guess we could rerun after the competition, no?Is there a script that has to be handed in, which could be added to the repository to codify the learned lesson?Best,Norbert

**Comment by TrevorHansen** [comment]
The incremental & model-validation jobs for SMTCOMP 2020 have finished running:
https://smt-comp.github.io/2020/news/2020-05-29

The single query is still going. 

There are so many tracks I imagine we'll place highly in some of them.

**Comment by TrevorHansen** [comment]
SMTCOMP 2020 results are out:

https://smt-comp.github.io/2020/results/qf-bv-incremental
https://smt-comp.github.io/2020/results/qf-bv-single-query

All reasonable results in the top half. Nice work everyone!

**Comment by conp-solutions** [comment]
I really like the MergeSat results. Sorry for the bug wrt switching decision heuristics in a wrong way. If you build with MergeSat today, it will be fixed.Best,Norbert
