### ISSUE TITLE
Move to C++14.

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#355]
I've changed cmake to require C++14, and updated TravisCI to use Ubuntu 18 -  which installs with C++14 compilers. 

Is using C++14 going to be a problem for anyone?

Perhaps it's a good time to move to C++17?

**Comment by msoos** [comment]
Hey,

Beware, in my experience trying to move to C++11, it can be early. There
may be many users who will be annoyed and surprised. Many compilers still
don't implement that standard. MSVC for example -- usually they are
many-many years behind. Are there some cool/good reason for moving to it?
It'd be good to know what the gains are before we take on the downsides :)

Just my 2 cents,

Mate

**Comment by andrewvaughanj** [comment]
For me (an "industrial user" of STP), I don't think moving to C++14 or C++17 should be a problem.

I'll need to check, but I believe we're using MinGW 8.3 and MinGW 9.2 (but a custom build that links against the UCRT, rather than a stock MinGW).

**Comment by TrevorHansen** [comment]
Thanks Mate, Andrew,

I moved to C++14 because it introduced std::make_unique which I find
helpful.

If C++14 is trouble for people, I'm happy to go back to C++11. But I don't
want to stick on old c++ standards for no reason.

Unless anyone has a better plan, maybe stick with c++14, but not use many
of its features. If not much breaks after a couple of months, I'll bump up
to c++17. Otherwise, revert back to c++11?

Trev.

**Comment by msoos** [comment]
Hi,

Wait :) I thought we were talking about C++14. Now it's 17. What do you
need from 17? Also, how many compilers support that? Have you checked MSVC?
Sorry but you were talking about 14, that's what the title says, too. Let's
stick to 14 unless necessary.

I have a modern compiler. But e.g. Statexec does not. I'm pretty sure STP
would not build on Statexec with C++14. With 17 it certainly would not, and
I'm sure many people will be having trouble. Do you really need 17? What
features would you use of 17?

Sorry for sounding like a parrot but it was hard to move to 11, I remember
the time. I want to avoid all that frustration if possible.

Just my 2 cents,

Mate

**Comment by andrewvaughanj** [comment]
AFAIUI MSVC 2019 is pretty good for C++17: 

- https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B17_core_language_features

- [19.20 == the first release of Visual Studio 2019 compiler](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B)


In the non-SMT parts of my work, I've worked heavily with checking MSVC's support for C++17 (well, cross checking C++17 with MSVC + EDG in MSVC mode).

**Comment by andrewvaughanj** [comment]
That's not me saying "ADOPT ALL THE C++17", that's me saying "if STP states we only support compilation with GCC >7 and MSVC > 1920, then adopting C++17 should be fine".

**Comment by TrevorHansen** [comment]
Thanks for the points. To spell out what's happened.

In d4783f98974b4d60b5ae75574e0db2db25f0c02f I wanted to make some initialisations less bad. To use the syntax I wanted to use, I needed c++14, so I changed STP from requiring c++11 to requiring c++14. 

After some changes to the TravisCI config (02b805fc2b15c5696d156cf2e7ff8835cfc539a0, 875916889b135cf739af9857ee341034eea20ed3)  it seems to build OK.

The AppVeyor Visual Studio 2015 build with  MSVC 19.0.24241.7 seems to build OK, too.

If people are using STP on machines that don't have compiler support for c++14, I'm OK to move back to requiring c++11.  

@msoos, I haven't used statexec - is it useful if STP compiles on it? If so, as mentioned, we can move back to c++11.

So far moving to c++14 seems to have been easy? But I appreciate not everyone will have tried the c++14 version.

I'll not use many c++14 features for the next couple of months in case we need to revert back.

We can hold off discussing c++17 for now.

**Comment by msoos** [comment]
Cool, let me close, I think we reached a consensus :)

Thanks for the discussion, and sorry for pushing back so much. I have a few painful memories from trying to move to C++11 and having massive issues with compilers, especially on Windows and on computing clusters.

Thanks again for the discussion,

Mate
