### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by HugeChaos** [stp/stp#356]
hi, I have a problem that I cannot solve.
When I call stp, it returns 

terminate called after throwing an instance of 'Minisat::OutOfMemoryException'
Aborted (core dumped)

what should I do? 
Thank you.

**Comment by andrewvaughanj** [comment]
At a first glance, this is probably an issue for where there is no solution, as it is related to how much RAM your instance requires.

That being said, some questions:

- Are you using a `.smt2` file, or are you using STP's API?

- Can you provide any information on the instance you are trying to solve?

- What options did you choose when building STP? Could you try building it with an alternative SAT solver (e.g., CryptoMiniSat)?

If we know about more about how you're using STP, it is possible we can make some suggestions as to ways you might be able to avoid this issue.

**Comment by HugeChaos** [comment]
When I use the statement in the puycharm:

res = commands.getoutput("stp --minisat --CVC " + solve_file)
it returns 

terminate called after throwing an instance of 'Minisat::OutOfMemoryException'
Aborted (core dumped)

When I use the statement in pycharm:
res = commands.getoutput("stp --cryptominisat --CVC " + solve_file)
it returns

ERROR: memory manager can't handle the load size: 1073721645 needed: 131085 newcapacity: 1073741823
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by andrewvaughanj** [comment]
Okay, so it has used ~1.07 GiB of RAM and then bombs out.

How much RAM do you have? Can you share your `solve_file`?

Given you're using the `--CVC` option: does this example work with CVC4?

**Comment by HugeChaos** [comment]
I have  14GiB of RAM.
Sorry, I cannot share my solve_file. 
Very thanks for your answer.

**Comment by andrewvaughanj** [comment]
Before STP dies, how much RAM does it report using? 1.07 GiB or more than that? There's no chance you've built a 32-bit STP is there?

**Comment by msoos** [comment]
I suggest you try using the CryptoMiniSat backend. If complied in a special way, it can support up to a few petabytes of RAM. Default should allow for about 4GB. If you find that short, you can use `-DLARGEMEM=ON` as an option to `cmake`. But you almost surely won't need it.

Just my 2 cents,

Mate
