### ISSUE TITLE
How to balance "timeout_max_conflicts" and "timeout_max_time" in vc_query_with_timeout

### ISSUE THREAD

**Issue by Flians** [stp/stp#362]
I wanna use vc_query_with_timeout to execute the Expr. 
And I dont know the relationship between "timeout_max_conflicts" and "timeout_max_time".
I looked the file [timeout.cpp](https://github.com/stp/stp/blob/master/tests/api/C/timeout.cpp).
```
    int limit = // time is in seconds
        rand() %
        max_value; // FIXME: non-determinsitc behaviour in a test case is BAD!!!
    std::string timeout_type;
    uint32_t max_conflicts = -1;
    uint32_t max_time = -1;
    if (test_with_time)
    {
      timeout_type = "Time ";
      limit = std::max(limit, 1); // we do not want a 0 timeout
      max_time = limit;
    }
    else
    {
      timeout_type = "Conflicts";
      max_conflicts = limit;
    }
    std::cout << timeout_type << " : " << limit << " : result " << std::flush;

    // returns 3 on timeout
    int query = vc_query_with_timeout(vc, vc_falseExpr(vc), max_conflicts, max_time);
    ASSERT_TRUE(query == 3);
```
It seems that "timeout_max_conflicts" and "timeout_max_time" can only be used one at a time.

**Comment by andrewvaughanj** [comment]
Just to check: how have you configured STP? I just looked over the code and the time-based timeout mechanism is only supported with CryptoMiniSat.

@msoos would know this for sure, but it is my understanding that you (for CMS) _can_ you both simultaneously and it is the first one that "expires" that stops the solver; [indeed](https://github.com/msoos/cryptominisat/blob/master/src/solver.cpp#L1851):

```
    while (status == l_Undef
        && !must_interrupt_asap()
        && cpuTime() < conf.maxTime
        && sumConflicts < (uint64_t)conf.max_confl
    ) {
```

**Comment by Flians** [comment]
I configure as follows: 
```
this->handle = vc_createValidityChecker();
vc_useCryptominisat(this->handle);
vc_query_with_timeout(this->handle, queryExpr, max_conflicts, timeout);
```

**Comment by andrewvaughanj** [comment]
Yep! Seems about right!

**Comment by Flians** [comment]
In addition, I compile the cryptominisat5 as the static library and install it in Debian 10.
When I compile the stp as the static library, there are the following errors:
```
In file included from /home/flynn/stp/stp/include/stp/Sat/SATSolver.h:28,
                 from /home/flynn/stp/stp/include/stp/Sat/CryptoMinisat5.h:31,
                 from /home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:25:
/usr/local/include/cryptominisat5/solvertypesmini.h:33:20: error: expected unqualified-id before ‘-’ token
 constexpr uint32_t var_Undef(0xffffffffU >> 4);
                    ^~~~~~~~~
/usr/local/include/cryptominisat5/solvertypesmini.h:33:20: error: expected ‘)’ before ‘-’ token
/usr/local/include/cryptominisat5/solvertypesmini.h:155:17: error: expected ‘)’ before ‘(’ token
 constexpr lbool l_True = lbool((uint8_t)0);
                 ^~~~~~
/usr/local/include/cryptominisat5/solvertypesmini.h:156:17: error: expected ‘)’ before ‘(’ token
 constexpr lbool l_False = lbool((uint8_t)1);
                 ^~~~~~~
/usr/local/include/cryptominisat5/solvertypesmini.h:157:17: error: expected ‘)’ before ‘(’ token
 constexpr lbool l_Undef = lbool((uint8_t)2);
                 ^~~~~~~
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp: In member function ‘virtual bool stp::CryptoMiniSat5::solve(bool&)’:
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:108:21: error: expected unqualified-id before ‘(’ token
   if (ret == CMSat::l_Undef)
                     ^~~~~~~
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:112:24: error: expected unqualified-id before ‘(’ token
   return ret == CMSat::l_True;
                        ^~~~~~
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp: In member function ‘virtual uint8_t stp::CryptoMiniSat5::modelValue(uint32_t) const’:
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:117:42: error: expected unqualified-id before ‘(’ token
   return (s->get_model().at(x) == CMSat::l_True);
                                          ^~~~~~
In file included from /usr/include/c++/8/cassert:44,
                 from /usr/local/include/cryptominisat5/solvertypesmini.h:28,
                 from /usr/local/include/cryptominisat5/cryptominisat.h:35,
                 from /home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:26:
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp: In member function ‘uint32_t stp::CryptoMiniSat5::getFixedCountWithAssumptions(const stp::SATSolver::vec_literals&, const std::unordered_set<unsigned int>&)’:
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:186:19: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
   assert(assigned >= assumps.size());
          ~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/flynn/stp/stp/lib/Sat/CryptoMinisat5.cpp:188:17: error: expected unqualified-id before ‘(’ token
   assert(CMSat::l_False != r); // always satisfiable.
                 ^~~~~~~
make[2]: *** [lib/Sat/CMakeFiles/sat.dir/build.make:89: lib/Sat/CMakeFiles/sat.dir/CryptoMinisat5.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1075: lib/Sat/CMakeFiles/sat.dir/all] Error 2
```

**Comment by Flians** [comment]
@andrewvaughanj 
Yeah, I know how to use vc_query_with_timeout. But I dont know what max_conflicts is and how much it should be set.

**Comment by andrewvaughanj** [comment]
> I dont know what max_conflicts is and how much it should be set

https://en.wikipedia.org/wiki/Conflict-driven_clause_learning

We cannot tell you what value to use here; it is very domain specific to the problem you are encoding.

> When I compile the stp as the static library, 

Are you saying you _only_ get those if you try to compile statically? Or if you compile any version of STP with CMS enabled?

**Comment by andrewvaughanj** [comment]
For everyone's else's benefit, @Flians asked a lot on the Z3 GH about linking statically:

- https://github.com/Z3Prover/z3/issues/4554

- https://github.com/Z3Prover/z3/issues/4574

and we didn't have a satisfying conclusion (because Z3 needs pthread and linking pthread statically leads to disaster).

**Comment by Flians** [comment]
> For everyone's else's benefit, @Flians asked a lot on the Z3 GH about linking statically:
> 
> * [Z3Prover/z3#4554](https://github.com/Z3Prover/z3/issues/4554)
> * [Z3Prover/z3#4574](https://github.com/Z3Prover/z3/issues/4574)
> 
> and we didn't have a satisfying conclusion (because Z3 needs pthread and linking pthread statically leads to disaster).

What does it mean？Is this wrong? Does this cause you any trouble? If so, I am really sorry for this.

I know that Z3 requires pthread. So I tried other solvers.
I noticed the stp didnt need pthread. So I wanna try it.

I compiled the cryptominisat using the following command:
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DSTATICCOMPILE=ON  ..`
I compiled the stp using the following command:
`cmake -DCMAKE_INSTALL_PREFIX=../install -DSTATICCOMPILE=ON  ..`

**Comment by andrewvaughanj** [comment]
No! No issues at all — your enthusiasm to work with these solvers is great!!! I’m just letting the rest of the STP team know we’ve had issues statically linking, and it is important they know of all the work we did on the Z3 issue list 😄 

Are you able to compile STP without making it static? Your compile issue suggests you can’t compile STP *at all* (either static or non static).

**Comment by Flians** [comment]
Thank you.
I want to use the solver to achieve the equivalence check of some special circuits.
But I don't know much about solvers, so I made a lot of low-level mistakes.
Thank you very much again.

For this compilation problem, it is also mentioned in [this](https://github.com/stp/stp/issues/172#issue-68141651). It seems that the version is incompatible

**Comment by andrewvaughanj** [comment]
What operating system are you using (as specific as possible) and what compiler/version?

**Comment by Flians** [comment]
The OS is Debian 10.4.0
The version of GCC is 8.3.0

**Comment by andrewvaughanj** [comment]
Hmm, well, I just build STP with CMS using 8.3.1 (on CentOS 8) with no issues.

Have you installed CMS using Debian's package manager, or only from source?

**Comment by Flians** [comment]
No, I downloaded the source code of cryptominisat5 and compiled it as a static library. Then I downloaded the source code of stp, and an error occurred when compiling it to a static library.

**Comment by andrewvaughanj** [comment]
Okay, well, I'm out of ideas -- you could try and make the changes in this commit https://github.com/stp/stp/commit/42a42a63c7f66bc0c185bceff1f475644e4a3d24 against the CMS parts of STP (rather than the MiniSat parts).

I cannot reproduce this issue, so it doesn't make sense for me to do the work (because I cannot validate if I've fixed anything).

**Comment by Flians** [comment]
Thank you.
I have solved this problem.
I think this is a problem with the cryptominisat header file. 
I use the include files compiled under mac to replace the include under debian.
The stp can be compiled normally.
