### ISSUE TITLE
Make perl required in cmake file

### ISSUE THREAD

**Issue by roptat** [stp/stp#380]
Hi, I know this is a weird issue, but I forgot to add perl to my build environment. Despite that, cmake passed with no error, but the Makefile aborted with "PERL_EXECUTABLE-NOTFOUND: command not found". It would be great to make perl required in the cmake (so the error appears earlier). That was with 2.3.3.

**Comment by andrewvaughanj** [comment]
Seems very reasonable; I can take a look at this.

**Comment by rgov** [comment]
Alternative: Remove dependence on perl altogether. It's just [a handful of scripts](https://github.com/search?q=repo%3Astp%2Fstp+language%3APerl&type=Code&ref=advsearch&l=Perl&l=). None of them is *particularly* complicated though `genkinds.pl` seems the most so.

**Comment by andrewvaughanj** [comment]
Yeah, when I saw it was `genkinds`, I was like: "this is a bigger change than just checking for `perl` while `cmake` is running"

**Comment by msoos** [comment]
Let me know if the change fixed it :)

Cheers,

Mate
