### ISSUE TITLE
Performance issue on QF_BV formula

### ISSUE THREAD

**Issue by rainoftime** [stp/stp#381]
Hi, for the following formula
~~~~
(set-logic QF_BV)
(declare-const bv_40-0 (_ BitVec 40))
(assert (bvugt (bvurem ((_ rotate_right 6) bv_40-0) bv_40-0) bv_40-0))
(check-sat)
~~~~
stp 101aee2a
~~~~
time ./yices_smt2 x.smt2
unsat
real    0m0.258s
user    0m0.253s
sys     0m0.005s

 time ./cvc4 x.smt2 
unsat
real    0m0.010s
user    0m0.008s
sys     0m0.000s

./stp --max_time 300 x.smt2
Timed out
~~~~

**Comment by rainoftime** [comment]
A fix suggested by CVC4
https://github.com/CVC4/CVC4/pull/4993
which adds a new rule `(bvugt (bvurem T x) x) ==> (ite (= x 0) (bvugt T 0) false)`

**Comment by andrewvaughanj** [comment]
Yep; I saw this when the change was made for CVC4. The rewrite is, indeed, correct (you either have a divide by zero, or the remainder isn't possible).
