### ISSUE TITLE
Incorrect function look-up with scopes

### ISSUE THREAD

**Issue by andrewvaughanj** [stp/stp#385]
[As reported by](https://github.com/stp/stp/commit/54416cc6f086163d1b5147e3e6db7897496c4848#commitcomment-43571894) @hailinzeng:

```
;t.smt2
(set-logic QF_ABV)
(define-fun |a| () Bool true)
(assert |a|)
(push 1)
(check-sat)
(pop 1)
```

Gives:

```
sat
Fatal Error: Trying to apply function which has not been defined.
STP Error: Trying to apply function which has not been defined.
```

Before the merge for function scopes, this does not give these errors.

**Comment by hailinzeng** [comment]
I noticed that ~SolverFrame was called multiple times.

**Comment by andrewvaughanj** [comment]
I haven't dug into it (yet), but I would expect there two be at least two frames: one for the implicit "zeroth" frame, and one for your push. Functions declared in frame `n` should be "visible" in `n+1` (but clearly something is wrong!).

**Comment by andrewvaughanj** [comment]
@hailinzeng can you take a look at https://github.com/stp/stp/pull/387 and tell me if this fixes your issue?

I added your original file as a new unit test -- so thank you for providing that!

**Comment by hailinzeng** [comment]
The pull request fixed my issue. Thanks! @andrewvaughanj
