### ISSUE TITLE
Performance issue solving some QF_AUFBV queries

### ISSUE THREAD

**Issue by MartinNowack** [stp/stp#389]
I recently came across some queries that the most recent STP release takes too long to solve (I aborted after 15min).
Z3 solves them to `unsat` in a sub-second range. Any idea what could cause that or how to workaround it?

```
(set-option :produce-models true)
(set-logic QF_AUFBV )
(declare-fun int_0 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun int_1 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert (let ( (?B1 (concat  (select  int_1 (_ bv3 32) ) (concat  (select  int_1 (_ bv2 32) ) (concat  (select  int_1 (_ bv1 32) ) (select  int_1 (_ bv0 32) ) ) ) ) ) (?B2 (concat  (select  int_0 (_ bv3 32) ) (concat  (select  int_0 (_ bv2 32) ) (concat  (select  int_0 (_ bv1 32) ) (select  int_0 (_ bv0 32) ) ) ) ) ) ) (let ( (?B4 ((_ sign_extend 32)  ?B2 ) ) (?B3 ((_ sign_extend 32)  ?B1 ) ) ) (let ( (?B6 (bvsub  ?B4 ?B3 ) ) (?B7 (bvmul  ?B3 ?B4 ) ) (?B5 (bvmul  ?B3 ?B3 ) ) ) (let ( (?B8 (bvsub  ?B6 ?B3 ) ) ) (and  (and  (and  (and  (and  (and  (and  (and  (=  false (=  (bvsub  (bvadd  (bvmul  (_ bv18446744073709551614 64) ?B5 ) ?B7 ) (bvadd  (bvadd  (bvmul  ?B8 ?B3 ) ?B4 ) (bvmul  (_ bv18446744073709551614 64) ?B3 ) ) ) (bvsub  (_ bv0 64) ?B8 ) ) ) (bvslt  (_ bv0 32) ?B2 ) ) (bvslt  (_ bv0 32) ?B1 ) ) (bvslt  ?B7 (_ bv2147483647 64) ) ) (bvult  ?B5 (_ bv2147483647 64) ) ) (=  false (bvslt  ?B4 ?B3 ) ) ) (=  false (bvslt  ?B6 ?B3 ) ) ) (bvslt  ?B8 ?B3 ) ) (=  false (=  (_ bv0 64) ?B8 ) ) ) ) ) ) ) )
(check-sat)
```

Thanks a lot in advance!

**Comment by andrewvaughanj** [comment]
> most recent STP release takes too long to solve
>

Not asked sarcastically: are you saying an older version _isn't_ slow?

I quickly tried this with Boolector, and it also wasn't quick. My guess here is that Z3 is doing some clever preprocessing (probably before bit blasting) -- CVC4 solves it "in a few seconds".

Boolector says that there is `30206 CNF vars, 90594 CNF clauses`; STP's dumped DIMACS has `p cnf 13300 55978` (so `13300` vars + `55978` clauses).

I threw that DIMACS at CMS and it also didn't finish quickly.

I can take a look at this and see what I can find, but this might not be an easy thing to add to STP's approach.

**Comment by MartinNowack** [comment]
@andrewvaughanj Thanks for your quick answer!
:D I just tried with two versions of STP and one of it the newest released version, in the sense of also happens with the newest version.
Thanks for the great evaluation. So it's not me just doing something wrong - good to know.

**Comment by andrewvaughanj** [comment]
This probably doesn't entirely help, but running it through CVC4 in verbose mode, I got CVC4's preprocessed file ...

```
(set-option :produce-models true)
(set-logic QF_AUFBV )
(declare-fun int_0 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(declare-fun int_1 () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert (let ((_let_0 (select int_1 #b00000000000000000000000000000011))) (let ((_let_1 (select int_1 #b00000000000000000000000000000010))) (let ((_let_2 (select int_1 #b00000000000000000000000000000001))) (let ((_let_3 (select int_1 #b00000000000000000000000000000000))) (let ((_let_4 (select int_0 #b00000000000000000000000000000011))) (let ((_let_5 (select int_0 #b00000000000000000000000000000010))) (let ((_let_6 (select int_0 #b00000000000000000000000000000001))) (let ((_let_7 (select int_0 #b00000000000000000000000000000000))) (let ((_let_8 ((_ sign_extend 32) (concat _let_4 (concat _let_5 (concat _let_6 _let_7)))))) (let ((_let_9 ((_ sign_extend 32) (concat _let_0 (concat _let_1 (concat _let_2 _let_3)))))) (let ((_let_10 ((_ extract 62 0) (bvneg _let_9)))) (let ((_let_11 (concat _let_10 #b0))) (let ((_let_12 (bvadd _let_8 _let_11))) (let ((_let_13 (bvmul _let_9 _let_9))) (and (bvslt _let_12 _let_9) (bvult _let_13 #b0000000000000000000000000000000001111111111111111111111111111111) (bvslt (bvmul _let_8 _let_9) #b0000000000000000000000000000000001111111111111111111111111111111) (bvslt #b00000000000000000000000000000000 (concat _let_0 (concat _let_1 (concat _let_2 _let_3)))) (bvslt #b00000000000000000000000000000000 (concat _let_4 (concat _let_5 (concat _let_6 _let_7)))) (not (= _let_12 #b0000000000000000000000000000000000000000000000000000000000000000)) (not (bvslt (bvadd _let_8 (bvneg _let_9)) _let_9)) (not (bvslt _let_8 _let_9)) (not (= (bvadd _let_11 (bvadd (bvmul _let_9 _let_11) (concat ((_ sign_extend 31) (concat _let_0 (concat _let_1 (concat _let_2 _let_3)))) #b0))) (concat ((_ extract 62 0) (bvneg _let_13)) #b0)))))))))))))))))))
(check-sat)
```

STP gives `unsat` on this after 31.08 seconds.

However, I am not certain that these are equisatisfiable, but it is a finding at least.

**Comment by andrewvaughanj** [comment]
Okay, asserting both your original formula and the CVC4 rewritten one are the same gives `sat` (for both STP and CVC4).

I can see if we can optimise STP to do some similar rewrites to CVC4.

**Comment by andrewvaughanj** [comment]
Late night mistake, but same outcome: I was supposed to do `distinct` and check for `unsat` (vs. `=` and check for `sat`) ... importantly, we do get `unsat` as well.

**Comment by TrevorHansen** [comment]
When I checked with 7be1a8de31a0b5a59ee69dde2646815768c422c3 just now, STP solves this in about 10ms. So this has been inadvertently* resolved.  

* apologies if someone has fixed this but not closed the case!
*
