### ISSUE TITLE
How to get the length of type?

### ISSUE THREAD

**Issue by mikhailramalho** [stp/stp#390]
Hi,

Is there a way to get the length of a `Type` using the C interface?

I found `DLL_PUBLIC int getBVLength(Expr e);` and `DLL_PUBLIC int vc_getBVLength(VC vc, Expr e);` in `c_interface.h` but they only accept `Expr`s.

**Comment by rgov** [comment]
The C interface is pretty limited and users often find they need to extend it. If you'd like to contribute something like this, I think it would likely be accepted.

For bitvector types, could you use `vc_varExpr` to create a dummy `Expr` and then get its length?

**Comment by andrewvaughanj** [comment]
I think this is slightly more problematic than @rgov may have suggested ... inside of STP, there is no notion of a "type" (== SMTLIB "sort"), like you might have with something like Boolector or Z3's API.

When you *declare* either a `const` (or a `func`), STP obtains the type information directly from the underlying expression. Behind the scenes something that is of sort `stp::BITVECTOR` is just an expression where it has value width (i.e., `> 0`) but *not* an index width (i.e., `== 0`. An expression with a value width and an index width is then an `stp::ARRAY`, and expression with neither is an `stp::BOOLEAN`.

If you call `getType()` on an expression, all you're getting is "is this type a `BITVECTOR`, an `ARRAY` or a `BOOLEAN`?" -- there is no further typing associated with the `getType` call.

Adding support for user-defined *sorts* that can then be reused (and have their own typing information) is possible, but it would be currently (I believe) unprecedented in the STP code-base.

**Comment by mikhailramalho** [comment]
Thanks for the answers @rgov and @andrewvaughanj.

1. I'm happy to try to submit a patch. I actually tried but I didn't get too far: `GetValueWidth()` seems to always return `0` in my tests.

2. I'll try the approach of creating a dummy expr to query its length.

Just a bit of context: I'm writing [Camada](https://github.com/mikhailramalho/camada), a wrapper for several SMT solvers, including STP. 

I'll use the type length information mostly for debugging: camada offers a layer that encodes all floating-point operations using bitvectors and the type length is helpful to get rid of off-by-one errors in the code.

**Comment by andrewvaughanj** [comment]
@mikhailramalho I just created the PR #391 that hopefully solves this for you. You should be able to use `vc_getValueSize` and `vc_getIndexSize` for your purposes.

Can you check this? If it works for you, I can merge the PR.

**Comment by mikhailramalho** [comment]
Thanks for the patch, @andrewvaughanj, it worked for me!

**Comment by andrewvaughanj** [comment]
Excellent! @msoos already merged the PR!
