### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by netFriendGao** [stp/stp#395]
error: expected ‘)’ before ‘(’ token
 constexpr lbool l_True = lbool((uint8_t)0);

**Comment by andrewvaughanj** [comment]
Hi,

I guess you're experiencing this while trying to build STP from source, right?

Can you provide some more details? For example, your operating system, your compiler, how you're building/configuring STP?

Cheers,

Andrew

**Comment by netFriendGao** [comment]
I use VS2019 compiler on WIN10 system to connect the virtual machine remotely ,ubuntu 18.04.  
when I switch to  CMake Taregets View,execute the executable file(stp-bin) will occur this error.

**Comment by andrewvaughanj** [comment]
Can you connect directly to Ubuntu (e.g., via SSH)? Does STP build if you use CMake directly?

Also, I think this error is from the [CMS](https://github.com/msoos/cryptominisat) code -- how have you built CMS (as a dependency of STP)?

**Comment by netFriendGao** [comment]
Yes,this error from CMS code, I have built CMS, follow your steps in the README.
How to connect directly to Ubuntu?
If I have the build file on Ubuntu, what should I do next?

**Comment by msoos** [comment]
Hi,

Thanks for the bug report! Unfortunately, you are giving very few details here and that makes it very hard for us to help you :( We cannot possibly fix your issue given the information you are giving. Please let us know:
- What version of Windows are you using?
- Are you using the Linux emulation of Windows or are you using virtual machine(s)?
- Did you clone the GIT or downloaded the tarball for STP?
- Did you clone the GIT or downloaded the tarball for CryptoMiniSat?
- Please give full log of build, including cmake, of the CryptoMiniSat build process
- Have you built CryptoMiniSat first? Please give full log.
- Please give full log of build, including cmake, of the STP build process
- What are you using to build STP? CMS? Visual Code compiler? mingw? GCC from Unbutu compatibility mode? Ubuntu in virtual machine?

Looking forward to helping,

Mate

**Comment by andrewvaughanj** [comment]
Looks like it might be the same as #384.

@netFriendGao could you try this (hopefully it should build you all of the deps and STP in isolation):

```
#!/bin/bash

set -euxo pipefail

workdir=workdir

rm -rf ${workdir}

mkdir ${workdir}

cd ${workdir}

git clone https://github.com/stp/minisat.git
git clone https://github.com/msoos/cryptominisat.git
git clone https://github.com/stp/stp.git

cd minisat
mkdir build
cd build
cmake ..
make -j$(nproc)
export MINISAT_LIBDIR=$(readlink -f .)
export MINISAT_INCLUDE_DIRS=$(readlink -f ..)
cd ..
cd ..

# avoid cmake doing clever stuff
rm -rf ~/.cmake

cd cryptominisat
mkdir build
cd build
cmake ..
make -j$(nproc)
export CRYPTOMINISAT5_DIR=$(readlink -f .)
cd ..
cd ..

# avoid cmake doing clever stuff
rm -rf ~/.cmake

cd stp
mkdir build
cd build
cmake -DMINISAT_LIBDIR:PATH=${MINISAT_LIBDIR} -DMINISAT_INCLUDE_DIRS:PATH=${MINISAT_INCLUDE_DIRS} -DFORCE_CMS:BOOL=ON -Dcryptominisat5_DIR:PATH=${CRYPTOMINISAT5_DIR} ..
make -j$(nproc)
cd ..
cd ..

echo "(check-sat)" | ./stp/build/stp_simple

cd ..

# EOF
```

Admittedly, you might need to do this via SSH (directly onto your Ubuntu VM) rather than from within Visual Studio + "CMake Targets View".

**Comment by netFriendGao** [comment]
I have generated a build file

**Comment by andrewvaughanj** [comment]
Can you tell us what the problem/solution was? That will help future people who might experience the same issue.

**Comment by netFriendGao** [comment]
But,what should I do next? How do I run this program?

**Comment by andrewvaughanj** [comment]
Take a look here:

- http://smtlib.cs.uiowa.edu/examples.shtml

Please note, STP only supports QF_ABV *but without array extensionality*.

**Comment by netFriendGao** [comment]
Why can't the program be run by double-clicking the mouse，but it can be executed in the terminal?
My stp and stp_simple in build file is ‘shared library (application/x-sharedlib)’  type. Is this normal?

**Comment by andrewvaughanj** [comment]
@netFriendGao STP is a command-line application; you run it by either proving an SMT2 file as the first argument, or by sending commands "iteratively" via stdin.

I am not sure what behaviour you'd expect to happen when double-clicking the executable (I assume you mean from within something like KDE or Gnome).

> My stp and stp_simple in build file is ‘shared library (application/x-sharedlib)’ type
>

Sounds about right; the file is likely to be the a dynamically-linked executable.

**Comment by netFriendGao** [comment]
How do I build on windows system?thank you

**Comment by andrewvaughanj** [comment]
This is documented under the section `Building on Windows/Visual Studio` in the top-level [README](https://github.com/stp/stp/blob/master/README.markdown).
