### ISSUE TITLE
Unexpected errors when updating STP

### ISSUE THREAD

**Issue by ericwhitmansmith** [stp/stp#403]
I am trying to update my Axe prover to use the latest version of STP, but I am getting surprising syntax errors.  For example, this file:

https://www.kestrel.edu/download/problem.cvc

new causes:
```
syntax error: line 18
syntax error, unexpected WITH
Fatal Error: 
STP Error:
```

whereas STP version 2.1.2 just says "Valid."  As far as I can tell, nothing is wrong with the file.  Can someone take a look?  

BTW, the version where it works is:
```
STP version 2.1.2
STP version SHA string 80742b4858e695e741a30f6d4111ee63e6917e9c
```

Thanks!
-Eric

**Comment by andrewvaughanj** [comment]
This is not asked in a "rude" way, but is there a reason you're using the CVC input format?

This is a language that even CVC4/CVC5 (the flagship CVC solver) is [dropping support for](https://cvc4.github.io/2021/04/02/cvc5-announcement.html): 

> Support for the old “CVC” language will be discontinued; users will be encouraged to use the SMT-LIB standard input language instead
>

If you support an SMTLIB2 backend, and this works for you, then maybe you can just switch to that?

If you really need the CVC frontend in STP, I can take a look at why this is broken (but, just to be upfront, this doesn't feel like a great use of effort, given the status of the CVC language).

**Comment by andrewvaughanj** [comment]
```
BTW, the version where it works is:
STP version 2.1.2
STP version SHA string 80742b4
```

Just to check: you're saying it works on 2.1.2 and works on 80742b4 (which means 2.3.1 likely works), but doesn't work on 2.3.2 (which is after 80742b4)?

**Comment by ericwhitmansmith** [comment]
Hi Andrew,

Thanks for the quick response!  I'm using the CVC input format because I think that's all there was when I started using STP back in 2006 (Vijay and I were in the same research group at Stanford).  Switching to SMTLIB is something I'd like to do eventually, but that would require me to re-implement the translation code.  Currently this input file (and similar files) are causing STP errors, so I'm stuck using the old version of STP.

Regarding the version, I pasted in what 'stp --version' prints for the version that works.  I don't know why there seems to be a discrepancy between the version number it prints and the hash that it prints.  Here is the full output:

STP version 2.1.2
STP version SHA string 80742b4858e695e741a30f6d4111ee63e6917e9c
STP compilation options CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wunused -pedantic -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-\
deprecated -Wstrict-aliasing -Wpointer-arith -fvisibility=hidden -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -fPIC | COMPILE_DEFINES =  -D__ST\
DC_LIMIT_MACROS | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATICCOMPILE = OFF | TUNE_NATIVE = OFF | COVERAGE = OFF | FORCE_CMS = OFF | LIBS = /usr/local/lib/libminisat.so | ENABLE_TESTING \
= OFF | ENABLE_PYTHON_INTERFACE = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = /usr/lib/x86_64-linux-gnu/libpython2.7.so | PYTHON_INCLUDE_DIRS = /usr/include/python2.7 \
|  | compilation date time = Oct 25 2018 16:12:22
c compiled with gcc version 8.1.0

On another machine, where the example also works, 'stp --version' gives:

STP version 2.1.2
STP version SHA string b67aa8396762a5831f0d228b4db26e77392774ae
STP compilation options CMAKE_CXX_COMPILER = /Library/Developer/CommandLineTools/usr/bin/c++ | CMAKE_CXX_FLAGS =  -stdlib=libc++ -Wall -Wextra -Wunused -pedantic -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wheader-guard -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -fPIC | COMPILE_DEFINES =  -D__STDC_LIMIT_MACROS | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATICCOMPILE = OFF | TUNE_NATIVE = OFF | COVERAGE = OFF | FORCE_CMS = OFF | LIBS = /usr/local/lib/libminisat.dylib | ENABLE_TESTING = OFF | ENABLE_PYTHON_INTERFACE = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = /usr/lib/libpython2.7.dylib | PYTHON_INCLUDE_DIRS = /usr/include/python2.7 |  | compilation date time = Nov 17 2017 17:16:17
c compiled with gcc version 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)

Thanks!
-Eric

**Comment by msoos** [comment]
Hi!

Sorry for the "version number" -- to be honest, we should completely remove it. It's extremely misleading, we haven't bumped it in a very long while. The only thing that you/we should be looking at is the `version SHA string`.

Can you please give us the CVC file you are trying to pass to the system? Maybe we introduced a bug. The version where you reported it working, `80742b4858e695e741a30f6d4111ee63e6917e9c`, is from 2018, so likely there have been substantial changes which may have broken your example, or perhaps may have fixed some check which now potentially detects some discrepancy (i.e. the old result may have been incorrect/unreliable).

If you could give us the CVC file, we could try to check!

Thanks for your patience,

Mate

**Comment by ericwhitmansmith** [comment]
Thanks, Mate!  The original CVC file is linked from my post above.  You can grab it from here:
https://www.kestrel.edu/download/problem.cvc
But maybe the smaller example I just made is more useful.  It is here:
https://www.kestrel.edu/download/problem2.cvc

**Comment by msoos** [comment]
Hi,

So seemingly f6f2707ec68ab17354b8604981a85f8cc55028fe works. I see the DIFF between f6f2707ec68ab17354b8604981a85f8cc55028fe and current master that may be of interest since it concerns `WITH` in `cvc.y`:

```
@@ -1015,18 +1008,18 @@
 } | STRING_TOK
 {
    cerr << "Unresolved symbol:" << $1 << endl;
-   yyerror("bad symbol"); 
+   yyerror("bad symbol");
 }
 ;
 
 /*Grammar for Array Update Expr*/
-ArrayUpdateExpr : Expr WITH_TOK Updates
+ArrayUpdateExpr : Expr Updates
 {
   ASTNode * result;
   unsigned int width = $1->GetValueWidth();
 
-  ASTNodeMap::iterator it = $3->begin();
-  ASTNodeMap::iterator itend = $3->end();
+  ASTNodeMap::iterator it = $2->begin();
+  ASTNodeMap::iterator itend = $2->end();
   result = new ASTNode(GlobalParserInterface->nf->CreateArrayTerm(WRITE,
                                             $1->GetIndexWidth(),
                                             width,
@@ -1045,20 +1038,20 @@
   }
   BVTypeCheck(*result);
   $$ = result;
-  delete $3;
+  delete $2;
   delete $1;
 }
 ;
 
-Updates         : '[' Expr ']' ASSIGN_TOK Expr 
+Updates         : '[' Expr ']' ASSIGN_TOK Expr
 {
   $$ = new ASTNodeMap();
-  (*$$)[*$2] = *$5;         
+  (*$$)[*$2] = *$5;
   delete $2;
-  delete $5;        
+  delete $5;
 }
-| Updates WITH_TOK '[' Expr ']' ASSIGN_TOK Expr 
-{                   
+| Updates WITH_TOK '[' Expr ']' ASSIGN_TOK Expr
+{
   (*$1)[*$4] = *$7;
   delete $4;
   delete $7;
```

Do I understand correctly that the way `WITH` is supposed to be used has changed? Do you think you can adjust your CVC to this? Do you know which version is "right"? In other words, should we adjust our definition back, or do you think your use is correct? Or are both correct? Or am I completely on the wrong track?

Thanks for checking this out,

Mate

**Comment by ericwhitmansmith** [comment]
Aha!  This is interesting.  My examples seem to work fine with the current STP if I just remove all occurrences of the "WITH" token.  That would be an easy change to my code.  I guess the question is which way is right.  According to this page:

https://stp.readthedocs.io/en/latest/cvc-input-language.html

the "WITH" is supposed to be present for an array write.  It gives the example of "x_arr WITH [index] := value".

This page:

https://cvc4.github.io/cvc4-native-input-language.html

also mentions "WITH", saying "a WITH [i] := v denotes a map that associates v to index i and is otherwise identical to a."

I believe it's the case that STP has supported the use of "WITH" for most of the past 15 years.  So I would suggest that it be changed back to work with the "WITH" being present.

FWIW, the old version of STP that I am using rejects my examples if I remove the "WITH" tokens, saying "syntax error, unexpected :=".

Thanks!
-Eric

**Comment by msoos** [comment]
Thanks Eric for the detailed response! I have now nailed it down to this commit: ee7a42a5e494e1dfdf5aaffca36fe969ec8b4b2c by @bpfoley. Brian, can you please look at this? Seems like it was supposed to fix a warning but seemingly changed behaviour? Should I revert this change?

Thanks,

Mate

**Comment by andrewvaughanj** [comment]
I think Brian’s changes were to clean-up build-time warnings, rather than “functional changes”.

Given this, and that I don’t think that Brian needed functional changes in the CVC parser, it is probably safe to revert it.

**Comment by msoos** [comment]
Fair enough! I have reverted the change and added a your mini-example as a test case! Should all be good now :)

Thanks again for reporting,

Mate
