### ISSUE TITLE
Assert failed parsing `laby_20_20_15.lp.smt2`, issue for SMTCOMP2021

### ISSUE THREAD

**Issue by msoos** [stp/stp#407]
As per email that @conp-solutions and me received from the SMTCOMP2021 organizers, the files `laby_20_20_15.lp.smt2`, gzipped attached (also available from [here](https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/QF_BV/-/blob/master/asp/Labyrinth/laby_20_20_15.lp.smt2) ) and `laby_21_21_15.lp.smt2` are causing issues.

On STP 876589d45f656f13cefeb04a2f13005d0fa0c932, `laby_20_20_15.lp.smt2` causes an assert fail:
```
soos@tiresias:build$ /usr/bin/time --verbose ./stp --SMTLIB2 --output-CNF --exit-after-CNF laby_20_20_15.lp.smt2 
stp: /home/soos/development/smt/stp/lib/Simplifier/PropagateEqualities.cpp:333: stp::ASTNode stp::PropagateEqualities::propagate(const stp::ASTNode&, stp::ArrayTransformer*): Assertion `false' failed.
Command terminated by signal 6
        Command being timed: "./stp --SMTLIB2 --output-CNF --exit-after-CNF laby_20_20_15.lp.smt2"
        User time (seconds): 84.11
        System time (seconds): 0.40
        Percent of CPU this job got: 97%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:27.01
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 596988
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 15
        Minor (reclaiming a frame) page faults: 160688
        Voluntary context switches: 15
        Involuntary context switches: 188
        Swaps: 0
        File system inputs: 2888
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

The file `laby_21_21_15.lp.smt2` causes an  assert fail, too, at seemingly the same place:

```
soos@tiresias:build$ /usr/bin/time --verbose ./stp --SMTLIB2 --output-CNF --exit-after-CNF laby_21_21_15.lp.smt2 
stp: /home/soos/development/smt/stp/lib/Simplifier/PropagateEqualities.cpp:333: stp::ASTNode stp::PropagateEqualities::propagate(const stp::ASTNode&, stp::ArrayTransformer*): Assertion `false' failed.
Command terminated by signal 6
        Command being timed: "./stp --SMTLIB2 --output-CNF --exit-after-CNF laby_21_21_15.lp.smt2"
        User time (seconds): 84.72
        System time (seconds): 0.35
        Percent of CPU this job got: 97%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:27.53
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 600548
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 161576
        Voluntary context switches: 4
        Involuntary context switches: 199
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

[laby_20_20_15.lp.smt2.gz](https://github.com/stp/stp/files/6824956/laby_20_20_15.lp.smt2.gz)

**Comment by msoos** [comment]
My minor investigations shows that there is something perhaps going wrong, and/or unexpected. The code at line 333 is not even complied in(!!) when `NDEBUG` is active, because of this `#ifdef`:
```
// The below block should be subsumed by the searchXOR function which
// generalises it.
// So the below block should never do anything..
#ifndef NDEBUG
```

Then there is a lot of code, and finally, we have:

```
      if (simp->UpdateSolverMap(symbol, nf->CreateNode(NOT, rhs)))
      {
        assert(false);
        output = ASTTrue;
      }
```

where `assert(false)` is line 333.

Unfortunately, I'm not well-equipped to understand what's going on here :( Would it be possible for someone to take a look? @andrewvaughanj @TrevorHansen ?

**Comment by andrewvaughanj** [comment]
I'll try to look at this tonight.

Does this reproduce on master, @msoos? Lazy question, but I haven't tried.

**Comment by msoos** [comment]
Yep, it reproduces, apparently, 876589d *is* master :rofl:  Sorry about that!

**Comment by andrewvaughanj** [comment]
Wow, I didn't even see you wrote the hash 🤦

**Comment by TrevorHansen** [comment]
What's happened is:
* In the old days we had code to solve for variables in XORS, and then
remove them from the problem.
* Later on I made a more comprehensive XOR solver - that handled more cases.
* I wasn't sure if the new solver subsumed the old one, so put the old code
in as a check in debug mode. It checks that the new solver does everything
the old does.
* Just before SMT-COMP I put a timeout on the new XOR solver. So
sometimes now the new solver will timeout before doing everything that the
old solver did.
* In this case it's timing out and failing the check against the old solver.

It's an easy fix. Only do the check in the debug code if a timeout hasn't
occurred.

**Comment by TrevorHansen** [comment]
It's an ugly patch, but it just wraps it in a simple check that the timeout hasn't happened already. I knew this happened in debug mode, but was in a rush and didn't think it'd be a problem in the short term. The propagating code is the code I'm most unhappy with in STP and mean to rewrite it all.

**Comment by andrewvaughanj** [comment]
Wow, amazing work, @TrevorHansen -- thanks for fixing it so quickly!

I hadn't even thought that it would be timeout related; I spent last night trying to reduce the file (got it to 24 MB from 52 MB), so I'm glad you fixed this now, otherwise I would have spent all day being like "why can't I make the file smaller?", when you can't, because too small == no timeout 😂

**Comment by andrewvaughanj** [comment]
Ha! And I guess that this:

- https://github.com/stp/stp/blob/81850c0d6973bf5fb7d283ab4037385930290be2/lib/Simplifier/PropagateEqualities.cpp#L49

is 80 seconds, which means it always needs to take a least 80 seconds ... I stood no chance to make it "tiny" 😆

**Comment by msoos** [comment]
Thank you so much! Amazing! :) Sending update to Cloud track now!
