### ISSUE TITLE
Many test cases are failing in CI

### ISSUE THREAD

**Issue by rgov** [stp/stp#419]
```
The following tests FAILED:
	  1 - query-files (Failed)
	  2 - C-api-tests-gtest-suite (Failed)
	  5 - b4-c2Tests-gtest (Subprocess aborted)
	 25 - stp-div-001Tests-gtest (Subprocess aborted)
	 39 - python-interface-tests (Subprocess aborted)
```

---

The "subprocess aborted" failures seem to be related to this:

    /home/runner/work/stp/stp/lib/STPManager/STP.cpp:641:
    stp::SOLVER_RETURN_TYPE stp::STP::TopLevelSTPAux(stp::SATSolver &, const stp::ASTNode &):
    Assertion `arrayops' failed.

The last change around this was e1682133e8310526fcca96724f7ed3a8ea01294e by @TrevorHansen last summer.

---

The `query-files` failures are:

  * https://github.com/stp/stp/blob/master/tests/query-files/crypto-tests/tea_three_round_one_var.stp.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/crypto-tests/tea_two_round_two_var.stp.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a164test0005.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a169test0012.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a172test0002.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a174test0003.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a178test0007.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-cvc-tests/a180test0004.cvc
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-smt-tests/Example_1.txt.smt2
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-smt-tests/arity1.smt2
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-smt-tests/symbols.smt2
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-smt-tests/tmp.FKuQABT1Bf.smt2
  * https://github.com/stp/stp/blob/master/tests/query-files/sample-smt-tests/tmp.m8W1FfWP7L.smt2

---

The `C-api-tests-gtest-suite` failures come from two failing files:

  * https://github.com/stp/stp/blob/master/tests/api/C/b4-c2.cpp
  * https://github.com/stp/stp/blob/master/tests/api/C/stp-div-001.cpp

**Comment by rgov** [comment]
The `C-api-tests-gtest-suite` failures look like they're the same as the assertion failure. Possibly they're all related to this one issue.

**Comment by nivi1501** [comment]
I am also facing the same issue, is there any fix for this?

**Comment by rgov** [comment]
It seems that the logic is that if there are no array operations, the SAT solver is expected to not return `SOLVER_UNDECIDED`, but it is.

https://github.com/stp/stp/blob/e1682133e8310526fcca96724f7ed3a8ea01294e/lib/STPManager/STP.cpp#L618-L619

**Comment by TrevorHansen** [comment]
I'll figure out what I've done. 

To check that STP gets the right answer, in debut mode,  it substitutes the model/counter-example it gets from the SAT solver into the original problem. This assertion error occurs when it doesn't collapse down to "True". I suspect it's sound, just that a mapping to a variable is lost along the way. For example that "x must equal y +1" to be true.

**Comment by TrevorHansen** [comment]
This was a soundness problem introduced in 7351d7d2179b8d70703fe8569af3d5d4902452c1

I expected the "Id" of AIGs to be unique, but different AIGs have the same Id, so different AIGs were erroneously being discarded from a set.

CI is still failing:
```
CMake Error at bindings/python/stp/CMakeLists.txt:78 (message):
  Reported python site package directory '/usr/lib/python3.8/site-packages'
  does not exist
```
It seems like CI doesn't have the install path for the python bindings?

**Comment by rgov** [comment]
Thanks! CI is succeeding but the CodeQL analysis is not. I think that can be tracked by a different issue.
