### ISSUE TITLE
Function corresponding to ZeroExt in STP solver with python interface

### ISSUE THREAD

**Issue by Anonychn** [stp/stp#434]
Hi all,

What is the function in STP that works same as ZeroExt in Z3?
For example, below is a code snippet from Z3 solver
```
from z3 import *
m = Solver()
var = [BitVec('s%d'%i,1) for i in range(5)]
***Some equations that involve Xor and &***
m.add(ZeroExt(3,var[0]) + ZeroExt(3,var[1]) + ZeroExt(3,var[2]) + ZeroExt(3,var[3]) + ZeroExt(3,var[4]) == 5)
m.check()
print(m.model())
```
I want to increase the size of BitVec variables temporarily just to increase the modular size. I want to solve a similar model as above in STP as it uses cryptominisat as a SAT solver.

**Comment by aytey** [comment]
You need to use the "non-wrapped" form of `vc_bvConcatExpr` -- it takes a `solver.vc` and then the two expressions you want to "join". To do a zero ext, your first term wants to be the constant zero at the bit-width you want to extend by.

If you look at something like `Solver.xor` in `stp.py`, you should be able to see how `vc_bvConcatExpr` should be called.

Sorry that it isn't more polished.

**Comment by rgov** [comment]
Beat me to it @aytey. Anyway, let's please use [Discussions](https://github.com/stp/stp/discussions) for general questions. (GitHub won't let me transfer this issue over there, so I'll just mark as closed.)
