### ISSUE TITLE
PDF link on SMT-LIB v2 documentation page is not working

### ISSUE THREAD

**Issue by mnswdhw** [stp/stp#435]
I might be mistaken but I think the documentation https://stp.readthedocs.io/en/latest/smt-input-language.html has a broken/wrong link. "For longer description please read this PDF". Here the link redirects to https://www.grammatech.com/ . 

Please check.

**Comment by aytey** [comment]
I don't know if this was the "last" (as in, most recent version), but a version is here: https://smtlib.github.io/jSMTLIB/SMTLIBTutorial.pdf

We could add this to our repo to avoid potentially having broken links again in the future.

It might be better just to redirect people to https://smtlib.cs.uiowa.edu/

**Comment by mnswdhw** [comment]
Thank you for your prompt response. May I change the link to https://smtlib.github.io/jSMTLIB/SMTLIBTutorial.pdf and open a pull request for the same ?

**Comment by aytey** [comment]
> May I change the link to https://smtlib.github.io/jSMTLIB/SMTLIBTutorial.pdf and open a pull request for the same ?
>

No, because then what happens if jSMTLIB removes/deletes that PDF? I am also not sure it makes sense to add that PDF to our repo.

Changing the link to be https://smtlib.cs.uiowa.edu/ would be the only reasonable choice (as that URL is the canonical source of "all things SMTLIB").

**Comment by mnswdhw** [comment]
Oh Okay, understood.

**Comment by mnswdhw** [comment]
Closing. Fixed in the commit [e8d153f](https://github.com/stp/stp/commit/e8d153f196dcdf609add70e867f2188d58ffcc97)
