### ISSUE TITLE
Question about parallel.

### ISSUE THREAD

**Issue by TraceShadow** [stp/stp#456]
Hi, I would like to know if there is a parallel function in your smt solver now? I really need this feature, thank you very much!

**Comment by aytey** [comment]
What kind of parallel are you referring to? STP being able to attempt solving one instance using multiple threads (itself) or that you want to create multiple STP instances and you use them in parallel?

**Comment by TraceShadow** [comment]
The first one is OK.

**Comment by TraceShadow** [comment]
I saw your solver has a parameter called "threads", but it is in the "SAT Solver options". Does this mean that if I use this parameter, the smt file will be converted to cnf and use sat solver?

**Comment by TraceShadow** [comment]
> What kind of parallel are you referring to? STP being able to attempt solving one instance using multiple threads (itself) or that you want to create multiple STP instances and you use them in parallel?
The first one is OK. I saw your solver has a parameter called "threads", but it is in the "SAT Solver options". Does this mean that if I use this parameter, the smt file will be converted to cnf and use sat solver?

**Comment by msoos** [comment]
It means that your file will be solved using a multi-threaded SAT solver. Unfortunately your question is not well-formulated, so it's hard to answer. However, it means that we'll use a multi-threaded SAT solver, such as CMS, to solve it using multiple threads. However, this may NOT be as much faster as you think. It's hard to speed up solving. I hope this answers your question!
