### ISSUE TITLE
how to install stp on windows  can you give me a program step by step?

### ISSUE THREAD

**Issue by 1214465750** [stp/stp#458]

**Comment by aytey** [comment]
This (probably) isn't documented; the best place to look is https://github.com/stp/stp/blob/master/appveyor.yml

**Comment by 1214465750** [comment]
> 这（可能）没有记录在案;最好的地方是 https://github.com/stp/stp/blob/master/appveyor.yml

do you know how to use appveyor install stp on windows

**Comment by aytey** [comment]
No, I'm saying: "read what's in that yml file to work out the correct commands to run on Windows".

**Comment by aytey** [comment]
Given you've started to ask usage questions, I presume this is resolved.

**Comment by 1214465750** [comment]
i fail install it on windows but success on ubuntu,that's enough,thank you very much @aytey
