### ISSUE TITLE
does stp has api?

### ISSUE THREAD

**Issue by 1214465750** [stp/stp#461]

**Comment by aytey** [comment]
Yes:

- C: https://github.com/stp/stp/blob/master/include/stp/c_interface.h
- C++: https://github.com/stp/stp/blob/master/include/stp/cpp_interface.h
- Python: https://github.com/stp/stp/blob/master/bindings/python/stp/stp.py.in

Here's an example of the C-based API: https://github.com/stp/stp/tree/master/examples/simple

**Comment by 1214465750** [comment]
@aytey 
for example
`
from stp import *
s=Solver()
a=s.bitvec('a',10)
b=s.bitvec('b',10)
c=s.bitvec('c',10)
`
if a==1 
then b==1 
else c==1
how can i achieve this

**Comment by aytey** [comment]
Sorry, it is very unclear what you mean there -- what do you want to happen when, e.g., `a == 1`? Also, is this the `ite` question? If so, please can you ask this under your `ite` issue, and not confuse issues like this.

**Comment by 1214465750** [comment]
sorry,it's my problen.
I have two question:
1.What is the function of ite()

**Comment by 1214465750** [comment]
sorry,it's my problen.
I have two question:
1.What is the function of ite()? how to use it?
2.if I want to achieve
`
if a==1
then b==1
else c==1
`
Is there any function in stp on python?
@aytey

**Comment by aytey** [comment]
> 1.What is the function of ite()? how to use it?
>

The semantics of `ite` are given here: https://smtlib.cs.uiowa.edu/theories-Core.shtml

> Is there any function in stp on python?
>

Yep! Seem my comment on your other issue about `ite`: https://github.com/stp/stp/issues/460#issuecomment-1455726752 😄
