### ISSUE TITLE
Build and runtime errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by gjurgensen** [stp/stp#465]
I'm getting a couple of build errors on Ubuntu 22.04.2 LTS. On the first machine, I receive the following error when trying to build according to the "quick install" instructions on the README:
```sh
[ 98%] Linking CXX executable ../../stp
/usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::SimpSolver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
/usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::Solver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [tools/stp/CMakeFiles/stp-bin.dir/build.make:117: stp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1050: tools/stp/CMakeFiles/stp-bin.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
As per the suggestion in #446, I fixed this issue by starting over and running `./scripts/deps/setup-minisat.sh` along with the other setup scripts. This time the build worked and STP ran fine.

On a second machine (again Ubuntu 22.04.2 LTS), I repeated the process. I again got a build error following the quick install instructions, although the error was different:
```sh
/home/grant/local/stp/lib/Sat/MinisatCore.cpp: In member function ‘bool stp::MinisatCore::propagateWithAssumptions(const stp::SATSolver::vec_literals&)’:
/home/grant/local/stp/lib/Sat/MinisatCore.cpp:81:42: error: expected unqualified-id before ‘(’ token
   81 |   return ret != (Minisat::lbool)Minisat::l_False;
      |                                          ^~~~~~~
/home/grant/local/stp/lib/Sat/MinisatCore.cpp: In member function ‘virtual bool stp::MinisatCore::solve(bool&)’:
/home/grant/local/stp/lib/Sat/MinisatCore.cpp:91:39: error: expected unqualified-id before ‘(’ token
   91 |   if (ret == (Minisat::lbool)Minisat::l_Undef)
      |                                       ^~~~~~~
/home/grant/local/stp/lib/Sat/MinisatCore.cpp:96:42: error: expected unqualified-id before ‘(’ token
   96 |   return ret == (Minisat::lbool)Minisat::l_True;
      |                                          ^~~~~~
gmake[2]: *** [lib/Sat/CMakeFiles/sat.dir/build.make:76: lib/Sat/CMakeFiles/sat.dir/MinisatCore.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:972: lib/Sat/CMakeFiles/sat.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
Again, I started over and ran the `./scripts/deps/setup-minisat.sh` script before re-building. This time the build completed, However, the resulting binary is crashing on certain inputs. For instance, given the following input file:
```
NODE0 : BITVECTOR(8);
NODE1 : BITVECTOR(8);
QUERY (
LET NODE2 = (NODE1[0:0]) IN (
LET NODE3 = (NODE0[0:0]) IN (
LET NODE4 = (0bin0 = NODE2) IN (
LET NODE5 = (0bin0 = NODE3) IN (
LET NODE6 = (IF NODE5 THEN 0bin0[0:0] ELSE NODE0[0:0] ENDIF)[0:0] IN (
LET NODE7 = (IF NODE5 THEN NODE1[0:0] ELSE 0bin0[0:0] ENDIF)[0:0] IN (
LET NODE8 = (IF NODE4 THEN NODE6[0:0] ELSE NODE7[0:0] ENDIF)[0:0] IN (
LET NODE89 = (BVXOR(NODE1[0:0],NODE0[0:0])) IN (
(NODE8 = NODE89))))))))));
```
This produces the following runtime error:
```sh
stp: /home/grant/local/stp/lib/ToSat/ToSATAIG.cpp:160: void stp::ToSATAIG::add_cnf_to_solver(stp::SATSolver&, Cnf_Dat_t*): Assertion `(var < satSolver.nVars())' failed.
[1]    15471 IOT instruction (core dumped)  stp err.cvc
```
The binary does not crash on every input; it has successfully processed other inputs.

**Comment by gjurgensen** [comment]
On a semi-related note, the first line of the quick install instructions:
```sh
sudo apt-get install cmake bison flex libboost-all-dev python perl minisat
```
This fails because `python` is no longer an apt package. `python2` or `python3` are valid packages though.

**Comment by rgov** [comment]
Does the assertion failure only happen on one of the two?

**Comment by rgov** [comment]
If you use `setup-minisat.sh` please `apt remove minisat`.

**Comment by gjurgensen** [comment]
> Does the assertion failure only happen on one of the two?

Yes, that failure only occurred on one of the two machines tested.

> If you use setup-minisat.sh please apt remove minisat.

Ah, I should have thought of this! This solved the assertion issue. Thanks.

Perhaps the README should be updated to reflect these issues (i.e. removing the `apt install minisat` and adding `setup-minisat.sh`)?

**Comment by gjurgensen** [comment]
> This solved the assertion issue.

That was slightly premature. STP worked when the the build directory was the working directory. Otherwise, it produced the following error:
```sh
stp: error while loading shared libraries: libminisat.so.2: cannot open shared object file: No such file or directory
```
Evidently the minisat library couldn't be found. I solved this by adding `deps/install/lib` to the `LD_LIBRARY_PATH` environment variable. Presumably one could also copy/link the library to some more standard location.

**Comment by TrevorHansen** [comment]
Thanks @gjurgensen I've updated the quick build instructions like you suggested.
