### ISSUE TITLE
 Assertion `solver->value(replaced_with_var) == l_Undef' failed

### ISSUE THREAD

**Issue by SJTUwwz** [stp/stp#470]
The background is that I am trying to use stp to model some encryption algorithms. I met such a mistakes
 "stp: /home/jdwwz/cryptominisat/src/varreplacer.cpp:145: void CMSat::VarReplacer::update_vardata(CMSat::Lit, CMSat::Lit): Assertion `solver->value(replaced_with_var) == l_Undef' failed." 
and didn't know how to fix it. 
What further confuses me is that I have tried varying the number of rounds of the algorithm, and both higher and lower numbers of iterations seem to work fine. This makes the whole issue appear even more random in nature. 
By the way, I'd like to mention that I'm using a .cvc file, but the model file is too large for me to upload directly here. I'm unsure where the issue lies and I hope to receive your assistance. Thank you!

**Comment by TrevorHansen** [comment]
It's hard to say what's going wrong, if you can attach a stack trace, or upload the problem somewhere then we can help more.

As an aside, it'd be best to convert your tool to generate SMTLIB2 format. That way you'd be able to easily run your problems on other solvers.

**Comment by SJTUwwz** [comment]
I first generated the CVC files and then called stp solver with command "stp xxx.cvc --CVC". If it's convenient, perhaps I can send the model files to you via email? Each file is approximately 150KB in size and contains around 300 variables and 2000 constraints.

**Comment by aytey** [comment]
If you change the extension to .txt, you should be able to attach them to this issue

**Comment by SJTUwwz** [comment]
[tmp1.txt](https://github.com/stp/stp/files/12854499/tmp1.txt)
[tmp2.txt](https://github.com/stp/stp/files/12854500/tmp2.txt)
Thank you for your useful advice! 
I just upload two files below. The tmp1.txt file corresponds to the model that can not be solved, while the tmp2.txt file can be solved easily. 
The two files are essentially the same, with the only difference being that the latter has more variables and constraints. Exactly, "tmp2" is an extension of "tmp1" with an additional round of additions.

**Comment by SJTUwwz** [comment]
But the error happened on my machine
`(base) jdwwz@gdp:/mnt/extra_space/jdwwz/GeneralMonomialPrediction/GMP/Feistel_MiMC$ stp --version
STP version 2.3.3
STP version SHA string 149f43f038e07422c5273451165f024db3190e33
STP compilation options CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wunused -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -fno-omit-frame-pointer | COMPILE_DEFINES =  -D__STDC_LIMIT_MACROS -DUSE_CRYPTOMINISAT | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATICCOMPILE =  | TUNE_NATIVE = OFF | COVERAGE = OFF | FORCE_CMS = OFF | LIBS = /usr/local/lib/libminisat.so | ENABLE_TESTING = OFF | ENABLE_PYTHON_INTERFACE = ON | PYTHON_EXECUTABLE = /home/anaconda3/bin/python | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  |  | compilation date time = Sep 19 2023 19:01:34
c compiled with gcc version 9.4.0
(base) jdwwz@gdp:/mnt/extra_space/jdwwz/GeneralMonomialPrediction/GMP/Feistel_MiMC$ stp tmp1.cvc
stp: /home/jdwwz/cryptominisat/src/varreplacer.cpp:145: void CMSat::VarReplacer::update_vardata(CMSat::Lit, CMSat::Lit): Assertion `solver->value(replaced_with_var) == l_Undef' failed.
已放弃
`
I'm wondering if this error is caused by my environment configuration？

**Comment by SJTUwwz** [comment]
Emmm，however, an error would happen on my machine when Executing the same command.
```
(base) jdwwz@gdp:/mnt/extra_space/jdwwz$ stp --version
STP version 2.3.3
STP version SHA string 149f43f038e07422c5273451165f024db3190e33
STP compilation options CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wu
nused -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -
Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code
-fno-omit-frame-pointer | COMPILE_DEFINES =  -D__STDC_LIMIT_MACROS -DUSE_CRYPTOMINISAT | ONLY_SI
MPLE = OFF | Boost_FOUND = TRUE | STATICCOMPILE =  | TUNE_NATIVE = OFF | COVERAGE = OFF | FORCE_
CMS = OFF | LIBS = /usr/local/lib/libminisat.so | ENABLE_TESTING = OFF | ENABLE_PYTHON_INTERFACE
 = ON | PYTHON_EXECUTABLE = /home/anaconda3/bin/python | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS
 =  |  | compilation date time = Sep 19 2023 19:01:34
c compiled with gcc version 9.4.0
(base) jdwwz@gdp:/mnt/extra_space/jdwwz$ stp tmp1.cvc
stp: /home/jdwwz/cryptominisat/src/varreplacer.cpp:145: void CMSat::VarReplacer::update_vardata(
CMSat::Lit, CMSat::Lit): Assertion `solver->value(replaced_with_var) == l_Undef' failed.
已放弃
(base) jdwwz@gdp:/mnt/extra_space/jdwwz$ stp tmp2.cvc
ASSERT( y46 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000100110011100011 );
ASSERT( x1_29 = 0b000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000100000001101 );
ASSERT( p_z45 = 0b00 );
ASSERT( y44 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000101011001111111011 );
ASSERT( l47 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000100010001011 );
ASSERT( x1_21 = 0b000000000000000000000000000000000000000000000000000000000000000000000000000000
000000100010000000010100000000001000000000110011100 );
ASSERT( y27 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000101001100100101110010101100011011100100100011 );
ASSERT( x1_10 = 0b000000000000000000000000000000000000000000000000000000000000000000000000000000
000001111000000000100010011000000110000010010100111 );
ASSERT( y26 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0001111100101110111100011101100001010100010000001 );
ASSERT( l44 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000001110011010101001 );
ASSERT( p_z11 = 0b00 );
ASSERT( x1_8 = 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000
00101110000000010100110011000000100000001000111010 );
ASSERT( y24 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000001
0001100010100011101011011110110000101111001100001 );
ASSERT( z10 = 0b00000000000000000000000000000000000000000000000000000000010001010011101100100000
0010000000000000001100000000000011000011011011000 );
ASSERT( t_x0_20 = 0b0 );
ASSERT( t_x0_29 = 0b0 );
ASSERT( l42 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000010000001101111100001 );
ASSERT( x1_6 = 0b0000000000000000000000000000000000000000000000000000000000001000010000000000000
00000100100000000100110010100101100100001000010100 );
ASSERT( x1_5 = 0b0000000000000000000000000000000000000000000000000000000000000000010000000000000
00000000001010000110000000011100000100000001010001 );
ASSERT( t_x0_49 = 0b0 );
ASSERT( l40 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000010010001111101011101001 );
ASSERT( x1_4 = 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000
00101001000000110101010101001110000000000100001010 );
ASSERT( p_z17 = 0b00 );
ASSERT( l38 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000010100100001101001000001100 );
ASSERT( x1_2 = 0b0000000000000000000000000000000000000000000000000100010010001010001000001000000
00010001000000010101010101111100010011000000001001 );
ASSERT( y18 = 0b00000000000000000000000000000000000000000000000000000000000000000000001100001000
0000101110000001100111100000001100000000011011001 );
ASSERT( l39 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000110110101111000010101010 );
ASSERT( p_z40 = 0b00 );
ASSERT( l37 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000111101100100111001000010101 );
ASSERT( x1_1 = 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000
01000100000001000001000110100101000010000000000100 );
ASSERT( y17 = 0b00000000000000000000000000000000000000000000000000000000000000000000100100001000
0111111111100011000001011000010000000001001010101 );
ASSERT( x1_0 = 0b0000000000000000000000000000000000000000000100100100100100100100100100100100100
10010011011011011011011011011011011011011011011100 );
ASSERT( l45 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000100110011100011 );
ASSERT( x1_9 = 0b0000000000000000000000000000000000000000000000000000000000000000000000110010000
00001010001001100111000100010000000000000010110110 );
ASSERT( y25 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0101110110001011111011111101110000100101000100011 );
ASSERT( l48 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000001011011001 );
ASSERT( x1_12 = 0b000000000000000000000000000000000000000000000000000000000000000000000010000000
000111111000000000100110011000000100000000010100110 );
ASSERT( l49 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000011110011 );
ASSERT( x1_13 = 0b000000000000000000000000000000000000000000000000000000000000000000000001000000
000011110000001010110000100010000100000000000110100 );
ASSERT( y29 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000100100111111001100011011101010000110010010 );
ASSERT( x1_14 = 0b000000000000000000000000000000000000000000000000000000000000000000000000000000
100111100100010000100110011000100100000000000100001 );
ASSERT( p_z32 = 0b00 );
ASSERT( t_x0_18 = 0b0 );
ASSERT( l51 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000011011 );
ASSERT( x1_15 = 0b000000000000000000000000000000000000000000000000000000000000000000000000000000
000011101000000000110000100010000000000000000110010 );
ASSERT( l52 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000001001 );
ASSERT( y32 = 0b00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000001010111101011001000001001100101110001 );
ASSERT( t_x0_41 = 0b0 );
```
I'm wondering if this error is caused by my environment configuration?

**Comment by aytey** [comment]
Two quick questions:

1) how did you install minisat?

2) how did you configure stp? Your output has `STATICCOMPILE = ` without a value (it should either be `ON` or `OFF`, not "absent")?

**Comment by SJTUwwz** [comment]
Let me recall..
For the first question, I install minisat just as what Readme.md tell
```
$ git clone https://github.com/msoos/cryptominisat
$ cd cryptominisat
$ mkdir build && cd build
$ cmake ..
$ cmake --build .
$ sudo cmake --install .
$ command -v ldconfig && sudo ldconfig
```
However, since I have already installed cryptominisat5 before, I change the variable "cryptominisat5_DIR" in CmakeLists during the installation.
For the second question, I have no idea about it because I don't seem to have made any additional configuration changes.

**Comment by TrevorHansen** [comment]
Yes, I think you're right it looks like a problem with the Cryptominsat setup. It's not something we can help much with. I've only got two suggestions (others might be able to help more):
1) Rebuild your shared Cryptominisat library using the latest Cryptomisat version in github, or
2) Rebuild STP & Cryptominisat using Docker and copy it out, as described here:
https://github.com/stp/stp/issues/446#issuecomment-1228503523
