### ISSUE TITLE
"--print-back-CVC" Feature in STP Solver

### ISSUE THREAD

**Issue by javadchaveleh** [stp/stp#472]
I've encountered an issue while using the "--print-back-CVC" feature in the STP solver , and I'm seeking assistance in understanding and resolving it.

The message I receive is as follows:
printback from SMTLIB2 inputs isn't currently working.
Please try again later.

I would like to mention that I am currently using version 2.3.3. Your valuable contributions in identifying the root cause, as well as potential solutions or workarounds, are highly appreciated. I look forward to your collective expertise in resolving this matter.

**Comment by aytey** [comment]
Do you mean `--print-back-SMTLIB2` (rather than `--print-back-CNF`)?
