### ISSUE TITLE
BV constants over 64 bits don't seem to work

### ISSUE THREAD

**Issue by r4dr3fr4d** [stp/stp#480]
#303/#304 don't seem to work for values over ULONG_MAX.

```
In [5]: c = s.bitvecvalD(72, str(0xaa00000000000000bb))

In [6]: hex(c.value)
Out[6]: '0xffffffffffffffff'
```

Am I doing something wrong?

**Comment by aytey** [comment]
I assume you're referring to over the Python API and not (e.g.,) the STP binary?

My guess (and I haven't checked): `c.value` is a long and we need some arbitrary length type to support returning values such as these.

Would a string work (maybe)?

**Comment by r4dr3fr4d** [comment]
Yes I'm using the Python API.

**Comment by aytey** [comment]
Okay, so "behind the scenes", this ends-up using `getBVUnsignedLongLong` (which gives a `c_uint64`), which is the cause of the issue.

As I mentioned, would a string be okay for this?

**Comment by r4dr3fr4d** [comment]
That would probably be fine - if I had been around for #303, I'd probably suggest using a byte-string instead, but either would work I imagine.

**Comment by TrevorHansen** [comment]
Thanks for reporting the problem.

I've had a go at fixing it in:
95868756ae2e2487b0f9405d17281b4d5394a476
82d76c804f0f3ba2396bdb145f9326aca5517379

Let me know if it doesn't do what you need or could be better.
