### ISSUE TITLE
How to solve this problem encountered in the installation, I followed the tutorial step by step to install

### ISSUE THREAD

**Issue by hzwthebest** [stp/stp#484]
./scripts/deps/setup-cms.sh
An error will be reported after this command is executed

![image](https://github.com/stp/stp/assets/62511655/c81643f5-212a-4f3a-93f9-52f2c3b4b447)

**Comment by TrevorHansen** [comment]
Thanks for letting us know. This should be fixed in #482 by @gussmith23 

Can you try again?
