### ISSUE TITLE
Regarding the bug issue with the STP Release version compiled.

### ISSUE THREAD

**Issue by whitecloudsun** [stp/stp#487]
When encountering STP Debug and STP Release versions compiled on the same server to solve the same SMT2 task,
the stp Debug version can provide counterexamples normally, but the stp Release version cannot provide counterexamples normally, for example,

(1) After use the compiled STP Debug version to execute stp task.smt2, return
sat
(model
(define-fun |spec_a| () (_ BitVec 32) #x00000000 )
(define-fun |impl_result_C1_FECTSYM_0| () (_ BitVec 32) #x00000000 )
(define-fun |impl_a_C1| () (_ BitVec 32) #x00000000 )
(define-fun |spec_b| () (_ BitVec 32) #x00000000 )
(define-fun |spec_result_FECTSYM_1| () (_ BitVec 32) #x00000000 )
(define-fun |impl_b_C1| () (_ BitVec 32) #x00000000 )
)

(2) After use the compiled STP Release version to execute stp task.smt2, return
sat
unsupported

Note: the make command used to compile the stp Debug and stp Release versions is the same,
except that using - DCMAKE-BUILD-TYPE=Debug for stp Debug version, and using
-DCMAKE-BUILD-TYPE=Release for stp Release version.

I would like to ask that is this a bug in your STP itself, or is it caused by some other reason?
I hope to receive your detailed response as soon as possible. Thank you very much!

**Comment by aytey** [comment]
Can you share the output of your CMake configure step (i.e., what `cmake -DCMAKE-BUILD-TYPE=Release ..` prints) for both of these?

**Comment by TrevorHansen** [comment]
A little background then a quick guess.

In debug mode, the original input is saved and a model is produced, then the model is substituted into the original formula to check that it's indeed satisfiable (i.e. that the solver has correctly done its job).

Keeping the original input, and generating the model is costly though, so in release model it's only done if needed. In SMTLIB2 you tell the solver you need the model by sending it:
```
(set-option :produce-models true)
```
at the start.

Requesting the model if STP hasn't been asked to produce it is unsupported.

Feel free to open this again if I'm mistaken.

**Comment by whitecloudsun** [comment]
@TrevorHansen，after my experiment,  your mentioned method  works, thank you very much!

**Comment by whitecloudsun** [comment]
@aytey， thank you for your reply, currently, this issue has been resolved through the methods mentioned above.
