### ISSUE TITLE
SVN STP is out of sync with GitHub

### ISSUE THREAD

**Issue by delcypher** [stp/stp#62]
The STP website ( https://sites.google.com/site/stpfastprover/ ) still lists the old SVN copy of STP ( https://stp-fast-prover.svn.sourceforge.net/svnroot/stp-fast-prover/trunk/stp stp ). This svn repo should be setup to mirror what is on GitHub or it should be removed.

**Comment by msoos** [comment]
Let's remove the SVN&sourceforge entirely. The large benchmarks we should forget about. They are probably not good tests, and the SMT benchmarks used for the competition are always downloadable from starexec. @hellovijay can you please delete the sourceforge repo and redirect people to the github repo?

As for the other stuff (overflow, underflow, no full SMT2 support) they are individual issues now, so let's concentrate on fixing the SVN stuff. Actually, I would love to move all the Sourceforge website over to github pages, too. Much easier to maintain. First, @hellovijay, can you please remove the SVN from Sourceforge? Thanks!

**Comment by msoos** [comment]
I'll close this one and create an issue with:

* Sourceforge must be marked as stale
* http://people.csail.mit.edu/vganesh/STP_files/stp.html must be removed

That's what we agreed on with Vijay. In the meanwhile, I have significantly cleaned up the STP google sites page (https://sites.google.com/site/stpfastprover/)

**Comment by delcypher** [comment]
@msoos Thanks for doing this!
