### ISSUE TITLE
Decide what to do with crypto-tests

### ISSUE THREAD

**Issue by delcypher** [stp/stp#82]
I've not setup the tests in `tests/query-files/crypto-tests/`. These need looking at. If they are too slow they need to be put into a different repository for slower tests.

**Comment by msoos** [comment]
I cleaned them up, they should be added to the test suite. @delcypher  can you do that please? I couldn't quite handle the 'lit' system, again. Sorry.

**Comment by delcypher** [comment]
@msoos I started looking at but I'm having a weird issue with one of the tests. Could you try reproducing it?

1. Rename ``tests/query-files/crypto-tests/rsa_1024_bit_prime_1s_only.stp.cvc.fixme`` to ``tests/query-files/crypto-tests/rsa_1024_bit_prime_1s_only.stp.cvc``

2. Go into the ``tests/query-files/crypto-tests``. Run

```
/absolute/path/to/stp ./rsa_1024_bit_prime_1s_only.stp.cvc
```

After roughly 13 seconds I get answer like

```
ASSERT( p = 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000CB0DF8F842B1BCCE70D83851BFBFEC0FBF8A2C8670AC2B22EE251B4809C258FA09277E46079C3C5C88B7E34973A99724E9E67CB3A0B3863F4CDC091C53955C6955AB35CF7A966DA003B9 );
ASSERT( q = 0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001F121E78A1E2011266292B5B978955F90AC49BE223FD378ADB86B4008278E9178B8F8B5E4C1412FA35CC4AC669E6ECF4D1DFC4E6599BEA64BF47B863DEF865A1AFFB427561F6AD12001 );
ASSERT( n = 0x0000018A5104CE3A90F4FF0B82B35C6B042CBB10695E5C895F68DC15D0EFDD6A256E7C9E18502DBDBD61412BFC50F669954788B6FB4CF9C161508F6017E5E82B988ACB504656F61CDF924A7955D7ED4F7889FF0FAB12856A672C510E62965135F580AEAD8B39E48EB3E3A1A8D7224EA95A867F8355E2AFAF072AECFE77C583350F8F5A5FF4B27CB6451B9D49A9DB3025A2DF122023B9 );
Invalid.
```

3. Now run like this

```
/absolute/path/to/stp `pwd`/rsa_1024_bit_prime_1s_only.stp.cvc
```

No response after a minute. I have no idea why changing how the query file path is written is changing performance...

**Comment by msoos** [comment]
Actually, I think it was the interactive nature of STP that got messed up there, i.e. it was not running. I can run the system in both ways and it works well. Can you check that STP is indeed taking CPU in the latter case? Maybe we need to fix something about the command line parsing there. Maybe you have a "space" in the `ṗwd`?

**Comment by TrevorHansen** [comment]
This all seems to be OK now.
