### ISSUE TITLE
Decide what to do with various odd programs

### ISSUE THREAD

**Issue by delcypher** [stp/stp#85]
I do not know what to do with the following programs in `tests/api/C`
- biosat-rna.cpp
- cvc-to-c.cpp
- userguided-absrefine.cpp

It is not obvious to me how they could be made into Unit tests.

**Comment by msoos** [comment]
* The "userguided-absrefine.cpp" is deprecated, the code in STP is disabled, I suggest we remove this file and all the disabled code from STP. Most probably stale and not working. Would you agree with this?

* cvc-to-c wow, this is cool! It can convert CVC to C. Also, probably SMT to C too. Pretty useful, I think. I'll take a look.

* biosat-rna.cpp This is research stuff as far as I could tell. Not really STP, and should not be in the GIT. I suggest we delete. Would you be OK with this?

**Comment by msoos** [comment]
OK, biosat and userguided has been dealt with. cvc-to-c is the only thing left. It's interesting, but I think writing a python parser is probably better and easier. I'll think about it.

**Comment by TrevorHansen** [comment]
I've moved cvc-to-c into the tools directory, and will get it working, if it's easy to, as part of #342
