### ISSUE TITLE
Fix leaks for C API tests

### ISSUE THREAD

**Issue by delcypher** [stp/stp#86]
When I enable ``USE_VALGRIND`` the C API tests appear to have lots of memory leaks.

We should investigate these once the test suites have stabilised to passing states without leak checks.

**Comment by msoos** [comment]
Isn't this essentially unfixable thanks to a badly designed C interface?

**Comment by delcypher** [comment]
@msoos It might hackable if the existing C API tests were changed to clean up everything. Not sure it's worth it though because

* Most of the C API tests aren't very good. I just took old code but didn't add many assertions
* The C API isn't very good. See #90

**Comment by msoos** [comment]
Yep. Let's close this. I want to keep the issue tracker more to the point, instead of having stale wishlist. Instead, let's try to make sure the new C api tests we add have the asserts inside.
