### ISSUE TITLE
The "lit" tool should use its own Python interpreter

### ISSUE THREAD

**Issue by smcc** [stp/stp#88]
The wiki page about the new testing infrastructure recommends that if you don't have the permissions to install the "lit" tool as part of your system-wide Python installation, you can use the virtualenv tool. However in my testing this didn't actually work, because the Makefile tried to run lit using its own favorite Python interpreter (e.g., /usr/bin/python), whereas virtualenv requires the script to be run with a special wrapped Python interpreter which is mentioned in the script's #! line. But it did work after I removed the explicit Python reference from the makefile. For reference my change is at:

https://github.com/bitblaze-fuzzball/stp/commit/2594114f7b53f1665da37a6b25a5fb862266019a

**Comment by msoos** [comment]
Let's see if TravisCI likes it. If it does, I merge and we are good. In that case, it works in both cases so there is no need to have the python hard-coded and this issue can be closed :)

**Comment by msoos** [comment]
Okay, so the cmake now has an option to specify the python interpreter explicitly (run `cmake-gui ...` from `build`) Also, the virtualenv should work out of the box. I am closing this. Please re-open if there are further issues with building!
